/**
 * Registry + generic loader for the first-party BUNDLED reference plugins (slice S5).
 *
 * There is now more than one first-party bundled reference plugin. This module is the
 * host-side generalization: a small FROZEN, compiled-in registry of the bundled plugins
 * (BUNDLED_PLUGINS) and a `loadBundledPlugin(plugin_id)` that integrity-verifies a
 * bundle ONLY when it is named by that registry. Trust does NOT reduce to a bundle's own
 * self-declared key: it derives from "ships in the signed release", i.e. presence in
 * this fixed registry AND a signature that verifies against the PUBLIC KEY PINNED IN THAT
 * REGISTRY (public_key_b64, compiled into the signed release). The on-disk directory is
 * resolved INTERNALLY from the registry entry (never from a caller-supplied path),
 * realpath-checked for EQUALITY against the registry's expected location, the bundle's
 * signature is checked against the registry-pinned key (a self-shipped key may only echo
 * it), and the loaded governance + signer identity are asserted to MATCH the registry
 * spec. Each bundle is independently signed with its own key; the public half is BOTH
 * pinned in this registry and echoed in the bundle's first-party-signer.json.
 *
 * SECURITY (fail-closed): there is deliberately NO exported arbitrary-path bundle loader.
 * An arbitrary-path loader is an arbitrary-code-execution fail-open: an attacker who can
 * write a plugin directory could self-sign governance.yaml + first-party-signer.json +
 * SIGNATURE.json + bin/evil.mjs with their OWN key and have the host "verify" and spawn
 * it. The path-based primitive (`loadBundleFromDirInternal`) is module-private and MUST
 * NEVER be called with an untrusted or caller-supplied path; the only caller is the
 * registry-gated `loadBundledPlugin`.
 *
 * These are FIRST-PARTY BUNDLED reference plugins (second reference plugin included),
 * NOT third-party or marketplace plugins. Third-party install stays F1-gated (design
 * D2). "bundled" never means "integrity-skipped": every bundle passes the same §3.1a
 * verifyBundle hash-check and runs under the identical launcher/confinement path. The
 * supervisor isolates the plugins from each other, so one bundle's fault (a hostile or
 * failing plugin, a tampered SIGNATURE.json) cannot corrupt or take down another.
 *
 * `blocklist.ts` keeps its blocklist-specific loader surface (frozen export NAMES), but
 * its loaders now DELEGATE to `loadBundledPlugin` here: they no longer honor a caller
 * path or a caller-supplied signer (that was a sibling arbitrary-code-execution fail-open).
 * This module is the ONE chokepoint - every exported loader funnels through it.
 */

import { promises as fs, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { canonicalizeToBytes } from "../canonical-json.js";
import { reject } from "../errors.js";
import { parseGovernance, type Governance } from "../governance.js";
import {
  sha256Hex,
  verifyBundle,
  type BundleDescriptor,
  type ObservedBundle,
  type SignatureFile,
  type TrustedSigner,
} from "../manifest.js";

/** The committed signer pubkey wrapper the build step writes alongside each SIGNATURE.json. */
export const FIRST_PARTY_SIGNER_FILENAME = "first-party-signer.json";

/** A first-party bundled reference plugin: its stable id, directory, and PINNED signer. */
export interface BundledPluginSpec {
  /** Stable plugin id; must match the bundle's governance.yaml plugin_id. */
  plugin_id: string;
  /** Bundle directory name under reference-plugin/ (e.g. "blocklist"). */
  dirName: string;
  /** Expected first-party signer id the bundle's SIGNATURE.json must carry. */
  signer_id: string;
  /**
   * Expected first-party key id for this bundle. Distinct per bundle so the
   * (signer_id, key_id) identity tuple is unique across the registry (a future
   * third-party signer registry may key signers by this tuple).
   */
  key_id: string;
  /**
   * The PINNED Ed25519 public key (base64, raw 32 bytes) this bundle's signature MUST
   * verify against. This is the ROOT OF TRUST: it is compiled into the signed release,
   * NOT read from the bundle. The bundle's self-shipped first-party-signer.json is no
   * longer the trust root - it may only ECHO this pinned key (any divergence is rejected).
   * Regenerated by scripts/sign-reference-plugin.mjs --print-registry after any re-sign.
   */
  public_key_b64: string;
}

/**
 * The FROZEN, compiled-in registry of first-party bundled reference plugins. This is the
 * ROOT OF TRUST for bundled-plugin loading: `loadBundledPlugin` will load ONLY a plugin
 * named here, resolving its directory internally from `dirName`, and will verify the
 * bundle's signature against the `public_key_b64` PINNED HERE (never a bundle-self-shipped
 * key). To add a bundled plugin, add a row here (with its pinned pubkey), add its dirName
 * to REFERENCE_PLUGIN_BUNDLES in scripts/copy-templates.js, and add its
 * {dir, entry, signerId, keyId} to BUNDLES in scripts/sign-reference-plugin.mjs, then run
 * `node scripts/sign-reference-plugin.mjs --print-registry` and paste the pinned pubkeys
 * here. Each (signer_id, key_id) tuple MUST be unique. All rows are FIRST-PARTY BUNDLED
 * plugins; third-party install is a separate F1-gated path.
 */
export const BUNDLED_PLUGINS: readonly BundledPluginSpec[] = [
  {
    plugin_id: "ai.sanctuary.blocklist",
    dirName: "blocklist",
    signer_id: "ai.sanctuary.first-party",
    key_id: "release-v1",
    public_key_b64: "M4I6Jsr4NR6HBofRXRhSP0vYiVXcxLuiwHwJY6yucJw=",
  },
  {
    plugin_id: "ai.sanctuary.hosts-blocklist",
    dirName: "hosts-blocklist",
    signer_id: "ai.sanctuary.first-party",
    key_id: "hosts-blocklist-v1",
    public_key_b64: "LHDRPc9Mw5rZXd5R8LfCmubqp4WL0SvJ5EVY73yLFvA=",
  },
];

/** The registry-pinned signer for a spec, decoded to a TrustedSigner (the trust root). */
export function pinnedSignerFor(spec: BundledPluginSpec): TrustedSigner {
  return {
    signer_id: spec.signer_id,
    key_id: spec.key_id,
    publicKey: new Uint8Array(Buffer.from(spec.public_key_b64, "base64")),
  };
}

/** Resolve the frozen registry spec for a plugin id, or fail closed if it is not registered. */
export function bundledPluginSpec(plugin_id: string): BundledPluginSpec {
  const spec = BUNDLED_PLUGINS.find((p) => p.plugin_id === plugin_id);
  if (!spec) {
    reject(
      "signature_plugin_mismatch",
      `"${plugin_id}" is not a registered first-party bundled plugin`,
    );
  }
  return spec;
}

export interface LoadedBundledPlugin {
  bundleDir: string;
  governance: Governance;
  descriptor: BundleDescriptor;
  observed: ObservedBundle;
  /** sha256 over the canonical descriptor - the exact installed artifact set id. */
  bundleHash: string;
  /** Absolute path to the plugin entry binary. */
  entryPath: string;
}

/**
 * The lexical candidate directories the registry permits for a bundle, in resolution
 * order (source sibling, dist copy, dist->src fallback). These are computed by pure
 * path joins on this module's own directory + the registry dirName - they do NOT follow
 * a symlink at the final segment, so they are the AUTHORITATIVE expected locations that
 * the realpath gate compares against. Kept in one place so bundledPluginDir (which picks
 * a candidate) and assertRegistryPath (which validates the pick) can never diverge.
 */
function registryCandidateDirs(spec: BundledPluginSpec): string[] {
  const thisDir = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    // case 1: source layout - bundle is a sibling directory of this module
    path.join(thisDir, spec.dirName),
    // case 2: bundled dist - copy-templates places it under dist/reference-plugin/
    path.join(thisDir, "reference-plugin", spec.dirName),
  ];
  // case 3: dist fall back to a src checkout (local dev before a build copy)
  if (thisDir.includes(`${path.sep}dist`)) {
    const srcGuess = thisDir.replace(`${path.sep}dist`, `${path.sep}src`);
    candidates.push(path.join(srcGuess, spec.dirName));
  }
  return candidates;
}

/**
 * Resolve a bundled plugin's directory by its spec, across the same layouts the
 * original blocklist resolver handled (source sibling, dist copy, dist->src fallback).
 * The governance.yaml marker must be present for a candidate to win.
 */
export function bundledPluginDir(spec: BundledPluginSpec): string {
  const marker = "governance.yaml";
  const candidates = registryCandidateDirs(spec);
  for (const candidate of candidates) {
    if (existsSync(path.join(candidate, marker))) return candidate;
  }
  // Default to the source-layout sibling; a caller reading it gets a clear ENOENT
  // rather than a silent wrong directory.
  return candidates[0]!;
}

/**
 * Enumerate a bundle directory into the (files, nonRegular, signatureFileCount) shape
 * the verifier consumes. Reports what is on disk (including non-regular entries) so the
 * verifier can fail closed on them; this function is NOT the gate.
 */
export async function enumerateBundleDir(
  bundleDir: string,
  entryRel: string,
): Promise<ObservedBundle> {
  const files: Array<{ path: string; sha256: string; mode_exec: boolean; size: number }> = [];
  const nonRegular: string[] = [];
  let signatureFileCount = 0;

  async function walk(absDir: string, relPrefix: string): Promise<void> {
    const entries = await fs.readdir(absDir, { withFileTypes: true });
    for (const entry of entries) {
      const abs = path.join(absDir, entry.name);
      const rel = relPrefix ? `${relPrefix}/${entry.name}` : entry.name;
      if (entry.isSymbolicLink()) {
        nonRegular.push(rel);
        continue;
      }
      if (entry.isDirectory()) {
        await walk(abs, rel);
        continue;
      }
      if (!entry.isFile()) {
        nonRegular.push(rel);
        continue;
      }
      if (rel === "SIGNATURE.json") {
        signatureFileCount += 1;
        continue;
      }
      const data = await fs.readFile(abs);
      const stat = await fs.stat(abs);
      files.push({
        path: rel,
        sha256: sha256Hex(new Uint8Array(data)),
        // The entry binary is forced executable to match the signed descriptor; a
        // git checkout may drop the exec bit. Every OTHER file's exec bit is
        // cross-checked against disk by verifyBundle.
        mode_exec: rel === entryRel ? true : (stat.mode & 0o111) !== 0,
        size: data.length,
      });
    }
  }

  await walk(bundleDir, "");
  files.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return { files, nonRegular, signatureFileCount };
}

/**
 * Read the committed first-party signer public key from a bundle. This is the key the
 * host verifies THAT bundle against; it ships with the bundle as part of the signed
 * release (trust = release integrity), NOT an independent host-policy pin and NOT a
 * third-party signer-registry entry (that path is F1-gated). The (signer_id, key_id) it
 * carries is asserted against the frozen registry spec by loadBundledPlugin.
 */
export async function readBundledSignerFrom(bundleDir: string): Promise<TrustedSigner> {
  const raw = await fs.readFile(path.join(bundleDir, FIRST_PARTY_SIGNER_FILENAME), "utf8");
  const parsed = JSON.parse(raw) as {
    signer_id?: unknown;
    key_id?: unknown;
    public_key_b64?: unknown;
  };
  if (
    typeof parsed.signer_id !== "string" ||
    typeof parsed.key_id !== "string" ||
    typeof parsed.public_key_b64 !== "string"
  ) {
    throw new Error("first-party-signer.json is malformed");
  }
  return {
    signer_id: parsed.signer_id,
    key_id: parsed.key_id,
    publicKey: new Uint8Array(Buffer.from(parsed.public_key_b64, "base64")),
  };
}

/**
 * Compute the AUTHORITATIVE expected realpath of one registry candidate: realpath the
 * candidate's PARENT (legitimately in-tree, so any symlinked ancestor is normalized) and
 * append the registry dirName LITERALLY. This deliberately does NOT follow a symlink at
 * the final segment, so it is the true "where the registry says this bundle lives" - the
 * fixed point the resolved dir's realpath must equal. Returns undefined if the parent
 * cannot be resolved (e.g. the src-fallback parent does not exist in this layout).
 */
async function expectedCandidateRealpath(candidate: string): Promise<string | undefined> {
  const parent = path.dirname(candidate);
  const base = path.basename(candidate);
  try {
    const realParent = await fs.realpath(parent);
    return path.join(realParent, base);
  } catch {
    return undefined;
  }
}

/**
 * Assert that a resolved bundle directory is EXACTLY the one the frozen registry names,
 * by realpath EQUALITY. bundledPluginDir resolves from the registry's dirName by pure
 * path joins, but a symlink swap at the final segment (even a same-basename in-tree
 * symlink like reference-plugin/.evil/hosts-blocklist -> /attacker/hosts-blocklist) could
 * make the resolved dir's realpath point at a foreign target. We recompute each registry
 * candidate's OWN expected realpath (parent realpath + literal dirName) and require
 * fs.realpath(bundleDir) to EQUAL one of them. A same-basename descendant, a symlink
 * redirect, or any target that is not byte-for-byte the registry location is rejected
 * (named rejection, fail-closed).
 */
async function assertRegistryPath(spec: BundledPluginSpec, bundleDir: string): Promise<void> {
  // The last segment must still be the registry dirName (cheap pre-check).
  if (path.basename(bundleDir) !== spec.dirName) {
    reject(
      "bundle_path_traversal",
      `bundled plugin "${spec.plugin_id}" resolved to unexpected directory "${bundleDir}"`,
    );
  }
  let realResolved: string;
  try {
    realResolved = await fs.realpath(bundleDir);
  } catch {
    reject(
      "bundle_missing_listed_file",
      `bundled plugin "${spec.plugin_id}" directory "${bundleDir}" does not resolve`,
    );
  }
  // The realpath of the resolved dir must EQUAL the expected realpath of some registry
  // candidate. Equality (not startsWith/descendant) is the point: a symlink at the final
  // segment resolves realResolved elsewhere, breaking equality even if its basename or an
  // ancestor still lies in-tree.
  const expected: string[] = [];
  for (const candidate of registryCandidateDirs(spec)) {
    const real = await expectedCandidateRealpath(candidate);
    if (real !== undefined) expected.push(real);
  }
  if (!expected.includes(realResolved)) {
    reject(
      "bundle_path_traversal",
      `bundled plugin "${spec.plugin_id}" realpath "${realResolved}" is not the registry location for dir "${spec.dirName}"`,
    );
  }
}

/**
 * INTERNAL, PATH-BASED primitive. MUST NEVER be called with an untrusted or
 * caller-supplied path. It verifies a bundle's signature against the REGISTRY-PINNED
 * signer public key passed in `pinnedSigner` (the trust root), NOT the bundle's own
 * self-shipped key. If the bundle self-ships a first-party-signer.json, that key may only
 * ECHO the pinned key: any divergence is rejected, so the self-shipped key can no longer
 * be the trust root even for a same-(signer_id,key_id) attacker key. The ONLY legitimate
 * caller is the registry-gated loadBundledPlugin below, which has already pinned the
 * directory to a frozen registry entry, realpath-checked it, and supplies the pinned
 * signer from the compiled-in registry. It is deliberately NOT exported.
 */
async function loadBundleFromDirInternal(
  bundleDir: string,
  pinnedSigner: TrustedSigner,
): Promise<LoadedBundledPlugin> {
  const governanceText = await fs.readFile(path.join(bundleDir, "governance.yaml"), "utf8");
  const governance = parseGovernance(governanceText);

  // If the bundle ships a self-declared signer, it must EQUAL the registry-pinned key.
  // The registry pin is the trust root; a self-shipped key that differs (even with a
  // matching signer_id/key_id tuple) is a foreign key and is rejected fail-closed.
  const selfShipped = await readBundledSignerFrom(bundleDir);
  const selfShippedB64 = Buffer.from(selfShipped.publicKey).toString("base64");
  const pinnedB64 = Buffer.from(pinnedSigner.publicKey).toString("base64");
  if (
    selfShipped.signer_id !== pinnedSigner.signer_id ||
    selfShipped.key_id !== pinnedSigner.key_id ||
    selfShippedB64 !== pinnedB64
  ) {
    reject(
      "signature_signer_mismatch",
      `bundle "${governance.plugin_id}" self-shipped signer does not equal the registry-pinned key`,
    );
  }

  const signatureRaw = await fs.readFile(path.join(bundleDir, "SIGNATURE.json"), "utf8");
  const signatureFile = JSON.parse(signatureRaw) as SignatureFile;

  const observed = await enumerateBundleDir(bundleDir, governance.entry);

  // Trust root: resolve ONLY the registry-pinned signer. A descriptor claiming any other
  // (signer_id, key_id) resolves to undefined -> signature_signer_unknown, fail-closed.
  const descriptor = verifyBundle(signatureFile, {
    resolveSigner: (signer_id, key_id) =>
      signer_id === pinnedSigner.signer_id && key_id === pinnedSigner.key_id
        ? pinnedSigner
        : undefined,
    observed,
    entryPath: governance.entry,
    expect: {
      plugin_id: governance.plugin_id,
      version: governance.version,
      channel: governance.channel,
    },
  });

  const bundleHash = sha256Hex(canonicalizeToBytes(descriptor));

  return {
    bundleDir,
    governance,
    descriptor,
    observed,
    bundleHash,
    entryPath: path.join(bundleDir, governance.entry),
  };
}

/**
 * Load + integrity-verify a first-party bundled plugin BY ITS REGISTRY PLUGIN ID.
 *
 * This is the ONLY public bundle-loading surface, and it is fail-closed: the plugin_id
 * MUST be present in the frozen, compiled-in BUNDLED_PLUGINS registry. The on-disk
 * directory is resolved INTERNALLY from that registry entry (never from a caller
 * argument), realpath-checked to EQUAL the registry's expected location, and the bundle's
 * signature is verified against the PUBLIC KEY PINNED IN THE REGISTRY (compiled into the
 * signed release), never a bundle-self-shipped key. A self-shipped first-party-signer.json
 * may only echo the pinned key; any divergence is rejected. The loaded governance.plugin_id
 * + the descriptor (signer_id, key_id) are then asserted to MATCH the registry spec.
 *
 * Trust derives from "ships in the signed release" (registry presence + registry-pinned
 * key), NOT from a bundle's self-declared key: a self-signed bundle at a path outside the
 * registry, a symlink-redirected registry dir, or a same-tuple foreign key can never be
 * loaded here.
 *
 * Throws a named SubstrateError on any registry, path, key, identity, or integrity
 * failure (fail-closed); a bundle that does not pass every gate never runs. Third-party
 * install remains a separate F1-gated path.
 */
export async function loadBundledPlugin(plugin_id: string): Promise<LoadedBundledPlugin> {
  // 1. Registry gate: only a plugin the signed release ships may be loaded.
  const spec = bundledPluginSpec(plugin_id);

  // 2. Resolve the directory from the registry entry, never from a caller path.
  const bundleDir = bundledPluginDir(spec);

  // 3. realpath gate: the resolved directory's realpath must EQUAL the registry's
  //    expected location (reject a symlink swap that redirects the bundle dir elsewhere,
  //    including a same-basename in-tree symlink).
  await assertRegistryPath(spec, bundleDir);

  // 4. Per-bundle integrity against the REGISTRY-PINNED signer key (the trust root),
  //    not a bundle-self-shipped key.
  const loaded = await loadBundleFromDirInternal(bundleDir, pinnedSignerFor(spec));

  // 5. Identity gate: the loaded governance + signer identity must MATCH the frozen
  //    registry spec, not merely be self-consistent.
  if (loaded.governance.plugin_id !== spec.plugin_id) {
    reject(
      "signature_plugin_mismatch",
      `bundle governance plugin_id "${loaded.governance.plugin_id}" does not match registry id "${spec.plugin_id}"`,
    );
  }
  if (
    loaded.descriptor.signer_id !== spec.signer_id ||
    loaded.descriptor.key_id !== spec.key_id
  ) {
    reject(
      "signature_signer_mismatch",
      `bundle "${spec.plugin_id}" signer (${loaded.descriptor.signer_id}, ${loaded.descriptor.key_id}) does not match registry (${spec.signer_id}, ${spec.key_id})`,
    );
  }

  return loaded;
}
