//! Per-event producer signatures for drained enforcement events (Slice L1).
//!
//! # Why this exists
//!
//! Before Slice L1, an enforcement event drained from the daemon's WAL was
//! trusted by Sanctuary main *because it arrived over the mutually-pinned IPC
//! channel from the separately-authenticated daemon process* — not because
//! each event carried its own proof of origin. On the read side, the audit
//! entry's authenticity rested on a plain-text provenance marker
//! (`cw_source`), which any in-process TS module already holding the
//! `AuditLog` reference can forge.
//!
//! Slice L1 closes the in-process forgery hole on Linux by having the daemon
//! sign every drained enforcement event with a **producer key the in-process
//! TS server cannot reach**, and having the consumer verify that signature
//! against the producer's pinned public key before accepting the event as
//! enforcement evidence.
//!
//! # The key separation (the load-bearing fact)
//!
//! The daemon does NOT hold the fortress *signing* key — that key is held by
//! Sanctuary main, which signs the daemon's handshake nonce (`ipc::auth`).
//! The daemon only ever holds the fortress *public* pin. So we cannot sign
//! producer signatures with "the fortress key the daemon already holds": it
//! does not have it.
//!
//! Instead the daemon owns a **dedicated audit-producer keypair**:
//!
//!   - private key: `<policy_dir>/audit-producer.key` (32 raw Ed25519 seed
//!     bytes), generated by the daemon at boot if absent, written `0600`,
//!     root-owned. It is NEVER transmitted over IPC and never written where
//!     the (non-root) in-process TS server reads.
//!   - public key: `/run/sanctuary/<fortress-id>/audit-producer.pub` in the
//!     server profile (32 raw verifying-key bytes), world-readable inside the
//!     root-created broker-traversable runtime directory and TOFU-pinned by the
//!     consumer. It is republished from the persistent private key each boot.
//!
//! Because the private seed lives only in the daemon process / a root-owned
//! file, an in-process TS forger can mint the `cw_source` marker but cannot
//! produce a signature that verifies against the pinned producer public key.
//! Forgery fails closed at the reader.
//!
//! # Anti-replay binding
//!
//! The signature covers `seq` and `captured_at_unix_ms` in addition to the
//! canonical event bytes, so a genuine past signed event replayed to fake
//! current liveness is rejected: the consumer already tracks `lastAckedSeq`
//! and rejects `seq <= lastAckedSeq` as a regression, and the timestamp lets
//! the freshness window reject stale events. Without this binding, replay
//! would remain open even with per-event signing.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use base64::Engine;
use ed25519_dalek::{Signer, SigningKey, SECRET_KEY_LENGTH};
use rand_core::{OsRng, RngCore};

use crate::constants::PRODUCER_SIG_DOMAIN_PREFIX;

/// Errors emitted while loading or using the producer signing key.
#[derive(Debug, thiserror::Error)]
pub enum ProducerSigError {
    #[error("producer key io error at {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("producer private key wrong length (expected {expected}, got {actual})")]
    KeyLength { expected: usize, actual: usize },
    #[error("producer private key at {path} has insecure permissions {mode:o} (must be 0600, group/other bits clear)")]
    InsecurePermissions { path: PathBuf, mode: u32 },
    #[error("producer key path is unsafe at {path}: {reason}")]
    UnsafePath { path: PathBuf, reason: String },
}

/// Compute the canonical signing bytes for one drained enforcement event.
///
/// Layout (newline-delimited, unambiguous, cross-language reproducible):
///
/// ```text
/// PRODUCER_SIG_DOMAIN_PREFIX        (ends in '\n')
/// event_canonical_json '\n'
/// captured_at_unix_ms (decimal ASCII) '\n'
/// seq (decimal ASCII)
/// ```
///
/// The mirror is `producerSigningBytes()` in
/// `server/src/castle-wall/runtime/producer-signature.ts`; the two MUST
/// produce byte-identical input. `event_canonical_json` is the exact
/// canonical-JSON string already on the WAL; it is signed verbatim (NOT
/// re-encoded) so the producer and consumer hash the same bytes the daemon
/// committed.
pub fn producer_signing_bytes(
    event_canonical_json: &str,
    captured_at_unix_ms: u64,
    seq: u64,
) -> Vec<u8> {
    let mut out =
        Vec::with_capacity(PRODUCER_SIG_DOMAIN_PREFIX.len() + event_canonical_json.len() + 48);
    out.extend_from_slice(PRODUCER_SIG_DOMAIN_PREFIX.as_bytes());
    out.extend_from_slice(event_canonical_json.as_bytes());
    out.push(b'\n');
    out.extend_from_slice(captured_at_unix_ms.to_string().as_bytes());
    out.push(b'\n');
    out.extend_from_slice(seq.to_string().as_bytes());
    out
}

/// The daemon's audit-producer signing key. Holds the private seed in memory
/// for the daemon's lifetime; the seed is never serialized back out except to
/// the root-owned key file at first-boot generation.
pub struct ProducerSigner {
    signing_key: SigningKey,
}

impl ProducerSigner {
    /// Load the producer signing key from `key_path`, generating a fresh
    /// keypair (and persisting both halves) if the private key is absent.
    ///
    /// `key_path` holds the 32-byte Ed25519 seed (`0600`); `pub_path` holds
    /// the 32-byte verifying key (world-readable) so the consumer can pin it.
    /// On generation both files are written; on load the public file is
    /// (re)written to stay consistent with the loaded private key.
    pub fn load_or_generate(key_path: &Path, pub_path: &Path) -> Result<Self, ProducerSigError> {
        for path in [key_path, pub_path] {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).map_err(|source| ProducerSigError::Io {
                    path: parent.to_path_buf(),
                    source,
                })?;
            }
        }
        validate_key_parent(key_path)?;
        validate_key_parent(pub_path)?;
        let signing_key = if key_path
            .try_exists()
            .map_err(|source| ProducerSigError::Io {
                path: key_path.to_path_buf(),
                source,
            })? {
            // Refuse a private key that any other principal can read. A
            // group/world-readable seed would let a non-daemon process recover
            // the producer key and forge signatures — exactly the hole L1
            // closes. (codex L1 HIGH #4.)
            #[cfg(unix)]
            {
                use std::os::unix::fs::MetadataExt;
                use std::os::unix::fs::PermissionsExt;
                let metadata =
                    fs::symlink_metadata(key_path).map_err(|source| ProducerSigError::Io {
                        path: key_path.to_path_buf(),
                        source,
                    })?;
                if !metadata.file_type().is_file()
                    || metadata.nlink() != 1
                    || metadata.uid() != unsafe { libc::geteuid() }
                {
                    return Err(ProducerSigError::UnsafePath {
                        path: key_path.to_path_buf(),
                        reason:
                            "private key must be a single-link regular file owned by the daemon UID"
                                .to_string(),
                    });
                }
                let mode = metadata.permissions().mode() & 0o777;
                if mode & 0o077 != 0 {
                    return Err(ProducerSigError::InsecurePermissions {
                        path: key_path.to_path_buf(),
                        mode,
                    });
                }
            }
            use std::io::Read as _;
            use std::os::unix::fs::OpenOptionsExt;
            let mut file = fs::OpenOptions::new()
                .read(true)
                .custom_flags(libc::O_NOFOLLOW | libc::O_CLOEXEC)
                .open(key_path)
                .map_err(|source| ProducerSigError::Io {
                    path: key_path.to_path_buf(),
                    source,
                })?;
            let mut bytes = Vec::new();
            if let Err(source) = file
                .by_ref()
                .take((SECRET_KEY_LENGTH + 1) as u64)
                .read_to_end(&mut bytes)
            {
                secure_zero(&mut bytes);
                return Err(ProducerSigError::Io {
                    path: key_path.to_path_buf(),
                    source,
                });
            }
            if bytes.len() != SECRET_KEY_LENGTH {
                let actual = bytes.len();
                secure_zero(&mut bytes);
                return Err(ProducerSigError::KeyLength {
                    expected: SECRET_KEY_LENGTH,
                    actual,
                });
            }
            let mut seed = [0u8; SECRET_KEY_LENGTH];
            seed.copy_from_slice(&bytes);
            let signing_key = SigningKey::from_bytes(&seed);
            secure_zero(&mut seed);
            secure_zero(&mut bytes);
            signing_key
        } else {
            let signing_key = SigningKey::generate(&mut OsRng);
            write_private_key(key_path, &signing_key)?;
            signing_key
        };

        // Always (re)publish the public half so it stays consistent with the
        // private key currently in use.
        write_public_key(pub_path, &signing_key)?;
        Ok(Self { signing_key })
    }

    /// Construct directly from an in-memory signing key (tests).
    pub fn from_signing_key(signing_key: SigningKey) -> Self {
        Self { signing_key }
    }

    /// Sign one drained enforcement event, returning the base64url-no-pad
    /// signature over `producer_signing_bytes(...)`.
    pub fn sign_event(
        &self,
        event_canonical_json: &str,
        captured_at_unix_ms: u64,
        seq: u64,
    ) -> String {
        let bytes = producer_signing_bytes(event_canonical_json, captured_at_unix_ms, seq);
        let sig = self.signing_key.sign(&bytes);
        base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(sig.to_bytes())
    }

    /// The base64url-no-pad verifying (public) key, for diagnostics/tests.
    pub fn public_key_b64url(&self) -> String {
        base64::engine::general_purpose::URL_SAFE_NO_PAD
            .encode(self.signing_key.verifying_key().to_bytes())
    }
}

fn secure_zero(bytes: &mut [u8]) {
    for byte in bytes {
        // Volatile writes plus the compiler fence prevent the optimizer from
        // eliding post-load secret cleanup.
        unsafe { std::ptr::write_volatile(byte, 0) };
    }
    std::sync::atomic::compiler_fence(std::sync::atomic::Ordering::SeqCst);
}

fn write_private_key(path: &Path, key: &SigningKey) -> Result<(), ProducerSigError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| ProducerSigError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    validate_key_parent(path)?;
    // Create the file with 0600 BEFORE writing any bytes, so the private seed
    // is never momentarily readable by group/other (the chmod-after-write race
    // codex L1 HIGH #4 flagged). On Unix we set the mode at open time; on other
    // platforms we fall back to plain write (production target is Linux).
    #[cfg(unix)]
    {
        use std::io::Write as _;
        use std::os::unix::fs::OpenOptionsExt;
        let mut f = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(path)
            .map_err(|source| ProducerSigError::Io {
                path: path.to_path_buf(),
                source,
            })?;
        f.write_all(&key.to_bytes())
            .map_err(|source| ProducerSigError::Io {
                path: path.to_path_buf(),
                source,
            })?;
        f.sync_all().map_err(|source| ProducerSigError::Io {
            path: path.to_path_buf(),
            source,
        })?;
    }
    #[cfg(not(unix))]
    {
        fs::write(path, key.to_bytes()).map_err(|source| ProducerSigError::Io {
            path: path.to_path_buf(),
            source,
        })?;
    }
    Ok(())
}

fn write_public_key(path: &Path, key: &SigningKey) -> Result<(), ProducerSigError> {
    validate_key_parent(path)?;
    let parent = path.parent().expect("validated above");
    let tmp = parent.join(format!(".audit-producer.pub.{:016x}.tmp", OsRng.next_u64()));
    #[cfg(unix)]
    {
        use std::io::Write as _;
        use std::os::unix::fs::OpenOptionsExt;
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o644)
            .open(&tmp)
            .map_err(|source| ProducerSigError::Io {
                path: tmp.clone(),
                source,
            })?;
        file.write_all(&key.verifying_key().to_bytes())
            .and_then(|_| file.sync_all())
            .map_err(|source| ProducerSigError::Io {
                path: tmp.clone(),
                source,
            })?;
        fs::rename(&tmp, path).map_err(|source| ProducerSigError::Io {
            path: path.to_path_buf(),
            source,
        })?;
        fs::File::open(parent)
            .and_then(|directory| directory.sync_all())
            .map_err(|source| ProducerSigError::Io {
                path: parent.to_path_buf(),
                source,
            })?;
    }
    #[cfg(not(unix))]
    fs::write(path, key.verifying_key().to_bytes()).map_err(|source| ProducerSigError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(path)
            .map_err(|source| ProducerSigError::Io {
                path: path.to_path_buf(),
                source,
            })?
            .permissions();
        perms.set_mode(0o644);
        fs::set_permissions(path, perms).map_err(|source| ProducerSigError::Io {
            path: path.to_path_buf(),
            source,
        })?;
    }
    Ok(())
}

fn validate_key_parent(path: &Path) -> Result<(), ProducerSigError> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::{MetadataExt, PermissionsExt};
        let parent = path.parent().ok_or_else(|| ProducerSigError::UnsafePath {
            path: path.to_path_buf(),
            reason: "path has no parent".to_string(),
        })?;
        let metadata = fs::symlink_metadata(parent).map_err(|source| ProducerSigError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
        // Linux is the production target and normally has a lexical `/var`.
        // macOS aliases `/var` to `/private/var`, so comparing the whole
        // canonical path there would reject every secure TempDir used by the
        // cross-platform contract tests. `symlink_metadata` below still
        // rejects a final-component parent symlink on every Unix target; on
        // Linux, additionally reject a symlink in any ancestor component.
        #[cfg(target_os = "linux")]
        {
            let canonical = fs::canonicalize(parent).map_err(|source| ProducerSigError::Io {
                path: parent.to_path_buf(),
                source,
            })?;
            if canonical != parent {
                return Err(ProducerSigError::UnsafePath {
                    path: parent.to_path_buf(),
                    reason: "parent path traverses a symlink".to_string(),
                });
            }
        }
        let mode = metadata.permissions().mode() & 0o777;
        if !metadata.file_type().is_dir()
            || metadata.uid() != unsafe { libc::geteuid() }
            || mode & 0o022 != 0
        {
            return Err(ProducerSigError::UnsafePath {
                path: parent.to_path_buf(),
                reason: format!("parent must be a real daemon-owned directory without group/world write (mode {mode:o})"),
            });
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::{Signature, Verifier, VerifyingKey};
    use tempfile::TempDir;

    fn verifying_key_from_pub(path: &Path) -> VerifyingKey {
        let bytes = fs::read(path).unwrap();
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&bytes);
        VerifyingKey::from_bytes(&arr).unwrap()
    }

    #[test]
    fn signing_bytes_are_stable_and_bound_to_seq_and_ts() {
        let a = producer_signing_bytes("{\"k\":1}", 1000, 7);
        let b = producer_signing_bytes("{\"k\":1}", 1000, 7);
        assert_eq!(a, b);
        // Changing seq, timestamp, or body changes the bytes.
        assert_ne!(a, producer_signing_bytes("{\"k\":1}", 1000, 8));
        assert_ne!(a, producer_signing_bytes("{\"k\":1}", 1001, 7));
        assert_ne!(a, producer_signing_bytes("{\"k\":2}", 1000, 7));
        // The domain prefix is present.
        assert!(a.starts_with(PRODUCER_SIG_DOMAIN_PREFIX.as_bytes()));
    }

    #[test]
    fn sign_then_verify_round_trips_against_published_pub() {
        let dir = TempDir::new().unwrap();
        let key_path = dir.path().join("audit-producer.key");
        let pub_path = dir.path().join("audit-producer.pub");
        let signer = ProducerSigner::load_or_generate(&key_path, &pub_path).unwrap();

        let sig_b64 = signer.sign_event("{\"event_type\":\"egress_blocked\"}", 1718000000000, 42);
        let sig_bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .decode(sig_b64.as_bytes())
            .unwrap();
        let mut sig_arr = [0u8; 64];
        sig_arr.copy_from_slice(&sig_bytes);
        let signature = Signature::from_bytes(&sig_arr);

        let vk = verifying_key_from_pub(&pub_path);
        let message =
            producer_signing_bytes("{\"event_type\":\"egress_blocked\"}", 1718000000000, 42);
        vk.verify(&message, &signature).expect("sig must verify");
    }

    #[test]
    fn replayed_signature_fails_against_different_seq() {
        let signer = ProducerSigner::from_signing_key(SigningKey::generate(&mut OsRng));
        let vk = signer.signing_key.verifying_key();
        let sig_b64 = signer.sign_event("{\"e\":1}", 100, 5);
        let sig_bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .decode(sig_b64.as_bytes())
            .unwrap();
        let mut sig_arr = [0u8; 64];
        sig_arr.copy_from_slice(&sig_bytes);
        let signature = Signature::from_bytes(&sig_arr);
        // Verifying the same signature against a different seq's message fails.
        let replayed_message = producer_signing_bytes("{\"e\":1}", 100, 6);
        assert!(vk.verify(&replayed_message, &signature).is_err());
    }

    #[test]
    fn generated_private_key_is_owner_only() {
        let dir = TempDir::new().unwrap();
        let key_path = dir.path().join("nested/audit-producer.key");
        let pub_path = dir.path().join("nested/audit-producer.pub");
        ProducerSigner::load_or_generate(&key_path, &pub_path).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = fs::metadata(&key_path).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o600, "private producer key must be owner-only");
            let pub_mode = fs::metadata(&pub_path).unwrap().permissions().mode() & 0o777;
            assert_eq!(
                pub_mode, 0o644,
                "public producer key must be world-readable"
            );
        }
    }

    #[test]
    fn load_reuses_existing_private_key() {
        let dir = TempDir::new().unwrap();
        let key_path = dir.path().join("audit-producer.key");
        let pub_path = dir.path().join("audit-producer.pub");
        let first = ProducerSigner::load_or_generate(&key_path, &pub_path).unwrap();
        let first_pub = first.public_key_b64url();
        let second = ProducerSigner::load_or_generate(&key_path, &pub_path).unwrap();
        assert_eq!(
            first_pub,
            second.public_key_b64url(),
            "key must be stable across boots"
        );
    }

    #[cfg(unix)]
    #[test]
    fn rejects_group_or_world_readable_private_key() {
        use std::os::unix::fs::PermissionsExt;
        let dir = TempDir::new().unwrap();
        let key_path = dir.path().join("audit-producer.key");
        let pub_path = dir.path().join("audit-producer.pub");
        // First boot generates a 0600 key.
        ProducerSigner::load_or_generate(&key_path, &pub_path).unwrap();
        // Loosen it to world-readable and re-load: must refuse.
        let mut perms = fs::metadata(&key_path).unwrap().permissions();
        perms.set_mode(0o644);
        fs::set_permissions(&key_path, perms).unwrap();
        match ProducerSigner::load_or_generate(&key_path, &pub_path) {
            Err(ProducerSigError::InsecurePermissions { .. }) => {}
            Err(other) => panic!("expected InsecurePermissions, got {other:?}"),
            Ok(_) => panic!("expected a world-readable private key to be refused"),
        }
    }

    #[test]
    fn rejects_wrong_length_private_key() {
        let dir = TempDir::new().unwrap();
        let key_path = dir.path().join("audit-producer.key");
        let pub_path = dir.path().join("audit-producer.pub");
        fs::write(&key_path, b"too short").unwrap();
        // Set 0600 so we exercise the length check, not the perms check (which
        // is verified separately in rejects_group_or_world_readable_private_key).
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&key_path).unwrap().permissions();
            perms.set_mode(0o600);
            fs::set_permissions(&key_path, perms).unwrap();
        }
        match ProducerSigner::load_or_generate(&key_path, &pub_path) {
            Err(ProducerSigError::KeyLength { .. }) => {}
            Err(other) => panic!("expected KeyLength error, got {other:?}"),
            Ok(_) => panic!("expected load to reject a wrong-length private key"),
        }
    }
}
