/**
 * Sanctuary MCP Server — EU AI Act Compliance Bundle Generator
 *
 * Copyright 2026 Erik Newton
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generates an EU AI Act compliance bundle (6 Markdown documents + 1
 * JSON manifest) by walking the coverage matrix, rendering each
 * document from its template, hashing each file, and signing each
 * hash with the provider's primary Ed25519 identity.
 *
 * NOT LEGAL ADVICE. This generator produces a technical compliance
 * artifact bundle; it does not constitute a legal interpretation of
 * Regulation (EU) 2024/1689.
 */

import { sign } from "../../core/identity.js";
import { derivePurposeKey } from "../../core/key-derivation.js";
import { hash } from "../../core/hashing.js";
import { toBase64url, stringToBytes } from "../../core/encoding.js";

/**
 * Encode a byte array as a lowercase hexadecimal string. Used for
 * the bundle manifest and file attestation table so auditors can
 * verify with standard CLI tools like `sha256sum`.
 */
function bytesToHex(bytes: Uint8Array): string {
  let hex = "";
  for (let i = 0; i < bytes.length; i++) {
    hex += bytes[i]!.toString(16).padStart(2, "0");
  }
  return hex;
}
import type { SanctuaryConfig } from "../../config.js";
import type { IdentityManager } from "../../l1-cognitive/tools.js";
import type { AuditLog, AuditEntry } from "../../l2-operational/audit-log.js";
import type { PrincipalPolicy } from "../../principal-policy/types.js";
import type { StoredIdentity } from "../../core/identity.js";
import type { ToolDefinition } from "../../router.js";
import { toolResult } from "../../router.js";

import {
  COVERAGE_MATRIX_V1,
  REGULATION_VERSION,
  coverageStats,
  type CoverageRow,
} from "./coverage_matrix.js";

import {
  render,
  ROW_BLOCK_TEMPLATE,
  coverageBadge,
  formatEmitterList,
  ANNEX_IV_TECHNICAL_DOCUMENTATION_TEMPLATE,
  ARTICLE_26_DEPLOYER_LOG_TEMPLATE,
  ARTICLE_12_AUTOMATIC_LOGS_TEMPLATE,
  RISK_MANAGEMENT_SUMMARY_TEMPLATE,
  HUMAN_OVERSIGHT_STATEMENT_TEMPLATE,
  CRYPTOGRAPHIC_ATTESTATIONS_TEMPLATE,
  type TemplateContext,
} from "./templates/index.js";

import type {
  ComplianceBundleInput,
  ComplianceBundle,
  BundleFile,
  BundleManifest,
  AuditPeriodSummary,
  ManifestRowSummary,
} from "./types.js";

// ── Generator dependencies ───────────────────────────────────────────

/**
 * Runtime dependencies the generator needs. Wire these from
 * `src/index.ts` at server startup.
 */
export interface GeneratorDeps {
  config: SanctuaryConfig;
  identityManager: IdentityManager;
  masterKey: Uint8Array;
  auditLog: AuditLog;
  policy: PrincipalPolicy;
}

// ── Top-level disclaimer (shared by every document and the manifest) ─

const NOT_LEGAL_ADVICE_DISCLAIMER =
  "This bundle is a technical compliance artifact generated by the " +
  "Sanctuary Framework EU AI Act Compliance Artifact Generator. It " +
  "is NOT legal advice and does not constitute a legal interpretation " +
  "of Regulation (EU) 2024/1689. Consult qualified legal counsel " +
  "before filing or relying on this bundle for regulatory submissions.";

// ── Canonical JSON (sorted keys, no whitespace) ──────────────────────

/**
 * Deterministic canonical JSON serialisation for signing. Sorts keys
 * recursively and emits with no whitespace.
 */
function canonicalJSON(value: unknown): string {
  return JSON.stringify(sortKeys(value));
}

function sortKeys(value: unknown): unknown {
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(sortKeys);
  const sorted: Record<string, unknown> = {};
  const obj = value as Record<string, unknown>;
  for (const key of Object.keys(obj).sort()) {
    sorted[key] = sortKeys(obj[key]);
  }
  return sorted;
}

// ── Audit period summary ─────────────────────────────────────────────

/**
 * Walk the audit log for the reporting period and compute
 * aggregate statistics for the templates.
 */
export async function computeAuditPeriodSummary(
  auditLog: AuditLog,
  periodStart: string,
  periodEnd: string
): Promise<AuditPeriodSummary> {
  // Query as broadly as possible, then filter client-side for
  // the end date. The audit log query API supports `since` but not
  // `until` — so we pull everything since period_start and filter
  // by period_end in memory.
  const { entries: rawEntries } = await auditLog.query({
    since: periodStart,
    limit: 1_000_000, // effectively unbounded for this period
  });

  const endTime = new Date(periodEnd).getTime();
  const entries = rawEntries.filter(
    (e: AuditEntry) => new Date(e.timestamp).getTime() <= endTime
  );

  const byLayer: Record<"l1" | "l2" | "l3" | "l4", number> = {
    l1: 0,
    l2: 0,
    l3: 0,
    l4: 0,
  };
  const gate = {
    allow: 0,
    allow_proxy: 0,
    deny: 0,
    escalate: 0,
    unclassified: 0,
  };
  let injection = 0;
  const operationSet = new Set<string>();
  const identitySet = new Set<string>();

  for (const entry of entries) {
    byLayer[entry.layer]++;
    operationSet.add(entry.operation);
    identitySet.add(entry.identity_id);

    if (entry.operation.startsWith("gate_allow_proxy:")) {
      gate.allow_proxy++;
    } else if (entry.operation.startsWith("gate_allow:")) {
      gate.allow++;
    } else if (entry.operation.startsWith("gate_deny:")) {
      gate.deny++;
    } else if (entry.operation.startsWith("gate_escalate:")) {
      gate.escalate++;
    } else if (entry.operation.startsWith("gate_unclassified:")) {
      gate.unclassified++;
    } else if (entry.operation.startsWith("injection_detected:")) {
      injection++;
    }
  }

  return {
    period_start: periodStart,
    period_end: periodEnd,
    total_entries: entries.length,
    entries_by_layer: byLayer,
    gate_decisions: gate,
    injection_detected: injection,
    unique_operations: Array.from(operationSet).sort(),
    unique_identities: Array.from(identitySet).sort(),
  };
}

// ── Row block rendering ──────────────────────────────────────────────

/**
 * Pre-render one coverage matrix row into a Markdown block using the
 * shared ROW_BLOCK_TEMPLATE.
 */
function renderRowBlock(row: CoverageRow): string {
  const citation = `${row.citation.instrument} ${row.citation.section}`;
  return render(ROW_BLOCK_TEMPLATE, {
    row_citation: citation,
    row_title: row.citation.title,
    row_coverage_badge: coverageBadge(row.coverage),
    regulation_version: REGULATION_VERSION,
    row_requirement: row.requirement,
    row_evidence_emitted: row.evidence_emitted,
    row_evidence_emitter_list: formatEmitterList(row.evidence_emitter),
    row_manual_carveout:
      row.manual_carveout ?? "_(none — this row is fully auto-emitted)_",
  });
}

/**
 * Render an array of rows as concatenated row blocks.
 */
function renderRowBlocks(rows: CoverageRow[]): string {
  return rows.map(renderRowBlock).join("");
}

// ── Row filters by citation ──────────────────────────────────────────

function rowsWithCitationPrefix(prefix: string): CoverageRow[] {
  return COVERAGE_MATRIX_V1.rows.filter((r) =>
    r.citation.clause_id.startsWith(prefix)
  );
}

function rowsById(ids: string[]): CoverageRow[] {
  const set = new Set(ids);
  return COVERAGE_MATRIX_V1.rows.filter((r) => set.has(r.id));
}

// ── Common context builder ───────────────────────────────────────────

function buildCommonContext(
  input: ComplianceBundleInput,
  deps: GeneratorDeps,
  signer: StoredIdentity,
  auditSummary: AuditPeriodSummary,
  generatedAt: string
): TemplateContext {
  const dc = input.deployment_context;
  const policy = deps.policy;

  return {
    // Header fields
    document_title: "", // overridden per document
    document_subtitle: "", // overridden per document
    regulation_version: REGULATION_VERSION,
    matrix_version: COVERAGE_MATRIX_V1.matrix_version,
    generated_at: generatedAt,
    period_start: input.period_start,
    period_end: input.period_end,
    agent_did: input.agent_did,
    provider_legal_name: dc.provider_legal_name ?? "",
    provider_contact: dc.provider_contact ?? "",
    intended_purpose: dc.intended_purpose ?? "",
    annex_iii_class: dc.annex_iii_class ?? "",
    signer_did: signer.did,
    signer_pubkey: signer.public_key,
    sanctuary_version: deps.config.version,

    // Audit period stats
    audit_total_entries: auditSummary.total_entries,
    audit_l1_count: auditSummary.entries_by_layer.l1,
    audit_l2_count: auditSummary.entries_by_layer.l2,
    audit_l3_count: auditSummary.entries_by_layer.l3,
    audit_l4_count: auditSummary.entries_by_layer.l4,
    gate_allow_count: auditSummary.gate_decisions.allow,
    gate_allow_proxy_count: auditSummary.gate_decisions.allow_proxy,
    gate_deny_count: auditSummary.gate_decisions.deny,
    gate_escalate_count: auditSummary.gate_decisions.escalate,
    gate_unclassified_count: auditSummary.gate_decisions.unclassified,
    injection_detected_count: auditSummary.injection_detected,
    unique_identity_count: auditSummary.unique_identities.length,
    unique_operation_count: auditSummary.unique_operations.length,

    // Principal Policy fields
    tier1_rule_count: policy.tier1_always_approve.length,
    tier2_rule_count:
      Object.keys(policy.tier2_anomaly).length, // count of tier2 keys as rule count
    tier3_rule_count: policy.tier3_always_allow.length,
    tier2_new_namespace_access: policy.tier2_anomaly.new_namespace_access,
    tier2_new_counterparty: policy.tier2_anomaly.new_counterparty,
    tier2_frequency_spike_multiplier:
      policy.tier2_anomaly.frequency_spike_multiplier,
    tier2_first_session_policy: policy.tier2_anomaly.first_session_policy,
    first_session_policy: policy.tier2_anomaly.first_session_policy,
    approval_channel_type: policy.approval_channel.type,
    approval_channel_timeout_seconds:
      policy.approval_channel.timeout_seconds,
    baseline_tracker_state: "loaded", // static — baseline is always loaded at startup

    // Context gate placeholder (filled in by tool handler if available)
    context_gate_policy_count: 0,
    context_gate_enforcer_active: "unknown",
  };
}

// ── Document renderers ───────────────────────────────────────────────

interface DocSigner {
  signContent: (content: string) => string;
  sha256Hex: (content: string) => string;
}

// NOTE: SignerView interface was removed during the first typecheck
// pass — signer fields are carried through the base template context
// (signer_did, signer_pubkey) rather than as a separate parameter.

function makeSigner(
  signer: StoredIdentity,
  masterKey: Uint8Array
): DocSigner {
  const encryptionKey = derivePurposeKey(masterKey, "identity-encryption");
  return {
    signContent: (content: string) => {
      const digest = hash(stringToBytes(content));
      const sig = sign(digest, signer.encrypted_private_key, encryptionKey);
      return toBase64url(sig);
    },
    sha256Hex: (content: string) => bytesToHex(hash(stringToBytes(content))),
  };
}

/**
 * Finalise a document: render the template once, hash the rendered
 * bytes with SHA-256, and sign the hash with the provider's primary
 * Ed25519 identity. The document body itself does not contain the
 * hash or signature — those live only in the bundle manifest and in
 * the returned BundleFile.sha256 / BundleFile.signature fields.
 *
 * Verification is trivial: SHA-256(file.content) === file.sha256,
 * and Ed25519.verify(file.signature, file.sha256, signer_pubkey).
 * No special knowledge of Sanctuary internals is required.
 */
function finaliseDocument(
  template: string,
  context: TemplateContext,
  filename: string,
  ds: DocSigner
): BundleFile {
  const content = render(template, context);
  const sha256Hex = ds.sha256Hex(content);
  const signature = ds.signContent(content);

  return {
    filename,
    content,
    content_type: "text/markdown",
    sha256: sha256Hex,
    signature,
  };
}

// ── Per-document renderers ───────────────────────────────────────────

function renderAnnexIV(
  baseContext: TemplateContext,
  ds: DocSigner
): BundleFile {
  // Group Annex IV rows by section number for the template slots.
  const sections: Record<string, string> = {};
  for (let n = 1; n <= 9; n++) {
    const sectionRows = rowsWithCitationPrefix(`annex-iv-${n}`);
    sections[`sections_${n}`] =
      sectionRows.length > 0
        ? renderRowBlocks(sectionRows)
        : "_(no rows in this section)_\n\n";
  }

  const context: TemplateContext = {
    ...baseContext,
    ...sections,
    document_title: "Annex IV Technical Documentation",
    document_subtitle:
      "Prepared under Article 11 of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    ANNEX_IV_TECHNICAL_DOCUMENTATION_TEMPLATE,
    context,
    "01_annex_iv_technical_documentation.md",
    ds
  );
}

function renderArticle26(
  baseContext: TemplateContext,
  ds: DocSigner
): BundleFile {
  const rows = rowsWithCitationPrefix("art-26");
  const context: TemplateContext = {
    ...baseContext,
    rows_rendered: renderRowBlocks(rows),
    document_title: "Article 26 Deployer Log",
    document_subtitle:
      "Deployer obligations under Article 26 of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    ARTICLE_26_DEPLOYER_LOG_TEMPLATE,
    context,
    "02_article_26_deployer_log.md",
    ds
  );
}

function renderArticle12(
  baseContext: TemplateContext,
  ds: DocSigner
): BundleFile {
  // Include Art. 12 rows + the Art. 19(1) retention row (which
  // lives under clause_id "art-19-1" in the matrix but belongs in
  // the logging narrative).
  const rows = [
    ...rowsWithCitationPrefix("art-12"),
    ...rowsWithCitationPrefix("art-19"),
  ];
  const context: TemplateContext = {
    ...baseContext,
    rows_rendered: renderRowBlocks(rows),
    document_title: "Article 12 Automatic Record-Keeping",
    document_subtitle:
      "Automatic logging and retention under Articles 12 and 19(1) of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    ARTICLE_12_AUTOMATIC_LOGS_TEMPLATE,
    context,
    "03_article_12_automatic_logs.md",
    ds
  );
}

function renderRiskManagement(
  baseContext: TemplateContext,
  ds: DocSigner
): BundleFile {
  // Risk management pulls from Annex IV §5 + §2(h) + Art. 15 rows.
  const rows = rowsById([
    "annex_iv_5_risk_management",
    "annex_iv_2_h_cybersecurity",
    "annex_iv_2_b_design_specifications",
    "art_15_cybersecurity_appropriate",
    "art_15_resilience_alteration",
    "art_15_resilience_poisoning",
  ]);
  const context: TemplateContext = {
    ...baseContext,
    rows_rendered: renderRowBlocks(rows),
    document_title: "Risk Management Summary",
    document_subtitle:
      "Risk management posture under Article 9 of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    RISK_MANAGEMENT_SUMMARY_TEMPLATE,
    context,
    "04_risk_management_summary.md",
    ds
  );
}

function renderHumanOversight(
  baseContext: TemplateContext,
  ds: DocSigner
): BundleFile {
  // Art. 14 rows + Annex IV §2(e) human oversight assessment.
  const rows = [
    ...rowsWithCitationPrefix("art-14"),
    ...rowsById(["annex_iv_2_e_human_oversight_assessment"]),
  ];
  const context: TemplateContext = {
    ...baseContext,
    rows_rendered: renderRowBlocks(rows),
    document_title: "Human Oversight Statement",
    document_subtitle:
      "Human oversight measures under Article 14 of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    HUMAN_OVERSIGHT_STATEMENT_TEMPLATE,
    context,
    "05_human_oversight_statement.md",
    ds
  );
}

/**
 * The cryptographic attestations document references the
 * already-generated files' hashes and signatures. It MUST be
 * rendered after all other documents.
 */
function renderAttestations(
  baseContext: TemplateContext,
  priorFiles: BundleFile[],
  manifestSha256: string,
  manifestSignature: string,
  ds: DocSigner
): BundleFile {
  const table = [
    "| Filename | SHA-256 | Signature (base64url) |",
    "|---|---|---|",
    ...priorFiles.map(
      (f) => `| \`${f.filename}\` | \`${f.sha256}\` | \`${f.signature ?? ""}\` |`
    ),
  ].join("\n");

  const context: TemplateContext = {
    ...baseContext,
    file_attestation_table: table,
    manifest_sha256: manifestSha256,
    manifest_signature: manifestSignature,
    document_title: "Cryptographic Attestations",
    document_subtitle:
      "Bundle integrity attestations signed by the provider's primary Ed25519 identity",
  };

  return finaliseDocument(
    CRYPTOGRAPHIC_ATTESTATIONS_TEMPLATE,
    context,
    "06_cryptographic_attestations.md",
    ds
  );
}

// ── Manifest builder ─────────────────────────────────────────────────

function buildManifest(
  input: ComplianceBundleInput,
  generatedAt: string,
  signer: StoredIdentity,
  files: BundleFile[],
  ds: DocSigner
): BundleManifest {
  const stats = coverageStats(COVERAGE_MATRIX_V1);

  const rowSummaries: ManifestRowSummary[] = COVERAGE_MATRIX_V1.rows.map(
    (r) => ({
      id: r.id,
      clause_id: r.citation.clause_id,
      coverage: r.coverage,
      evidence_emitter: [...r.evidence_emitter],
    })
  );

  // Build the manifest body without the signature (to be signed).
  const manifestBody: Omit<BundleManifest, "manifest_signature"> = {
    bundle_version: "1.0",
    matrix_version: "v1",
    regulation_version: REGULATION_VERSION,
    generated_at: generatedAt,
    agent_did: input.agent_did,
    period_start: input.period_start,
    period_end: input.period_end,
    deployment_context: input.deployment_context,
    signer: {
      did: signer.did,
      public_key_base64url: signer.public_key,
    },
    files: files.map((f) => ({
      filename: f.filename,
      content_type: f.content_type,
      sha256: f.sha256,
      signature: f.signature ?? "",
    })),
    coverage_summary: {
      total_rows: stats.total_rows,
      full: stats.full,
      partial: stats.partial,
      manual_only: stats.manual_only,
      full_pct: stats.full_pct,
      partial_pct: stats.partial_pct,
      manual_only_pct: stats.manual_only_pct,
    },
    coverage_rows: rowSummaries,
    disclaimer: NOT_LEGAL_ADVICE_DISCLAIMER,
  };

  // Sign the canonical JSON of the manifest body.
  const canonical = canonicalJSON(manifestBody);
  const manifestSignature = ds.signContent(canonical);

  return {
    ...manifestBody,
    manifest_signature: manifestSignature,
  };
}

// ── Top-level generator entry point ──────────────────────────────────

/**
 * Generate a complete EU AI Act compliance bundle for the given
 * agent and reporting period.
 */
export async function generateEuAiActBundle(
  input: ComplianceBundleInput,
  deps: GeneratorDeps
): Promise<ComplianceBundle> {
  // Resolve primary identity.
  const signer = deps.identityManager.getDefault();
  if (!signer) {
    throw new Error(
      "No primary identity configured. Run identity_create and " +
        "identity_set_primary before generating a compliance bundle."
    );
  }

  const ds = makeSigner(signer, deps.masterKey);

  // Compute audit period summary.
  const auditSummary = await computeAuditPeriodSummary(
    deps.auditLog,
    input.period_start,
    input.period_end
  );

  const generatedAt = input.generated_at_override ?? new Date().toISOString();

  // Build the shared template context.
  const baseContext = buildCommonContext(
    input,
    deps,
    signer,
    auditSummary,
    generatedAt
  );

  // Render documents 1-5 in order.
  const doc1 = renderAnnexIV(baseContext, ds);
  const doc2 = renderArticle26(baseContext, ds);
  const doc3 = renderArticle12(baseContext, ds);
  const doc4 = renderRiskManagement(baseContext, ds);
  const doc5 = renderHumanOversight(baseContext, ds);

  // Build a partial manifest with docs 1-5 (and a placeholder for
  // doc 6) so we can compute its canonical hash and signature for
  // inclusion in doc 6.
  //
  // Doc 6 references the manifest SHA-256 and signature, which
  // include every file's hash. Doc 6 cannot include its OWN hash
  // and signature inside the manifest it references, because that
  // would create a cyclic dependency. Resolution:
  //
  // 1. Build the manifest with docs 1-5 only.
  // 2. Render doc 6 with that partial manifest's hash/signature.
  // 3. Rebuild the manifest with all 6 docs (doc 6 is now included).
  // 4. The final bundle's manifest_signature covers all 6 files.
  //
  // The attestations document in step 2 references the manifest
  // hash from step 1, which is the hash-over-docs-1-5. The final
  // manifest in step 3 supersedes that with a hash-over-all-6.
  // Verifiers must check the final manifest; the intermediate hash
  // in doc 6's body is a narrative reference only.

  const partialManifest = buildManifest(
    input,
    generatedAt,
    signer,
    [doc1, doc2, doc3, doc4, doc5],
    ds
  );
  const partialCanonical = canonicalJSON(partialManifest);
  const partialSha256 = ds.sha256Hex(partialCanonical);
  const partialSignature = partialManifest.manifest_signature;

  const doc6 = renderAttestations(
    baseContext,
    [doc1, doc2, doc3, doc4, doc5],
    partialSha256,
    partialSignature,
    ds
  );

  const allFiles = [doc1, doc2, doc3, doc4, doc5, doc6];

  // Final manifest covers all 6 files.
  const finalManifest = buildManifest(
    input,
    generatedAt,
    signer,
    allFiles,
    ds
  );

  return {
    manifest: finalManifest,
    files: allFiles,
  };
}

// ── MCP tool factory ─────────────────────────────────────────────────

/**
 * Factory for the `compliance_generate_eu_ai_act_bundle` MCP tool.
 * Tier 3 (auto-allow, read-only) — the tool emits documents based
 * on existing Sanctuary state and does not modify anything.
 */
export function createComplianceTools(deps: GeneratorDeps): {
  tools: ToolDefinition[];
} {
  const tools: ToolDefinition[] = [
    {
      name: "compliance_generate_eu_ai_act_bundle",
      description:
        "Generate an EU AI Act compliance bundle for a given agent " +
        "and reporting period. Produces 6 Markdown documents plus a " +
        "signed JSON manifest, covering Annex IV technical " +
        "documentation (Art. 11), Art. 12 automatic record-keeping, " +
        "Art. 13 transparency, Art. 14 human oversight, Art. 15 " +
        "cybersecurity, and Art. 26 deployer obligations. Every " +
        "file is individually SHA-256 hashed and signed with the " +
        "provider's primary Ed25519 identity. NOT LEGAL ADVICE — " +
        "consult qualified counsel before filing.",
      inputSchema: {
        type: "object",
        properties: {
          agent_did: {
            type: "string",
            description:
              "DID of the agent the bundle is being generated for.",
          },
          deployment_context: {
            type: "object",
            description:
              "Enterprise-supplied deployment facts that Sanctuary " +
              "cannot infer (vertical, intended purpose, provider " +
              "legal name, Annex III classification, etc.).",
            properties: {
              vertical: { type: "string" },
              annex_iii_class: { type: "string" },
              intended_purpose: { type: "string" },
              provider_legal_name: { type: "string" },
              provider_contact: { type: "string" },
              deployer_is_public_authority: { type: "boolean" },
              notes: { type: "string" },
            },
          },
          period_start: {
            type: "string",
            description:
              "ISO 8601 timestamp — start of the reporting period.",
          },
          period_end: {
            type: "string",
            description:
              "ISO 8601 timestamp — end of the reporting period.",
          },
        },
        required: [
          "agent_did",
          "deployment_context",
          "period_start",
          "period_end",
        ],
      },
      handler: async (args) => {
        const input: ComplianceBundleInput = {
          agent_did: String(args.agent_did),
          deployment_context:
            (args.deployment_context as ComplianceBundleInput["deployment_context"]) ??
            {},
          period_start: String(args.period_start),
          period_end: String(args.period_end),
        };

        const bundle = await generateEuAiActBundle(input, deps);

        return toolResult({
          bundle_version: bundle.manifest.bundle_version,
          matrix_version: bundle.manifest.matrix_version,
          regulation_version: bundle.manifest.regulation_version,
          agent_did: bundle.manifest.agent_did,
          generated_at: bundle.manifest.generated_at,
          period: {
            start: bundle.manifest.period_start,
            end: bundle.manifest.period_end,
          },
          signer: bundle.manifest.signer,
          coverage_summary: bundle.manifest.coverage_summary,
          file_count: bundle.files.length,
          files: bundle.files.map((f) => ({
            filename: f.filename,
            content_type: f.content_type,
            sha256: f.sha256,
            signature: f.signature,
            content_length: f.content.length,
          })),
          manifest_signature: bundle.manifest.manifest_signature,
          disclaimer: bundle.manifest.disclaimer,
          _bundle_content: {
            manifest: bundle.manifest,
            files: bundle.files.map((f) => ({
              filename: f.filename,
              content: f.content,
            })),
          },
        });
      },
    },
  ];

  return { tools };
}
