/**
 * Sanctuary MCP Server — EU AI Act Compliance Bundle Generator
 *
 * Copyright 2026 Erik Newton
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generates an EU AI Act compliance bundle (6 Markdown documents + 1
 * JSON manifest) by walking the coverage matrix, rendering each
 * document from its template, hashing each file, and signing each
 * hash with the provider's primary Ed25519 identity.
 *
 * NOT LEGAL ADVICE. This generator produces a technical compliance
 * artifact bundle; it does not constitute a legal interpretation of
 * Regulation (EU) 2024/1689.
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { sign } from "../../core/identity.js";
import { derivePurposeKey } from "../../core/key-derivation.js";
import { hash } from "../../core/hashing.js";
import { toBase64url, stringToBytes } from "../../core/encoding.js";

/**
 * Encode a byte array as a lowercase hexadecimal string. Used for
 * the bundle manifest and file attestation table so auditors can
 * verify with standard CLI tools like `sha256sum`.
 */
function bytesToHex(bytes: Uint8Array): string {
  let hex = "";
  for (let i = 0; i < bytes.length; i++) {
    hex += bytes[i]!.toString(16).padStart(2, "0");
  }
  return hex;
}
import type { SanctuaryConfig } from "../../config.js";
import type { IdentityManager } from "../../cognitive/tools.js";
import type { AuditLog, AuditEntry } from "../../operational/audit-log.js";
import type { PrincipalPolicy } from "../../principal-policy/types.js";
import type { StoredIdentity } from "../../core/identity.js";
import type { ToolDefinition } from "../../router.js";
import { toolResult } from "../../router.js";

import {
  COVERAGE_MATRIX_V1,
  REGULATION_VERSION,
  coverageStats,
  type CoverageRow,
} from "./coverage_matrix.js";

import {
  render,
  ROW_BLOCK_TEMPLATE,
  coverageBadge,
  formatEmitterList,
  ANNEX_IV_TECHNICAL_DOCUMENTATION_TEMPLATE,
  ARTICLE_26_DEPLOYER_LOG_TEMPLATE,
  ARTICLE_12_AUTOMATIC_LOGS_TEMPLATE,
  RISK_MANAGEMENT_SUMMARY_TEMPLATE,
  HUMAN_OVERSIGHT_STATEMENT_TEMPLATE,
  CRYPTOGRAPHIC_ATTESTATIONS_TEMPLATE,
  ANNEX_III_CLASSIFICATION_TEMPLATE,
  DELTA_TEMPLATE,
  type TemplateContext,
} from "./templates/index.js";

import {
  classifyAgentDescription,
  type ClassificationResult,
  type ClassificationMatch,
} from "./annex_iii.js";

import type {
  ComplianceBundleInput,
  ComplianceBundle,
  BundleFile,
  BundleManifest,
  AuditPeriodSummary,
  ManifestRowSummary,
  DeltaReport,
  DeltaRowChange,
  VerascorePublishResult,
} from "./types.js";

// ── Generator dependencies ───────────────────────────────────────────

/**
 * Runtime dependencies the generator needs. Wire these from
 * `src/index.ts` at server startup.
 */
export interface GeneratorDeps {
  config: SanctuaryConfig;
  identityManager: IdentityManager;
  masterKey: Uint8Array;
  auditLog: AuditLog;
  policy: PrincipalPolicy;
}

// ── Top-level disclaimer (shared by every document and the manifest) ─

const NOT_LEGAL_ADVICE_DISCLAIMER =
  "This bundle is a technical compliance artifact generated by the " +
  "Sanctuary Framework EU AI Act Compliance Artifact Generator. It " +
  "is NOT legal advice and does not constitute a legal interpretation " +
  "of Regulation (EU) 2024/1689. Consult qualified legal counsel " +
  "before filing or relying on this bundle for regulatory submissions.";

// ── Canonical JSON (sorted keys, no whitespace) ──────────────────────

/**
 * Deterministic canonical JSON serialisation for signing. Sorts keys
 * recursively and emits with no whitespace.
 */
function canonicalJSON(value: unknown): string {
  return JSON.stringify(sortKeys(value));
}

function sortKeys(value: unknown): unknown {
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(sortKeys);
  const sorted: Record<string, unknown> = {};
  const obj = value as Record<string, unknown>;
  for (const key of Object.keys(obj).sort()) {
    sorted[key] = sortKeys(obj[key]);
  }
  return sorted;
}

// ── Audit period summary ─────────────────────────────────────────────

/**
 * Walk the audit log for the reporting period and compute
 * aggregate statistics for the templates.
 */
export async function computeAuditPeriodSummary(
  auditLog: AuditLog,
  periodStart: string,
  periodEnd: string
): Promise<AuditPeriodSummary> {
  // Query as broadly as possible, then filter client-side for
  // the end date. The audit log query API supports `since` but not
  // `until` — so we pull everything since period_start and filter
  // by period_end in memory.
  const { entries: rawEntries } = await auditLog.query({
    since: periodStart,
    limit: 1_000_000, // effectively unbounded for this period
  });

  const endTime = new Date(periodEnd).getTime();
  const entries = rawEntries.filter(
    (e: AuditEntry) => new Date(e.timestamp).getTime() <= endTime
  );

  const byLayer: Record<"l1" | "l2" | "l3" | "l4", number> = {
    l1: 0,
    l2: 0,
    l3: 0,
    l4: 0,
  };
  const gate = {
    allow: 0,
    allow_proxy: 0,
    deny: 0,
    escalate: 0,
    unclassified: 0,
  };
  let injection = 0;
  const operationSet = new Set<string>();
  const identitySet = new Set<string>();

  for (const entry of entries) {
    byLayer[entry.layer]++;
    operationSet.add(entry.operation);
    identitySet.add(entry.identity_id);

    if (entry.operation.startsWith("gate_allow_proxy:")) {
      gate.allow_proxy++;
    } else if (entry.operation.startsWith("gate_allow:")) {
      gate.allow++;
    } else if (entry.operation.startsWith("gate_deny:")) {
      gate.deny++;
    } else if (entry.operation.startsWith("gate_escalate:")) {
      gate.escalate++;
    } else if (entry.operation.startsWith("gate_unclassified:")) {
      gate.unclassified++;
    } else if (entry.operation.startsWith("injection_detected:")) {
      injection++;
    }
  }

  return {
    period_start: periodStart,
    period_end: periodEnd,
    total_entries: entries.length,
    entries_by_layer: byLayer,
    gate_decisions: gate,
    injection_detected: injection,
    unique_operations: Array.from(operationSet).sort(),
    unique_identities: Array.from(identitySet).sort(),
  };
}

// ── Row block rendering ──────────────────────────────────────────────

/**
 * Pre-render one coverage matrix row into a Markdown block using the
 * shared ROW_BLOCK_TEMPLATE.
 */
function renderRowBlock(row: CoverageRow): string {
  const citation = `${row.citation.instrument} ${row.citation.section}`;
  return render(ROW_BLOCK_TEMPLATE, {
    row_citation: citation,
    row_title: row.citation.title,
    row_coverage_badge: coverageBadge(row.coverage),
    regulation_version: REGULATION_VERSION,
    row_requirement: row.requirement,
    row_evidence_emitted: row.evidence_emitted,
    row_evidence_emitter_list: formatEmitterList(row.evidence_emitter),
    row_manual_carveout:
      row.manual_carveout ?? "_(none — this row is fully auto-emitted)_",
  });
}

/**
 * Render an array of rows as concatenated row blocks.
 */
function renderRowBlocks(rows: CoverageRow[]): string {
  return rows.map(renderRowBlock).join("");
}

// ── Row filters by citation ──────────────────────────────────────────

function rowsWithCitationPrefix(prefix: string): CoverageRow[] {
  return COVERAGE_MATRIX_V1.rows.filter((r) =>
    r.citation.clause_id.startsWith(prefix)
  );
}

function rowsById(ids: string[]): CoverageRow[] {
  const set = new Set(ids);
  return COVERAGE_MATRIX_V1.rows.filter((r) => set.has(r.id));
}

// ── Common context builder ───────────────────────────────────────────

function buildCommonContext(
  input: ComplianceBundleInput,
  deps: GeneratorDeps,
  signer: StoredIdentity,
  auditSummary: AuditPeriodSummary,
  generatedAt: string
): TemplateContext {
  const dc = input.deployment_context;
  const policy = deps.policy;

  return {
    // Header fields
    document_title: "", // overridden per document
    document_subtitle: "", // overridden per document
    regulation_version: REGULATION_VERSION,
    matrix_version: COVERAGE_MATRIX_V1.matrix_version,
    generated_at: generatedAt,
    period_start: input.period_start,
    period_end: input.period_end,
    agent_did: input.agent_did,
    provider_legal_name: dc.provider_legal_name ?? "",
    provider_contact: dc.provider_contact ?? "",
    intended_purpose: dc.intended_purpose ?? "",
    annex_iii_class: dc.annex_iii_class ?? "",
    signer_did: signer.did,
    signer_pubkey: signer.public_key,
    sanctuary_version: deps.config.version,

    // Audit period stats
    audit_total_entries: auditSummary.total_entries,
    audit_l1_count: auditSummary.entries_by_layer.l1,
    audit_l2_count: auditSummary.entries_by_layer.l2,
    audit_l3_count: auditSummary.entries_by_layer.l3,
    audit_l4_count: auditSummary.entries_by_layer.l4,
    gate_allow_count: auditSummary.gate_decisions.allow,
    gate_allow_proxy_count: auditSummary.gate_decisions.allow_proxy,
    gate_deny_count: auditSummary.gate_decisions.deny,
    gate_escalate_count: auditSummary.gate_decisions.escalate,
    gate_unclassified_count: auditSummary.gate_decisions.unclassified,
    injection_detected_count: auditSummary.injection_detected,
    unique_identity_count: auditSummary.unique_identities.length,
    unique_operation_count: auditSummary.unique_operations.length,

    // Principal Policy fields
    tier1_rule_count: policy.tier1_always_approve.length,
    tier2_rule_count:
      Object.keys(policy.tier2_anomaly).length, // count of tier2 keys as rule count
    tier3_rule_count: policy.tier3_always_allow.length,
    tier2_new_namespace_access: policy.tier2_anomaly.new_namespace_access,
    tier2_new_counterparty: policy.tier2_anomaly.new_counterparty,
    tier2_frequency_spike_multiplier:
      policy.tier2_anomaly.frequency_spike_multiplier,
    tier2_first_session_policy: policy.tier2_anomaly.first_session_policy,
    first_session_policy: policy.tier2_anomaly.first_session_policy,
    approval_channel_type: policy.approval_channel.type,
    approval_channel_timeout_seconds:
      policy.approval_channel.timeout_seconds,
    baseline_tracker_state: "loaded", // static — baseline is always loaded at startup

    // Context gate placeholder (filled in by tool handler if available)
    context_gate_policy_count: 0,
    context_gate_enforcer_active: "unknown",
  };
}

// ── Document renderers ───────────────────────────────────────────────

interface DocSigner {
  signContent: (content: string) => string;
  sha256Hex: (content: string) => string;
}

// NOTE: SignerView interface was removed during the first typecheck
// pass — signer fields are carried through the base template context
// (signer_did, signer_pubkey) rather than as a separate parameter.

function makeSigner(
  signer: StoredIdentity,
  masterKey: Uint8Array
): DocSigner {
  const encryptionKey = derivePurposeKey(masterKey, "identity-encryption");
  return {
    signContent: (content: string) => {
      const digest = hash(stringToBytes(content));
      const sig = sign(digest, signer.encrypted_private_key, encryptionKey);
      return toBase64url(sig);
    },
    sha256Hex: (content: string) => bytesToHex(hash(stringToBytes(content))),
  };
}

/**
 * Finalise a document: render the template once, hash the rendered
 * bytes with SHA-256, and sign the hash with the provider's primary
 * Ed25519 identity. The document body itself does not contain the
 * hash or signature — those live only in the bundle manifest and in
 * the returned BundleFile.sha256 / BundleFile.signature fields.
 *
 * Verification is trivial: SHA-256(file.content) === file.sha256,
 * and Ed25519.verify(file.signature, file.sha256, signer_pubkey).
 * No special knowledge of Sanctuary internals is required.
 */
function finaliseDocument(
  template: string,
  context: TemplateContext,
  filename: string,
  ds: DocSigner
): BundleFile {
  const content = render(template, context);
  const sha256Hex = ds.sha256Hex(content);
  const signature = ds.signContent(content);

  return {
    filename,
    content,
    content_type: "text/markdown",
    sha256: sha256Hex,
    signature,
  };
}

// ── Per-document renderers ───────────────────────────────────────────

function renderAnnexIV(
  baseContext: TemplateContext,
  ds: DocSigner
): BundleFile {
  // Group Annex IV rows by section number for the template slots.
  const sections: Record<string, string> = {};
  for (let n = 1; n <= 9; n++) {
    const sectionRows = rowsWithCitationPrefix(`annex-iv-${n}`);
    sections[`sections_${n}`] =
      sectionRows.length > 0
        ? renderRowBlocks(sectionRows)
        : "_(no rows in this section)_\n\n";
  }

  const context: TemplateContext = {
    ...baseContext,
    ...sections,
    document_title: "Annex IV Technical Documentation",
    document_subtitle:
      "Prepared under Article 11 of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    ANNEX_IV_TECHNICAL_DOCUMENTATION_TEMPLATE,
    context,
    "01_annex_iv_technical_documentation.md",
    ds
  );
}

function renderArticle26(
  baseContext: TemplateContext,
  ds: DocSigner
): BundleFile {
  const rows = rowsWithCitationPrefix("art-26");
  const context: TemplateContext = {
    ...baseContext,
    rows_rendered: renderRowBlocks(rows),
    document_title: "Article 26 Deployer Log",
    document_subtitle:
      "Deployer obligations under Article 26 of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    ARTICLE_26_DEPLOYER_LOG_TEMPLATE,
    context,
    "02_article_26_deployer_log.md",
    ds
  );
}

function renderArticle12(
  baseContext: TemplateContext,
  ds: DocSigner
): BundleFile {
  // Include Art. 12 rows + the Art. 19(1) retention row (which
  // lives under clause_id "art-19-1" in the matrix but belongs in
  // the logging narrative).
  const rows = [
    ...rowsWithCitationPrefix("art-12"),
    ...rowsWithCitationPrefix("art-19"),
  ];
  const context: TemplateContext = {
    ...baseContext,
    rows_rendered: renderRowBlocks(rows),
    document_title: "Article 12 Automatic Record-Keeping",
    document_subtitle:
      "Automatic logging and retention under Articles 12 and 19(1) of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    ARTICLE_12_AUTOMATIC_LOGS_TEMPLATE,
    context,
    "03_article_12_automatic_logs.md",
    ds
  );
}

function renderRiskManagement(
  baseContext: TemplateContext,
  ds: DocSigner
): BundleFile {
  // Risk management pulls from Annex IV §5 + §2(h) + Art. 15 rows.
  const rows = rowsById([
    "annex_iv_5_risk_management",
    "annex_iv_2_h_cybersecurity",
    "annex_iv_2_b_design_specifications",
    "art_15_cybersecurity_appropriate",
    "art_15_resilience_alteration",
    "art_15_resilience_poisoning",
  ]);
  const context: TemplateContext = {
    ...baseContext,
    rows_rendered: renderRowBlocks(rows),
    document_title: "Risk Management Summary",
    document_subtitle:
      "Risk management posture under Article 9 of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    RISK_MANAGEMENT_SUMMARY_TEMPLATE,
    context,
    "04_risk_management_summary.md",
    ds
  );
}

/**
 * Format a ClassificationResult's candidate list as a Markdown
 * block for embedding in the Annex III classification document.
 */
function formatClassificationCandidates(
  result: ClassificationResult
): string {
  if (result.candidates.length === 0) {
    return (
      "_No candidate category cleared the minimum rule-based " +
      "confidence threshold. This does **not** mean the agent is " +
      "out of scope of the EU AI Act — the deployer must still " +
      "review Annex III in full._"
    );
  }
  return result.candidates
    .map((c: ClassificationMatch, i: number) => {
      const confPct = (c.rule_based_confidence * 100).toFixed(0);
      const kwList =
        c.matched_keywords.length === 0
          ? "_(none)_"
          : c.matched_keywords.map((k) => `\`${k}\``).join(", ");
      return [
        `#### Candidate ${i + 1}: ${c.citation} — ${c.title}`,
        "",
        `- **Category ID:** \`${c.category_id}\``,
        `- **rule_based_confidence:** ${c.rule_based_confidence.toFixed(2)} (${confPct}%)`,
        `- **Matched keywords:** ${kwList}`,
        "",
      ].join("\n");
    })
    .join("\n");
}

function renderAnnexIIIClassification(
  baseContext: TemplateContext,
  intendedPurpose: string,
  ds: DocSigner
): BundleFile {
  const classification = intendedPurpose
    ? classifyAgentDescription(intendedPurpose)
    : null;

  const context: TemplateContext = {
    ...baseContext,
    classified_intended_purpose:
      intendedPurpose ||
      "_(no intended purpose supplied in deployment_context; the classifier was not run)_",
    candidates_rendered: classification
      ? formatClassificationCandidates(classification)
      : "_(classifier not run — no intended purpose supplied)_",
    classifier_advisory: classification
      ? classification.advisory
      : "The classifier was not invoked because the deployment_context.intended_purpose field was empty. The enterprise must perform manual Annex III review.",
    document_title: "Annex III Classification Candidates",
    document_subtitle:
      "Rule-based candidate classifications for Annex III of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    ANNEX_III_CLASSIFICATION_TEMPLATE,
    context,
    "07_annex_iii_classification.md",
    ds
  );
}

function renderHumanOversight(
  baseContext: TemplateContext,
  ds: DocSigner
): BundleFile {
  // Art. 14 rows + Annex IV §2(e) human oversight assessment.
  const rows = [
    ...rowsWithCitationPrefix("art-14"),
    ...rowsById(["annex_iv_2_e_human_oversight_assessment"]),
  ];
  const context: TemplateContext = {
    ...baseContext,
    rows_rendered: renderRowBlocks(rows),
    document_title: "Human Oversight Statement",
    document_subtitle:
      "Human oversight measures under Article 14 of Regulation (EU) 2024/1689",
  };

  return finaliseDocument(
    HUMAN_OVERSIGHT_STATEMENT_TEMPLATE,
    context,
    "05_human_oversight_statement.md",
    ds
  );
}

/**
 * The cryptographic attestations document references the
 * already-generated files' hashes and signatures. It MUST be
 * rendered after all other documents.
 */
function renderAttestations(
  baseContext: TemplateContext,
  priorFiles: BundleFile[],
  manifestSha256: string,
  manifestSignature: string,
  ds: DocSigner
): BundleFile {
  const table = [
    "| Filename | SHA-256 | Signature (base64url) |",
    "|---|---|---|",
    ...priorFiles.map(
      (f) => `| \`${f.filename}\` | \`${f.sha256}\` | \`${f.signature ?? ""}\` |`
    ),
  ].join("\n");

  const context: TemplateContext = {
    ...baseContext,
    file_attestation_table: table,
    manifest_sha256: manifestSha256,
    manifest_signature: manifestSignature,
    document_title: "Cryptographic Attestations",
    document_subtitle:
      "Bundle integrity attestations signed by the provider's primary Ed25519 identity",
  };

  return finaliseDocument(
    CRYPTOGRAPHIC_ATTESTATIONS_TEMPLATE,
    context,
    "06_cryptographic_attestations.md",
    ds
  );
}

// ── Manifest builder ─────────────────────────────────────────────────

function buildManifest(
  input: ComplianceBundleInput,
  generatedAt: string,
  signer: StoredIdentity,
  files: BundleFile[],
  ds: DocSigner
): BundleManifest {
  const stats = coverageStats(COVERAGE_MATRIX_V1);

  const rowSummaries: ManifestRowSummary[] = COVERAGE_MATRIX_V1.rows.map(
    (r) => ({
      id: r.id,
      clause_id: r.citation.clause_id,
      coverage: r.coverage,
      evidence_emitter: [...r.evidence_emitter],
    })
  );

  // Build the manifest body without the signature (to be signed).
  const manifestBody: Omit<BundleManifest, "manifest_signature"> = {
    bundle_version: "1.0",
    matrix_version: "v1",
    regulation_version: REGULATION_VERSION,
    generated_at: generatedAt,
    agent_did: input.agent_did,
    period_start: input.period_start,
    period_end: input.period_end,
    deployment_context: input.deployment_context,
    signer: {
      did: signer.did,
      public_key_base64url: signer.public_key,
    },
    files: files.map((f) => ({
      filename: f.filename,
      content_type: f.content_type,
      sha256: f.sha256,
      signature: f.signature ?? "",
    })),
    coverage_summary: {
      total_rows: stats.total_rows,
      full: stats.full,
      partial: stats.partial,
      manual_only: stats.manual_only,
      full_pct: stats.full_pct,
      partial_pct: stats.partial_pct,
      manual_only_pct: stats.manual_only_pct,
    },
    coverage_rows: rowSummaries,
    disclaimer: NOT_LEGAL_ADVICE_DISCLAIMER,
  };

  // Sign the canonical JSON of the manifest body.
  const canonical = canonicalJSON(manifestBody);
  const manifestSignature = ds.signContent(canonical);

  return {
    ...manifestBody,
    manifest_signature: manifestSignature,
  };
}

// ── Delta computation ────────────────────────────────────────────────

/**
 * Attempt to load a prior bundle manifest from disk. Returns null
 * and pushes a warning into the output array if the path is
 * unreadable or the file is not a valid bundle manifest. Never
 * throws — delta problems must never fail bundle generation.
 */
async function loadPriorBundleManifest(
  bundlePath: string,
  warnings: string[]
): Promise<BundleManifest | null> {
  try {
    const manifestPath = join(bundlePath, "00_bundle_manifest.json");
    const bytes = await readFile(manifestPath, "utf-8");
    const parsed = JSON.parse(bytes) as BundleManifest;
    if (
      typeof parsed.bundle_version !== "string" ||
      typeof parsed.regulation_version !== "string" ||
      !Array.isArray(parsed.coverage_rows)
    ) {
      warnings.push(
        `Prior bundle at ${bundlePath} is missing required manifest fields; delta skipped.`
      );
      return null;
    }
    return parsed;
  } catch (e) {
    warnings.push(
      `Prior bundle at ${bundlePath} could not be read: ${(e as Error).message}. Delta skipped.`
    );
    return null;
  }
}

/**
 * Compute the structured delta between a prior and current
 * manifest. Per Erik's Phase 2 spec, this focuses on four change
 * categories: regulation_version bump, coverage flag changes,
 * evidence_emitter array changes, and last_reviewed_date advances.
 *
 * The current manifest does not carry last_reviewed_date in
 * ManifestRowSummary (it's only in the source matrix), so
 * last_reviewed_date comparison uses the live matrix as the
 * authoritative current state and compares to the prior manifest's
 * coverage_rows entries if they carry the field. If the prior
 * manifest does not expose last_reviewed_date per row, that field
 * is omitted from the delta (no false positives).
 */
function computeDelta(
  prior: BundleManifest,
  current: BundleManifest,
  priorBundlePath: string,
  warnings: string[]
): DeltaReport {
  const priorRows = new Map(prior.coverage_rows.map((r) => [r.id, r]));
  const currentRows = new Map(current.coverage_rows.map((r) => [r.id, r]));

  const rows_added: string[] = [];
  const rows_removed: string[] = [];
  const rows_changed: DeltaRowChange[] = [];

  for (const [id] of currentRows) {
    if (!priorRows.has(id)) {
      rows_added.push(id);
    }
  }
  for (const [id] of priorRows) {
    if (!currentRows.has(id)) {
      rows_removed.push(id);
    }
  }

  for (const [id, currentRow] of currentRows) {
    const priorRow = priorRows.get(id);
    if (!priorRow) continue;
    const changes: DeltaRowChange["changes"] = {};
    if (priorRow.coverage !== currentRow.coverage) {
      changes.coverage = {
        from: priorRow.coverage,
        to: currentRow.coverage,
      };
    }
    const priorEmitters = [...(priorRow.evidence_emitter || [])].sort();
    const currentEmitters = [...(currentRow.evidence_emitter || [])].sort();
    if (JSON.stringify(priorEmitters) !== JSON.stringify(currentEmitters)) {
      changes.evidence_emitter = {
        from: priorRow.evidence_emitter || [],
        to: currentRow.evidence_emitter || [],
      };
    }
    if (Object.keys(changes).length > 0) {
      rows_changed.push({
        row_id: id,
        clause_id: currentRow.clause_id,
        changes,
      });
    }
  }

  rows_added.sort();
  rows_removed.sort();
  rows_changed.sort((a, b) => a.row_id.localeCompare(b.row_id));

  return {
    prior_bundle_path: priorBundlePath,
    prior_generated_at: prior.generated_at,
    prior_signer_did: prior.signer.did,
    prior_regulation_version: prior.regulation_version,
    prior_matrix_version: prior.matrix_version,
    current_generated_at: current.generated_at,
    current_signer_did: current.signer.did,
    current_regulation_version: current.regulation_version,
    current_matrix_version: current.matrix_version,
    regulation_version_changed:
      prior.regulation_version !== current.regulation_version,
    matrix_version_changed:
      prior.matrix_version !== current.matrix_version,
    rows_added,
    rows_removed,
    rows_changed,
    warnings,
  };
}

/**
 * Format a DeltaReport's three row-change sections as Markdown
 * blocks for embedding in the delta template.
 */
function formatDeltaSections(report: DeltaReport): {
  rows_added_rendered: string;
  rows_removed_rendered: string;
  rows_changed_rendered: string;
  warnings_rendered: string;
  no_changes_note: string;
} {
  const added =
    report.rows_added.length === 0
      ? "_(none)_"
      : report.rows_added.map((id) => `- \`${id}\``).join("\n");

  const removed =
    report.rows_removed.length === 0
      ? "_(none)_"
      : report.rows_removed.map((id) => `- \`${id}\``).join("\n");

  const changed =
    report.rows_changed.length === 0
      ? "_(none)_"
      : report.rows_changed
          .map((rc) => {
            const lines = [
              `#### \`${rc.row_id}\` (${rc.clause_id})`,
              "",
            ];
            if (rc.changes.coverage) {
              lines.push(
                `- **coverage:** \`${rc.changes.coverage.from}\` → \`${rc.changes.coverage.to}\``
              );
            }
            if (rc.changes.evidence_emitter) {
              lines.push(
                `- **evidence_emitter from:** [${rc.changes.evidence_emitter.from.map((e) => `\`${e}\``).join(", ")}]`
              );
              lines.push(
                `- **evidence_emitter to:** [${rc.changes.evidence_emitter.to.map((e) => `\`${e}\``).join(", ")}]`
              );
            }
            if (rc.changes.last_reviewed_date) {
              lines.push(
                `- **last_reviewed_date:** ${rc.changes.last_reviewed_date.from} → ${rc.changes.last_reviewed_date.to}`
              );
            }
            lines.push("");
            return lines.join("\n");
          })
          .join("\n");

  const warningsList =
    report.warnings.length === 0
      ? "_(none)_"
      : report.warnings.map((w) => `- ${w}`).join("\n");

  const hasAnyChanges =
    report.regulation_version_changed ||
    report.matrix_version_changed ||
    report.rows_added.length > 0 ||
    report.rows_removed.length > 0 ||
    report.rows_changed.length > 0;

  const noChangesNote = hasAnyChanges
    ? ""
    : "**No changes detected between prior and current bundle.** Both bundles reference the same regulation_version, the same matrix_version, and the same row set with identical coverage flags and evidence_emitter arrays. The only differences are the generation timestamps and the audit period activity captured in documents 02-05.\n\n";

  return {
    rows_added_rendered: added,
    rows_removed_rendered: removed,
    rows_changed_rendered: changed,
    warnings_rendered: warningsList,
    no_changes_note: noChangesNote,
  };
}

function renderDelta(
  baseContext: TemplateContext,
  report: DeltaReport,
  ds: DocSigner
): BundleFile {
  const sections = formatDeltaSections(report);
  const context: TemplateContext = {
    ...baseContext,
    prior_bundle_path: report.prior_bundle_path,
    prior_generated_at: report.prior_generated_at,
    prior_signer_did: report.prior_signer_did,
    prior_regulation_version: report.prior_regulation_version,
    prior_matrix_version: report.prior_matrix_version,
    current_generated_at: report.current_generated_at,
    current_signer_did: report.current_signer_did,
    current_regulation_version: report.current_regulation_version,
    current_matrix_version: report.current_matrix_version,
    regulation_version_changed: report.regulation_version_changed
      ? "yes"
      : "no",
    matrix_version_changed: report.matrix_version_changed ? "yes" : "no",
    rows_added_count: report.rows_added.length,
    rows_removed_count: report.rows_removed.length,
    rows_changed_count: report.rows_changed.length,
    ...sections,
    document_title: "Compliance Bundle Delta Report",
    document_subtitle:
      "Changes between the prior bundle and this bundle",
  };
  return finaliseDocument(
    DELTA_TEMPLATE,
    context,
    "08_delta.md",
    ds
  );
}

// ── Verascore publish hook ───────────────────────────────────────────

/**
 * Allowed Verascore hostnames for the SSRF allow-list. Matches the
 * set used by `reputation_publish` in `src/reputation/tools.ts`.
 * Mirrored here rather than imported so the compliance generator
 * does not couple to the reputation module's internals.
 */
const ALLOWED_VERASCORE_HOSTS = new Set([
  "verascore.ai",
  "www.verascore.ai",
  "api.verascore.ai",
]);

/**
 * Publish a signed bundle manifest to Verascore as a pure side-
 * effect. Follows the same wire format and signing path used by
 * `reputation_publish`:
 *
 *   - Allow-list SSRF check (HTTPS + known Verascore host)
 *   - Canonical JSON of the manifest is signed with the provider's
 *     primary Ed25519 identity via the existing core/identity.js
 *     sign() primitive — no second signing pipeline
 *   - POST { agentId, signature, publicKey, type, data } to
 *     `${verascoreUrl}/api/publish` with type "eu-ai-act-bundle"
 *   - Only the manifest is published; document bodies never leave
 *     the local filesystem
 *
 * NON-DEPENDENCY PRINCIPLE: this function MUST NOT throw. Any
 * error (URL validation, fetch failure, non-2xx response) is
 * captured in the returned VerascorePublishResult and bundle
 * generation proceeds unaffected. Sanctuary never requires
 * Verascore to be online.
 */
async function publishBundleManifestToVerascore(
  manifest: BundleManifest,
  signer: StoredIdentity,
  encryptionKey: Uint8Array,
  verascoreUrl: string,
  ds: DocSigner
): Promise<VerascorePublishResult> {
  const result: VerascorePublishResult = {
    attempted: true,
    published: false,
    verascore_url: verascoreUrl,
  };

  // Validate URL shape + SSRF allow-list.
  let parsed: URL;
  try {
    parsed = new URL(verascoreUrl);
  } catch {
    result.error = `Verascore URL is not a valid URL: ${verascoreUrl}`;
    return result;
  }
  if (parsed.protocol !== "https:") {
    result.error = `Verascore URL must use HTTPS (got ${parsed.protocol})`;
    return result;
  }
  if (!ALLOWED_VERASCORE_HOSTS.has(parsed.hostname)) {
    result.error = `Verascore URL must point to a known Verascore host (${[...ALLOWED_VERASCORE_HOSTS].join(", ")}). Got: ${parsed.hostname}`;
    return result;
  }

  // Build canonical manifest bytes and sign them for the publish
  // request body. The manifest already carries its own
  // manifest_signature field (over canonical body with the signature
  // stripped); Verascore's API additionally requires a signature
  // over the outer request body, so we sign once more — same
  // identity, same key, same sign() primitive.
  const canonicalManifest = canonicalJSON(manifest);
  const manifestBytes = stringToBytes(canonicalManifest);
  const manifestSha256 = ds.sha256Hex(canonicalManifest);
  result.published_manifest_sha256 = manifestSha256;

  let requestSignatureB64: string;
  try {
    const sigBytes = sign(
      manifestBytes,
      signer.encrypted_private_key,
      encryptionKey
    );
    requestSignatureB64 = toBase64url(sigBytes);
  } catch (e) {
    result.error = `Failed to sign Verascore publish payload: ${(e as Error).message}`;
    return result;
  }

  // Derive a Verascore-slug agent ID from the manifest's agent DID
  // using the same normalisation reputation_publish uses.
  const agentId = manifest.agent_did
    .replace(/[^a-zA-Z0-9-]/g, "-")
    .toLowerCase();
  result.verascore_agent_id = agentId;

  const requestBody = {
    agentId,
    signature: requestSignatureB64,
    publicKey: signer.public_key,
    type: "eu-ai-act-bundle",
    data: manifest,
  };

  try {
    const response = await fetch(`${verascoreUrl}/api/publish`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
    });
    result.status = response.status;
    if (!response.ok) {
      result.error = `Verascore API returned ${response.status}`;
      return result;
    }
    result.published = true;
    return result;
  } catch (e) {
    result.error = `Verascore fetch failed: ${(e as Error).message}`;
    return result;
  }
}

// ── Top-level generator entry point ──────────────────────────────────

/**
 * Generate a complete EU AI Act compliance bundle for the given
 * agent and reporting period.
 */
export async function generateEuAiActBundle(
  input: ComplianceBundleInput,
  deps: GeneratorDeps
): Promise<ComplianceBundle> {
  // Resolve primary identity.
  const signer = deps.identityManager.getDefault();
  if (!signer) {
    throw new Error(
      "No primary identity configured. Run identity_create and " +
        "identity_set_primary before generating a compliance bundle."
    );
  }

  const ds = makeSigner(signer, deps.masterKey);

  // Compute audit period summary.
  const auditSummary = await computeAuditPeriodSummary(
    deps.auditLog,
    input.period_start,
    input.period_end
  );

  const generatedAt = input.generated_at_override ?? new Date().toISOString();

  // Build the shared template context.
  const baseContext = buildCommonContext(
    input,
    deps,
    signer,
    auditSummary,
    generatedAt
  );

  // Render documents 1-5 in order.
  const doc1 = renderAnnexIV(baseContext, ds);
  const doc2 = renderArticle26(baseContext, ds);
  const doc3 = renderArticle12(baseContext, ds);
  const doc4 = renderRiskManagement(baseContext, ds);
  const doc5 = renderHumanOversight(baseContext, ds);

  // Doc 07 (Annex III classification) is rendered separately from
  // doc 06 (attestations) because it is a content document; doc 06
  // is the integrity attestation document and attests to docs 1-5.
  // Doc 07 is attested via the manifest only (the manifest covers
  // all 7 files with SHA-256 + Ed25519 signatures).
  const doc7 = renderAnnexIIIClassification(
    baseContext,
    input.deployment_context.intended_purpose ?? "",
    ds
  );

  // Build a partial manifest with docs 1-5 (and a placeholder for
  // doc 6) so we can compute its canonical hash and signature for
  // inclusion in doc 6.
  //
  // Doc 6 references the manifest SHA-256 and signature, which
  // include every file's hash. Doc 6 cannot include its OWN hash
  // and signature inside the manifest it references, because that
  // would create a cyclic dependency. Resolution:
  //
  // 1. Build the manifest with docs 1-5 only.
  // 2. Render doc 6 with that partial manifest's hash/signature.
  // 3. Rebuild the manifest with all 6 docs (doc 6 is now included).
  // 4. The final bundle's manifest_signature covers all 6 files.
  //
  // The attestations document in step 2 references the manifest
  // hash from step 1, which is the hash-over-docs-1-5. The final
  // manifest in step 3 supersedes that with a hash-over-all-6.
  // Verifiers must check the final manifest; the intermediate hash
  // in doc 6's body is a narrative reference only.

  const partialManifest = buildManifest(
    input,
    generatedAt,
    signer,
    [doc1, doc2, doc3, doc4, doc5],
    ds
  );
  const partialCanonical = canonicalJSON(partialManifest);
  const partialSha256 = ds.sha256Hex(partialCanonical);
  const partialSignature = partialManifest.manifest_signature;

  const doc6 = renderAttestations(
    baseContext,
    [doc1, doc2, doc3, doc4, doc5],
    partialSha256,
    partialSignature,
    ds
  );

  let allFiles: BundleFile[] = [doc1, doc2, doc3, doc4, doc5, doc6, doc7];

  // Optional doc 08 — delta report (only when delta_from_bundle_path
  // is supplied AND the prior bundle loads cleanly). Delta problems
  // never fail bundle generation: the bundle always lands locally,
  // and delta is a best-effort enrichment layer.
  if (input.delta_from_bundle_path) {
    const deltaWarnings: string[] = [];
    const priorManifest = await loadPriorBundleManifest(
      input.delta_from_bundle_path,
      deltaWarnings
    );
    if (priorManifest !== null) {
      // Build a temporary "current" manifest snapshot for comparison.
      // We need the coverage_rows and version fields; other fields
      // are not compared by computeDelta.
      const currentManifestSnapshot = buildManifest(
        input,
        generatedAt,
        signer,
        allFiles,
        ds
      );
      const report = computeDelta(
        priorManifest,
        currentManifestSnapshot,
        input.delta_from_bundle_path,
        deltaWarnings
      );
      const doc8 = renderDelta(baseContext, report, ds);
      allFiles = [...allFiles, doc8];
    }
  }

  // Final manifest covers all files (7 core + optional doc 08 delta).
  const finalManifest = buildManifest(
    input,
    generatedAt,
    signer,
    allFiles,
    ds
  );

  // Optional Verascore publish side-effect. Runs LAST so the bundle
  // is already fully built and ready to return before we touch the
  // network. If publish fails for any reason, the bundle is returned
  // in the same shape with publish_result describing the failure.
  // Sanctuary bundle generation NEVER depends on Verascore being
  // online — this is the non-dependency principle in action.
  let publishResult: VerascorePublishResult | undefined = undefined;
  if (input.publish_to_verascore) {
    const encryptionKey = derivePurposeKey(
      deps.masterKey,
      "identity-encryption"
    );
    publishResult = await publishBundleManifestToVerascore(
      finalManifest,
      signer,
      encryptionKey,
      input.verascore_url ?? "https://verascore.ai",
      ds
    );
  }

  return {
    manifest: finalManifest,
    files: allFiles,
    publish_result: publishResult,
  };
}

// ── MCP tool factory ─────────────────────────────────────────────────

/**
 * Factory for the EU AI Act compliance MCP tools.
 *
 * - compliance_eu_ai_act_annex_iii_classify: Tier 3 (auto-allow, read-only).
 *   A rule-based classifier over free text; its output carries no policy
 *   thresholds, so it stays agent-callable.
 * - compliance_generate_eu_ai_act_bundle: Tier 1 (operator approval required).
 *   It does not modify state, but the generated bundle BODY embeds the verbatim
 *   Tier-2 anomaly policy (e.g. frequency_spike_multiplier), the approval-channel
 *   timeout, and audit-derived aggregate gate-decision counts. Auto-allowing it
 *   would hand the agent a policy-inference oracle (no-read invariant,
 *   CLAUDE.md #7), the same leak class as audit_export_siem through a different
 *   door. It is also a governance conflict of interest: an agent must not
 *   generate its own compliance attestation (cf. the self-attested-reputation
 *   vuln). The OPERATOR who approves the bundle may see this structure, so the
 *   document bodies are unchanged; only the gate moved (Tier 3 to Tier 1, CISO
 *   NEW-1).
 */
export function createComplianceTools(deps: GeneratorDeps): {
  tools: ToolDefinition[];
} {
  const tools: ToolDefinition[] = [
    {
      name: "compliance_eu_ai_act_annex_iii_classify",
      description:
        "Classify a free-text agent description against the eight " +
        "Annex III high-risk categories of Regulation (EU) 2024/1689. " +
        "Returns zero or more candidate categories with a " +
        "rule_based_confidence score (sum of matched keyword weights " +
        "clamped to [0, 1]). This is a RULE-BASED classifier — NOT " +
        "a machine-learning model, and NOT legal advice. Use the " +
        "result to narrow the deployer's review. Tier 3 (read-only, " +
        "auto-allow).",
      inputSchema: {
        type: "object",
        properties: {
          description: {
            type: "string",
            description:
              "Free-text description of what the agent does — its " +
              "intended purpose, the users it serves, the decisions " +
              "it makes, the data it processes.",
          },
        },
        required: ["description"],
      },
      handler: async (args) => {
        const description = String(args.description ?? "");
        if (description.trim().length === 0) {
          return toolResult({
            error:
              "description must be a non-empty string describing the agent's intended purpose",
          });
        }
        const result = classifyAgentDescription(description);
        return toolResult(result);
      },
    },
    {
      name: "compliance_generate_eu_ai_act_bundle",
      description:
        "Generate an EU AI Act compliance bundle for a given agent " +
        "and reporting period. Produces 6 Markdown documents plus a " +
        "signed JSON manifest, covering Annex IV technical " +
        "documentation (Art. 11), Art. 12 automatic record-keeping, " +
        "Art. 13 transparency, Art. 14 human oversight, Art. 15 " +
        "cybersecurity, and Art. 26 deployer obligations. Every " +
        "file is individually SHA-256 hashed and signed with the " +
        "provider's primary Ed25519 identity. NOT LEGAL ADVICE — " +
        "consult qualified counsel before filing. " +
        "Tier 1 (operator approval required): the bundle body embeds your " +
        "anomaly-detection thresholds, approval timeout, and audit-derived " +
        "decision counts, so it is not auto-allowed (prevents policy-inference), " +
        "and an agent must not generate its own compliance attestation.",
      inputSchema: {
        type: "object",
        properties: {
          agent_did: {
            type: "string",
            description:
              "DID of the agent the bundle is being generated for.",
          },
          deployment_context: {
            type: "object",
            description:
              "Enterprise-supplied deployment facts that Sanctuary " +
              "cannot infer (vertical, intended purpose, provider " +
              "legal name, Annex III classification, etc.).",
            properties: {
              vertical: { type: "string" },
              annex_iii_class: { type: "string" },
              intended_purpose: { type: "string" },
              provider_legal_name: { type: "string" },
              provider_contact: { type: "string" },
              deployer_is_public_authority: { type: "boolean" },
              notes: { type: "string" },
            },
          },
          period_start: {
            type: "string",
            description:
              "ISO 8601 timestamp — start of the reporting period.",
          },
          period_end: {
            type: "string",
            description:
              "ISO 8601 timestamp — end of the reporting period.",
          },
          delta_from_bundle_path: {
            type: "string",
            description:
              "Optional filesystem path to a prior bundle directory. " +
              "When supplied, the generator compares the current " +
              "bundle to the prior one and emits an additional " +
              "08_delta.md document summarising what changed " +
              "(regulation_version, matrix_version, coverage rows " +
              "added/removed/changed). Delta problems never fail " +
              "bundle generation; the bundle always lands locally.",
          },
          publish_to_verascore: {
            type: "boolean",
            description:
              "If true, POST the signed bundle MANIFEST (not the " +
              "document bodies) to Verascore after the bundle is " +
              "generated. Non-dependency principle: publish " +
              "failure never fails bundle generation — the bundle " +
              "is returned with a publish_result field describing " +
              "the outcome. Defaults to false.",
          },
          verascore_url: {
            type: "string",
            description:
              "Optional Verascore base URL (HTTPS, allow-listed " +
              "hosts only). Defaults to https://verascore.ai.",
          },
        },
        required: [
          "agent_did",
          "deployment_context",
          "period_start",
          "period_end",
        ],
      },
      handler: async (args) => {
        const input: ComplianceBundleInput = {
          agent_did: String(args.agent_did),
          deployment_context:
            (args.deployment_context as ComplianceBundleInput["deployment_context"]) ??
            {},
          period_start: String(args.period_start),
          period_end: String(args.period_end),
          delta_from_bundle_path:
            typeof args.delta_from_bundle_path === "string"
              ? args.delta_from_bundle_path
              : undefined,
          publish_to_verascore: args.publish_to_verascore === true,
          verascore_url:
            typeof args.verascore_url === "string"
              ? args.verascore_url
              : undefined,
        };

        const bundle = await generateEuAiActBundle(input, deps);

        return toolResult({
          bundle_version: bundle.manifest.bundle_version,
          matrix_version: bundle.manifest.matrix_version,
          regulation_version: bundle.manifest.regulation_version,
          agent_did: bundle.manifest.agent_did,
          generated_at: bundle.manifest.generated_at,
          period: {
            start: bundle.manifest.period_start,
            end: bundle.manifest.period_end,
          },
          signer: bundle.manifest.signer,
          coverage_summary: bundle.manifest.coverage_summary,
          file_count: bundle.files.length,
          files: bundle.files.map((f) => ({
            filename: f.filename,
            content_type: f.content_type,
            sha256: f.sha256,
            signature: f.signature,
            content_length: f.content.length,
          })),
          manifest_signature: bundle.manifest.manifest_signature,
          disclaimer: bundle.manifest.disclaimer,
          publish_result: bundle.publish_result,
          _bundle_content: {
            manifest: bundle.manifest,
            files: bundle.files.map((f) => ({
              filename: f.filename,
              content: f.content,
            })),
          },
        });
      },
    },
  ];

  return { tools };
}
