/**
 * Sanctuary MCP Server — EU AI Act Template: Cryptographic Attestations
 *
 * Copyright 2026 Erik Newton
 * SPDX-License-Identifier: Apache-2.0
 *
 * Document 06 of the EU AI Act Compliance Bundle.
 *
 * Summarises the cryptographic attestations covering every file in
 * the bundle. This document is a human-readable companion to the
 * JSON manifest at `00_bundle_manifest.json` — it enables an auditor
 * to verify bundle integrity without parsing the machine-readable
 * manifest.
 */

import { HEADER_TEMPLATE, FOOTER_TEMPLATE } from "./shared.js";

export const CRYPTOGRAPHIC_ATTESTATIONS_TEMPLATE = `${HEADER_TEMPLATE}
## Introduction

This document is the Cryptographic Attestations summary for the
compliance bundle identified above. Every file in the bundle —
including this document — is individually hashed with SHA-256 and
signed with the provider's primary Ed25519 identity. The entire
bundle manifest is additionally signed as a single canonical
document so an auditor can verify "this exact set of files, in
this exact state, was attested by this identity at this exact
timestamp" with a single signature check.

**Why this matters under Article 11 and Article 47:** the Annex IV
technical documentation and the EU declaration of conformity are
typically signed by the provider's legal representative. This
document does not substitute for the legal signature — it provides
the **runtime authenticity attestation** that proves the technical
contents of the bundle were generated by the named Sanctuary
instance and have not been altered since generation. The legal
signature and the cryptographic attestation are complementary
controls.

---

## Signer Identity

| Field | Value |
|---|---|
| Signer DID | \`{{ signer_did }}\` |
| Signer public key (base64url) | \`{{ signer_pubkey }}\` |
| Signer key type | Ed25519 |
| Signer role | Provider primary identity |
| Key custody | Self-custodied (L1 Cognitive Sovereignty) |

The signer identity is the provider's primary Ed25519 identity as
reported by \`identity_set_primary\` on the generating Sanctuary
instance. To verify any signature in this bundle, retrieve the
public key above and check the base64url signature against the
SHA-256 digest of the corresponding file using standard Ed25519
verification.

---

## Bundle File Attestations

Each file in the bundle is listed below with its SHA-256 digest and
Ed25519 signature. Recompute the SHA-256 of any file and verify
the signature to confirm integrity.

{{ file_attestation_table }}

---

## Manifest Signature

The complete bundle manifest (\`00_bundle_manifest.json\`) is
canonically serialised (sorted keys, no whitespace) and signed as
a single document. Verifying the manifest signature establishes
authenticity of the entire bundle in one check.

| Field | Value |
|---|---|
| Manifest SHA-256 | \`{{ manifest_sha256 }}\` |
| Manifest signature (base64url) | \`{{ manifest_signature }}\` |
| Canonicalisation | Sorted keys, no whitespace (JSON canonical form) |

---

## Verification Procedure

To verify this bundle end-to-end:

1. **Verify each file individually.** For each file in the bundle:
   (a) read the file bytes, (b) compute SHA-256, (c) compare against
   the digest in the table above, (d) verify the Ed25519 signature
   against the SHA-256 digest using the signer's public key.
2. **Verify the manifest.** Canonically serialise
   \`00_bundle_manifest.json\` (sorted keys, no whitespace), compute
   SHA-256, and verify the \`manifest_signature\` field against the
   signer's public key.
3. **Cross-check the manifest against the files.** Ensure every
   file listed in the manifest exists in the bundle and every
   file in the bundle is listed in the manifest, with matching
   SHA-256 digests.
4. **Verify the signer identity.** Confirm the signer DID and
   public key match the expected provider identity (for example,
   via a trusted identity registry or via direct confirmation
   with the provider).

If all four checks pass, the bundle is cryptographically authentic
as-generated by the named Sanctuary instance. The cryptographic
check does not establish the **legal validity** of the contents —
that remains the responsibility of the provider's legal signature
and the applicable conformity assessment procedure under
Regulation (EU) 2024/1689.

${FOOTER_TEMPLATE}`;
