/**
 * Sanctuary MCP Server — EU AI Act Compliance Shared Template Fragments
 *
 * Copyright 2026 Erik Newton
 * SPDX-License-Identifier: Apache-2.0
 *
 * Header and footer fragments shared across all generated documents
 * in an EU AI Act compliance bundle. Every document includes both.
 */

/**
 * Shared document header. Rendered at the top of every bundle
 * document. The document-specific title is passed in as
 * `{{ document_title }}` and the document-specific subtitle as
 * `{{ document_subtitle }}`.
 */
export const HEADER_TEMPLATE = `# {{ document_title }}

*{{ document_subtitle }}*

---

| Field | Value |
|---|---|
| **Regulation** | {{ regulation_version }} |
| **Coverage matrix version** | {{ matrix_version }} |
| **Bundle generated** | {{ generated_at }} |
| **Reporting period** | {{ period_start }} → {{ period_end }} |
| **Agent DID** | \`{{ agent_did }}\` |
| **Legal provider** | {{ provider_legal_name }} |
| **Provider contact** | {{ provider_contact }} |
| **Intended purpose** | {{ intended_purpose }} |
| **Annex III classification** | {{ annex_iii_class }} |
| **Signer DID** | \`{{ signer_did }}\` |
| **Signer public key (base64url)** | \`{{ signer_pubkey }}\` |

---

`;

/**
 * Shared document footer. Rendered at the bottom of every bundle
 * document. Carries the mandatory "not legal advice" disclaimer and
 * the document-level signature block.
 */
export const FOOTER_TEMPLATE = `
---

## Document Signature

This document is cryptographically signed by the provider's primary
Ed25519 identity (DID \`{{ signer_did }}\`, public key
\`{{ signer_pubkey }}\`). The signature for this document is recorded
in the bundle manifest \`00_bundle_manifest.json\` under the entry
with this filename, alongside its SHA-256 digest.

**Verification procedure:** compute the SHA-256 of this file's raw
byte content, compare it against the \`sha256\` field for this file
in the bundle manifest, then verify the \`signature\` field against
the SHA-256 using the signer's public key with Ed25519. A successful
check proves this document was emitted by the named Sanctuary
instance and has not been altered since generation.

---

## Disclaimer

**This document is not legal advice.** It is a technical artifact
generated by the Sanctuary Framework EU AI Act Compliance Artifact
Generator. It is not a legal interpretation of Regulation (EU)
2024/1689 and does not constitute a legal opinion. Consult qualified
legal counsel before filing or relying on this document for
regulatory submissions, self-assessment, or CE marking procedures.

The coverage claims in this document reflect the state of the
Sanctuary Framework v{{ sanctuary_version }} runtime as of the
generation timestamp above. The coverage matrix is versioned
(\`{{ matrix_version }}\`) and aligned to the regulation text
identified by \`{{ regulation_version }}\`; if the European Commission
publishes implementing acts, delegated acts, or guidance that
modifies the applicable requirements, this document must be
regenerated against the updated matrix.

---

*Generated by [Sanctuary Framework](https://github.com/eriknewton/sanctuary-framework)
v{{ sanctuary_version }} · Author: Erik Newton · License: Apache-2.0*
`;

/**
 * Row block template used by every document for per-row rendering.
 * The generator iterates over the coverage matrix rows that belong
 * to the document, renders this template for each, and concatenates
 * the results into the {{ rows_rendered }} slot of the outer
 * document template.
 */
export const ROW_BLOCK_TEMPLATE = `### {{ row_citation }} — {{ row_title }}

**Coverage:** {{ row_coverage_badge }}

**Regulation text (verbatim, {{ regulation_version }}):**

> {{ row_requirement }}

**Evidence emitted by Sanctuary:**

{{ row_evidence_emitted }}

**Evidence emitter tools:**

{{ row_evidence_emitter_list }}

**Enterprise input required:**

{{ row_manual_carveout }}

---

`;

/**
 * Format a coverage flag as a human-readable badge for document
 * rendering. Uses structured text rather than emoji so the output
 * is greppable and audit-friendly.
 */
export function coverageBadge(
  coverage: "full" | "partial" | "manual_only"
): string {
  switch (coverage) {
    case "full":
      return "**FULL** — auto-emitted from Sanctuary, zero enterprise input required, machine-verifiable";
    case "partial":
      return "**PARTIAL** — Sanctuary emits structured evidence, enterprise supplies business context";
    case "manual_only":
      return "**MANUAL ONLY** — Sanctuary has no visibility, enterprise authors this section";
  }
}

/**
 * Format an array of evidence emitter tool names as a Markdown
 * bulleted list. Empty arrays render as "_(none — this row is
 * manual_only)_".
 */
export function formatEmitterList(emitters: string[]): string {
  if (emitters.length === 0) {
    return "_(none — this row is manual_only)_";
  }
  return emitters.map((e) => `- \`${e}\``).join("\n");
}
