//
// ArmLeaseParityVectorTests.swift
//
// Cross-language canonical-parity pin for the O-02 arm-lease signed body.
// The fixture is generated by `server/scripts/gen-arm-lease-parity-fixture.ts`
// from the TS producer (`armLeaseSignedBody` + `canonicalize`) and the same
// bytes are asserted by `server/test/castle-wall/runtime/
// arm-lease-parity-vector.test.ts`; this suite proves the Swift verifier
// recomputes byte-identical canonical bytes and accepts the TS-minted
// signature. A canonicalization divergence between the two sides fails HERE
// (and fails CLOSED on-device: every lease rejected), mirroring the manifest
// parity-vector contract.
//

import XCTest
@testable import CastleWallFilter
@testable import CastleWallIPC

final class ArmLeaseParityVectorTests: XCTestCase {

    private struct Fixture: Decodable {
        let armLease: ArmLeaseBody
        let expectedCanonicalJsonB64: String
        let expectedCanonicalJsonHex: String
        let testPublicKeyB64url: String
        let testSignatureB64url: String

        enum CodingKeys: String, CodingKey {
            case armLease = "arm_lease"
            case expectedCanonicalJsonB64 = "expected_canonical_json_b64"
            case expectedCanonicalJsonHex = "expected_canonical_json_hex"
            case testPublicKeyB64url = "test_public_key_b64url"
            case testSignatureB64url = "test_signature_b64url"
        }
    }

    private func loadFixture() throws -> Fixture {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures")
            .appendingPathComponent("arm-lease-parity-vector.json")
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    func testCanonicalBytesMatchTsProducer() throws {
        let fixture = try loadFixture()
        let expected = try XCTUnwrap(Data(base64Encoded: fixture.expectedCanonicalJsonB64))
        let actual = try SignedArmLeaseVerifier.canonicalSignedBody(fixture.armLease)
        XCTAssertEqual(actual, expected)
        XCTAssertEqual(
            actual.map { String(format: "%02x", $0) }.joined(),
            fixture.expectedCanonicalJsonHex
        )
    }

    func testTsMintedSignatureVerifies() throws {
        let fixture = try loadFixture()
        let pinned = try Base64URL.decode(fixture.testPublicKeyB64url)
        XCTAssertEqual(fixture.armLease.leaseSignatureB64url, fixture.testSignatureB64url)
        // Verifier "local clock" pinned just after the fixture's stamp so the
        // freshness window passes deterministically.
        let accepted = try SignedArmLeaseVerifier.verify(
            fixture.armLease,
            pinnedPublicKey: pinned,
            lastAcceptedUpdatedAt: nil,
            now: Date(timeIntervalSince1970: 1_786_838_400 + 1) // 2026-08-16T00:00:01Z
        )
        XCTAssertEqual(isoLeaseStamp(accepted), fixture.armLease.updatedAt)
    }
}
