/**
 * Sanctuary MCP Server, NIST AI RMF Crosswalk Generator
 *
 * Copyright 2026 Erik Newton
 * SPDX-License-Identifier: Apache-2.0
 *
 * Renders the NIST AI RMF crosswalk to a single Markdown document: a
 * preamble (tooling-coverage-map disclaimer), a coverage summary, and
 * one table per AI RMF function (GOVERN, MAP, MEASURE, MANAGE).
 *
 * Pure and dependency-free: it takes the crosswalk data and returns a
 * string. No Sanctuary server boot, no filesystem, no network, so it
 * is cheap to unit-test and never touches the operator's keychain.
 */

import type { NistCrosswalk, NistFunction } from "./types.js";
import { coverageStats, subcategoriesByFunction } from "./crosswalk.js";

const FUNCTION_ORDER: NistFunction[] = [
  "GOVERN",
  "MAP",
  "MEASURE",
  "MANAGE",
];

const COVERAGE_LABEL: Record<string, string> = {
  covered: "covered",
  partial: "partial",
  "not-applicable": "not-applicable (organizational)",
  gap: "gap",
};

/** Escape a cell value for GitHub-flavoured Markdown table safety. */
function cell(value: string): string {
  // Escape backslashes first so a literal backslash in the input cannot
  // combine with the pipe escape below (incomplete-sanitization safety).
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\|/g, "\\|")
    .replace(/\r?\n/g, " ");
}

function renderPreamble(crosswalk: NistCrosswalk): string {
  const lines: string[] = [];
  lines.push("# NIST AI RMF 1.0, Sanctuary Tooling-Coverage Crosswalk");
  lines.push("");
  lines.push(`**Framework:** ${crosswalk.framework_version}`);
  lines.push(`**Crosswalk version:** ${crosswalk.crosswalk_version}`);
  lines.push(`**Last review:** ${crosswalk.framework.last_full_review}`);
  lines.push("");
  lines.push("> **This is a tooling-coverage map, not a certification.**");
  lines.push(">");
  for (const note of crosswalk.notes) {
    lines.push(`> - ${note}`);
  }
  lines.push("");
  return lines.join("\n");
}

function renderSummary(crosswalk: NistCrosswalk): string {
  const s = coverageStats(crosswalk);
  const lines: string[] = [];
  lines.push("## Coverage summary");
  lines.push("");
  lines.push("| Status | Count | Share |");
  lines.push("| --- | ---: | ---: |");
  lines.push(`| covered | ${s.covered} | ${s.covered_pct}% |`);
  lines.push(`| partial | ${s.partial} | ${s.partial_pct}% |`);
  lines.push(
    `| not-applicable (organizational) | ${s.not_applicable} | ${s.not_applicable_pct}% |`
  );
  lines.push(`| gap | ${s.gap} | ${s.gap_pct}% |`);
  lines.push(`| **total mapped** | **${s.total}** | **100%** |`);
  lines.push("");
  lines.push(
    "`covered` counts only subcategories a real shipped Sanctuary " +
      "mechanism enforces or evidences. `not-applicable (organizational)` " +
      "marks org/process subcategories outside a runtime tool's scope. " +
      "`gap` marks technical subcategories Sanctuary does not address " +
      "today."
  );
  lines.push("");
  return lines.join("\n");
}

function renderFunctionTable(
  crosswalk: NistCrosswalk,
  fn: NistFunction
): string {
  const rows = subcategoriesByFunction(crosswalk, fn);
  if (rows.length === 0) return "";
  const lines: string[] = [];
  lines.push(`## ${fn}`);
  lines.push("");
  lines.push(
    "| Subcategory | Intent (paraphrase) | Coverage | Sanctuary control(s) | Evidence / note |"
  );
  lines.push("| --- | --- | --- | --- | --- |");
  for (const r of rows) {
    const controls =
      r.evidence_emitter.length > 0
        ? r.evidence_emitter.map((t) => "`" + t + "`").join(", ")
        : "(none)";
    lines.push(
      `| ${cell(r.id)} | ${cell(r.summary)} | ${cell(
        COVERAGE_LABEL[r.coverage] ?? r.coverage
      )} | ${cell(controls)} | ${cell(r.evidence_note)} |`
    );
  }
  lines.push("");
  return lines.join("\n");
}

/**
 * Render the entire crosswalk to a single Markdown document string.
 */
export function renderNistCrosswalk(crosswalk: NistCrosswalk): string {
  const parts: string[] = [];
  parts.push(renderPreamble(crosswalk));
  parts.push(renderSummary(crosswalk));
  for (const fn of FUNCTION_ORDER) {
    const table = renderFunctionTable(crosswalk, fn);
    if (table) parts.push(table);
  }
  parts.push(
    "---\n\n_Generated by the Sanctuary NIST AI RMF crosswalk. " +
      "NOT LEGAL ADVICE and NOT a NIST conformity assessment._\n"
  );
  return parts.join("\n");
}
