/**
 * The ONE definition of which files in a delivered pack directory the pack's
 * signed claims range over.
 *
 * D11-1 (Codex lens, dry-bar round 11): the writer's exemption and the signed
 * section-1 verification recipe are two surfaces describing the same set, and
 * they must not be able to disagree. The writer used to exempt every dotfile
 * while the signed report told the auditor that every Markdown and export file
 * in the pack is recorded in the manifest -- so a hidden `.counsel-notes.md`
 * shipped unmanifested beside a signed claim that it could not exist. That was a
 * deliberate usability tradeoff (refusing on `.DS_Store` would make the tool
 * unusable on a machine whose file browser has opened the delivery folder), but
 * a conscious tradeoff that breaks an honesty claim is still a defect.
 *
 * Both the enforcement (`writePackDirectory`) and the prose (`renderVerification`)
 * now read from this module. Widening the exemption widens what the signed
 * report tells the auditor to ignore, in the same edit, by construction.
 */

/**
 * Inert operating-system / file-browser metadata the pack's claims deliberately
 * do NOT range over. Every entry is generated by the operating system, carries
 * no evidentiary content, and is regenerated the moment the folder is opened.
 *
 * Keep this narrow. Anything NOT listed here -- any `.md`, `.json`, `.jsonl`, or
 * any other unrecognized dotfile -- is pack-relevant and is refused before
 * writing or caught by the post-write reconciliation, exactly like a visible
 * file.
 */
export const IGNORED_OS_METADATA: readonly string[] = [
  ".DS_Store",
  ".localized",
  "Thumbs.db",
  "desktop.ini",
];

/** AppleDouble resource forks (`._01_evidence_pack.md` and friends). */
const APPLEDOUBLE_PREFIX = "._";

/**
 * Human-readable rendering of the ignored set for the SIGNED section-1 recipe,
 * so the auditor is told the EXACT set the generator ignores rather than an
 * open-ended "hidden files". Derived from {@link IGNORED_OS_METADATA} so the
 * prose cannot drift from the enforcement.
 */
export const IGNORED_OS_METADATA_LABEL: string =
  IGNORED_OS_METADATA.map((n) => `\`${n}\``).join(", ") +
  ", and AppleDouble `._*` resource forks";

/**
 * True for a directory entry the pack's claims range over. Only the closed
 * {@link IGNORED_OS_METADATA} set (plus AppleDouble forks) is exempt; every
 * other name, hidden or not, is pack-relevant.
 */
export function isPackRelevantEntry(name: string): boolean {
  if (IGNORED_OS_METADATA.includes(name)) return false;
  if (name.startsWith(APPLEDOUBLE_PREFIX)) return false;
  return true;
}
