/**
 * The ONE definition of which files in a delivered pack directory the pack's
 * signed claims range over.
 *
 * D11-1 (Codex lens, dry-bar round 11): the writer's exemption and the signed
 * section-1 verification recipe are two surfaces describing the same set, and
 * they must not be able to disagree. The writer used to exempt every dotfile
 * while the signed report told the auditor that every Markdown and export file
 * in the pack is recorded in the manifest -- so a hidden `.counsel-notes.md`
 * shipped unmanifested beside a signed claim that it could not exist. That was a
 * deliberate usability tradeoff (refusing on `.DS_Store` would make the tool
 * unusable on a machine whose file browser has opened the delivery folder), but
 * a conscious tradeoff that breaks an honesty claim is still a defect.
 *
 * F-3 (dry-bar sweep 2026-07-27): the round-11 fix closed the open-ended
 * dotfile exemption to a named set but left the AppleDouble `._*` prefix
 * open-ended, so a planted `._counsel-notes.md` still shipped unmanifested
 * while the signed recipe told the auditor it "carries no evidentiary
 * content". The exemption is now VERIFIED, not name-pattern-trusted: a `._*`
 * entry is exempt only when (a) its data-fork name pairs with one of the
 * pack's own filenames AND (b) the file actually begins with the AppleDouble
 * magic bytes. Any other `._*` file is pack-relevant and refused or reconciled
 * exactly like a visible file.
 *
 * Both the enforcement (`writePackDirectory`) and the prose (`renderVerification`)
 * read from this module. Widening the exemption widens what the signed
 * report tells the auditor to ignore, in the same edit, by construction.
 */

import { open, readdir } from "node:fs/promises";
import { join } from "node:path";

/**
 * Inert operating-system / file-browser metadata the pack's claims deliberately
 * do NOT range over. Every entry is generated by the operating system, carries
 * no evidentiary content, and is regenerated the moment the folder is opened.
 *
 * Keep this narrow. Anything NOT listed here -- any `.md`, `.json`, `.jsonl`, or
 * any other unrecognized dotfile -- is pack-relevant and is refused before
 * writing or caught by the post-write reconciliation, exactly like a visible
 * file.
 */
export const IGNORED_OS_METADATA: readonly string[] = [
  ".DS_Store",
  ".localized",
  "Thumbs.db",
  "desktop.ini",
];

/** AppleDouble resource-fork name prefix (`._01_evidence_pack.md` and friends). */
const APPLEDOUBLE_PREFIX = "._";

/**
 * The AppleDouble on-disk magic number (0x00051607, big-endian), the first four
 * bytes of every genuine `._*` resource-fork companion file. A UTF-8 Markdown or
 * JSON file smuggled under a `._` name does not begin with these bytes, which is
 * what lets the writer tell a real fork from planted evidence-like content.
 */
export const APPLEDOUBLE_MAGIC: readonly number[] = [0x00, 0x05, 0x16, 0x07];

/**
 * Human-readable rendering of the ignored set for the SIGNED section-1 recipe,
 * so the auditor is told the EXACT set the generator ignores rather than an
 * open-ended "hidden files". Derived from {@link IGNORED_OS_METADATA} so the
 * prose cannot drift from the enforcement.
 */
export const IGNORED_OS_METADATA_LABEL: string =
  IGNORED_OS_METADATA.map((n) => `\`${n}\``).join(", ") +
  ", and verified AppleDouble `._*` resource forks of the pack's own filenames";

/**
 * The data-fork name a `._*` entry claims to be the resource fork of
 * (`._01_evidence_pack.md` -> `01_evidence_pack.md`), or null when the name is
 * not AppleDouble-shaped at all.
 */
export function appleDoubleDataName(name: string): string | null {
  if (!name.startsWith(APPLEDOUBLE_PREFIX)) return null;
  const dataName = name.slice(APPLEDOUBLE_PREFIX.length);
  return dataName.length > 0 ? dataName : null;
}

/**
 * NAME-LEVEL classification: true for a directory entry the pack's claims range
 * over. Only the closed {@link IGNORED_OS_METADATA} set and AppleDouble fork
 * names PAIRED WITH one of `packFilenames` are exempt at the name level; every
 * other name, hidden or not, is pack-relevant. F-3: an exempt-named fork
 * candidate must ADDITIONALLY carry the AppleDouble magic bytes to stay exempt;
 * {@link listPackRelevantEntries} performs that content check, so callers with
 * a real directory must use it rather than this name-only predicate.
 */
export function isPackRelevantEntry(
  name: string,
  packFilenames: readonly string[]
): boolean {
  if (IGNORED_OS_METADATA.includes(name)) return false;
  const dataName = appleDoubleDataName(name);
  if (dataName !== null && packFilenames.includes(dataName)) return false;
  return true;
}

/**
 * CONTENT verification for an AppleDouble fork candidate: true only when the
 * file's first four bytes are the AppleDouble magic. Fails toward "not a fork"
 * (pack-relevant, so refused) on any read error or short file: a file that
 * cannot be verified as inert metadata must never be silently exempted from
 * the signed claims (the could-not-look state is not the verified state).
 */
async function hasAppleDoubleMagic(filePath: string): Promise<boolean> {
  let handle;
  try {
    handle = await open(filePath, "r");
    const buf = new Uint8Array(APPLEDOUBLE_MAGIC.length);
    const { bytesRead } = await handle.read(buf, 0, buf.length, 0);
    if (bytesRead < APPLEDOUBLE_MAGIC.length) return false;
    return APPLEDOUBLE_MAGIC.every((b, i) => buf[i] === b);
  } catch {
    return false;
  } finally {
    await handle?.close().catch(() => undefined);
  }
}

/**
 * List the entries of `dirPath` the pack's signed claims range over: the
 * directory listing minus the closed {@link IGNORED_OS_METADATA} set and minus
 * VERIFIED AppleDouble forks of the pack's own filenames (name pairing AND
 * magic-byte check). A `._*` entry that fails either check is INCLUDED, so the
 * writer's foreign-file refusal and post-write reconciliation treat it exactly
 * like any other pack-relevant file.
 */
export async function listPackRelevantEntries(
  dirPath: string,
  packFilenames: readonly string[]
): Promise<string[]> {
  const names = await readdir(dirPath);
  const relevant: string[] = [];
  for (const name of names) {
    if (isPackRelevantEntry(name, packFilenames)) {
      relevant.push(name);
      continue;
    }
    // Name-level exempt. Metadata-set names are exempt outright; fork-named
    // candidates must ALSO carry the AppleDouble magic to stay exempt.
    const dataName = appleDoubleDataName(name);
    if (dataName === null) continue;
    if (await hasAppleDoubleMagic(join(dirPath, name))) continue;
    relevant.push(name);
  }
  return relevant;
}
