/**
 * Sanctuary MCP Server - Law-firm Evidence Pack: section renderers
 *
 * Copyright 2026 Erik Newton
 * SPDX-License-Identifier: Apache-2.0
 *
 * Renders the human-readable Markdown sections of the quarterly evidence pack,
 * mapped one-for-one to the five questions a malpractice carrier now asks on
 * the CNA AI supplement. Written for the reader it will actually have: an
 * office manager, an underwriter, or a client's outside-counsel-guidelines
 * auditor. Every section leads with a plain-English sentence.
 *
 * Slice 1 (walking skeleton) renders the sections that the shipped audit +
 * inventory surfaces can honestly fill; sections that require a later slice
 * (policy/attestation templates, fleet roster, incident-response runbook)
 * render a clearly-labeled "not yet included in this preview" placeholder
 * rather than fabricating content. A lawyer will read this, so it never
 * overclaims.
 *
 * NOT LEGAL ADVICE. The CNA mapping is a reading of the carrier supplement,
 * not a carrier-endorsed format.
 */

import type {
  CustodyFacts,
  EvidencePackInput,
  InventorySnapshot,
  QuarterAggregation,
  ShortfallReport,
} from "./types.js";
import type { QuarterWindow } from "./types.js";

/** One rendered section: a title (PDF page heading) plus its Markdown body. */
export interface PackSection {
  title: string;
  markdown: string;
}

const PLACEHOLDER_BADGE =
  "_[NOT YET INCLUDED IN THIS PREVIEW - a later build slice fills this " +
  "section; it is intentionally blank rather than fabricated.]_";

/** Static disclaimer carried on the cover and in the manifest. */
export const PACK_DISCLAIMER =
  "This evidence pack is a technical artifact generated by the Sanctuary " +
  "Framework. It is NOT legal advice and does not constitute a legal " +
  "interpretation of any professional-responsibility rule, insurance " +
  "questionnaire, or outside-counsel guideline. The mapping to carrier " +
  "questions is Sanctuary's reading of the supplement, not a carrier " +
  "endorsement. Have the policy and attestation content reviewed by a " +
  "licensed attorney before first use.";

function fmtCustodyMode(custody: CustodyFacts | undefined): string {
  switch (custody?.custody_mode) {
    case "passphrase":
      return "passphrase held by the firm";
    case "keychain":
      return "operating-system keychain on the firm's machine";
    default:
      return "not reported by this install";
  }
}

// ── Section 1: cover ─────────────────────────────────────────────────

function renderCover(
  input: EvidencePackInput,
  window: QuarterWindow,
  generatedAt: string,
  signerDid: string,
  productName: string,
  shortfall: ShortfallReport
): PackSection {
  const body = [
    `# ${productName}`,
    "",
    `**Firm:** ${input.firm_name}`,
    "",
    `**Reporting quarter:** ${window.label} (${window.start_inclusive} to ${window.end_exclusive}, end exclusive)`,
    "",
    `**Generated:** ${generatedAt}`,
    "",
    `**Coverage attested through:** ${shortfall.covered_to_exclusive} (exclusive)`,
    "",
    `**Signer identity:** ${signerDid}`,
    "",
  ];
  if (shortfall.in_progress_quarter) {
    body.push(
      "> PARTIAL QUARTER: this report was generated before " +
        window.label +
        " ended. It covers only the portion of the quarter through the " +
        "generation time above, NOT the full quarter. Regenerate after the " +
        "quarter closes for a complete report.",
      ""
    );
  }
  body.push(
    "This document answers, one for one, the five questions a legal " +
      "malpractice carrier now asks about AI use, and gives a third party " +
      "the instructions to verify the underlying evidence without trusting " +
      "the vendor.",
    "",
    "## Disclaimer",
    "",
    PACK_DISCLAIMER
  );
  return { title: productName, markdown: body.join("\n") };
}

// ── Section 2: executive summary ─────────────────────────────────────

function renderExecutiveSummary(
  agg: QuarterAggregation,
  shortfall: ShortfallReport,
  inv: InventorySnapshot
): PackSection {
  const machines = "1 (this Sanctuary install)";
  const c = agg.by_category;
  const toolCount = (inv.agents?.length ?? 0) + (inv.mcp_servers?.length ?? 0);
  const humanApproved = c.human_approved;
  const humanDenied = c.human_denied;
  const humanReviewed = humanApproved + humanDenied;
  const autoAllowed = c.allowed + c.allowed_proxy;
  const blendedDenied = c.denied;
  const autoBlocked = c.injection_blocked;
  const toolLine =
    toolCount === 0
      ? "**AI tools inventoried:** 0 in this preview " +
        "(live enumeration of wrapped harnesses and connected AI tool servers " +
        "is wired in a later slice; see the inventory section for the coverage " +
        "basis - this is NOT a claim that the firm uses no AI tools)."
      : `**AI tools inventoried:** ${toolCount} ` +
        "(wrapped harnesses and connected AI tool servers this install can " +
        "see; see the inventory section for coverage limits).";

  const lines = [
    "# Executive summary",
    "",
    "In plain terms, for the reporting quarter:",
    "",
    `- **Machines covered:** ${machines}.`,
    `- ${toolLine}`,
    `- **Actions reviewed by a human at the control point:** ${humanReviewed} ` +
      `(${humanApproved} approved, ${humanDenied} denied through the inbox).`,
    `- **Automated decisions:** ${autoAllowed} allowed, ${autoBlocked} blocked as ` +
      "prompt injection.",
    `- **Denied (automated policy or human control point):** ${blendedDenied} ` +
      "(these share one audit operation and cannot be split here; see section 6).",
    `- **Total recorded control-point decisions in the quarter:** ${agg.total_in_window}.`,
    "- **Unresolved incidents:** none surfaced by this preview " +
      "(the incident-response section is a labeled placeholder in this build).",
    "",
  ];
  if (shortfall.shortfall) {
    lines.push("> COVERAGE NOTICE: " + shortfall.explanation, "");
  }
  lines.push(
    "These counts reflect enforcement decisions at Sanctuary's control " +
      "point. They show that a human was in the loop for gated actions; they " +
      "do not, by themselves, prove that a supervising attorney reviewed the " +
      "output of each client matter. The written policy and per-attorney " +
      "attestations carry that half.",
    ""
  );
  return { title: "Executive summary", markdown: lines.join("\n") };
}

// ── Section 3: AI tool inventory (CNA Q1) ────────────────────────────

function renderInventory(inv: InventorySnapshot): PackSection {
  const lines = [
    "# AI tool inventory",
    "",
    "_Answers CNA Question 1: which AI tools are used._",
    "",
    "## Coverage basis (read this first)",
    "",
    "Sanctuary can enumerate only what it wraps, what flows through its " +
      "gates, and (on enforced machines) the destinations its observe engine " +
      "records. An attorney using ChatGPT in a browser tab, or Copilot inside " +
      "Word, is INVISIBLE to this inventory. This section must never be read " +
      "as an exhaustive list of AI use at the firm; the written policy and " +
      "per-attorney attestations cover unmanaged use.",
    "",
  ];

  const agents = inv.agents ?? [];
  lines.push("## Wrapped AI harnesses");
  lines.push("");
  if (agents.length === 0) {
    lines.push(
      "This preview did not enumerate wrapped harnesses from the hub agent " +
        "registry. " + PLACEHOLDER_BADGE
    );
  } else {
    lines.push("| Agent | Harness | Model | Wrapped | Status |");
    lines.push("|---|---|---|---|---|");
    for (const a of agents) {
      const model = [a.model_vendor, a.model_id].filter(Boolean).join(" / ") || "-";
      lines.push(
        `| ${a.agent_id} | ${a.harness} | ${model} | ${a.wrapped_at ?? "-"} | ${a.status ?? "-"} |`
      );
    }
  }
  lines.push("");

  const servers = inv.mcp_servers ?? [];
  lines.push("## Connected AI tool servers (MCP)");
  lines.push("");
  if (servers.length === 0) {
    lines.push(
      "This preview did not enumerate connected MCP servers. " +
        PLACEHOLDER_BADGE
    );
  } else {
    lines.push("| Server | Transport | State | Tools |");
    lines.push("|---|---|---|---|");
    for (const s of servers) {
      lines.push(
        `| ${s.name} | ${s.transport ?? "-"} | ${s.connection_state ?? "-"} | ${s.tool_count ?? "-"} |`
      );
    }
  }
  lines.push("");

  const dests = inv.observed_destinations ?? [];
  lines.push("## Observed egress destinations (enforced machines only)");
  lines.push("");
  if (dests.length === 0) {
    lines.push(
      "This preview did not include observed egress destinations. " +
        PLACEHOLDER_BADGE
    );
  } else {
    lines.push("| Destination | Port | Protocol | Seen | Exfil risk |");
    lines.push("|---|---|---|---|---|");
    for (const d of dests) {
      lines.push(
        `| ${d.host} | ${d.port ?? "-"} | ${d.protocol ?? "-"} | ${d.times_seen ?? "-"} | ${d.exfil_risk ? "yes" : "no"} |`
      );
    }
  }
  lines.push("");
  return { title: "AI tool inventory", markdown: lines.join("\n") };
}

// ── Section 4: written governance policy (CNA Q2) ────────────────────

function renderGovernancePolicy(): PackSection {
  const body = [
    "# Written governance policy",
    "",
    "_Answers CNA Question 2: is there a written AI governance policy._",
    "",
    "The signed, versioned AI-use policy and its per-attorney mapping to " +
      "professional-responsibility duties are delivered by the policy and " +
      "attestation layer.",
    "",
    PLACEHOLDER_BADGE,
    "",
    "When that layer is included, this section will also print the " +
      "technical-policy stability proof: an equal enforced-policy fingerprint " +
      "across the quarter's signed transparency checkpoints demonstrates that " +
      "the enforced technical policy did not change mid-quarter. That is a " +
      "rendering of a field the shipped checkpoint chain already signs.",
    "",
  ].join("\n");
  return { title: "Written governance policy", markdown: body };
}

// ── Section 5: training attestations (CNA Q3) ────────────────────────

function renderTrainingAttestations(): PackSection {
  const body = [
    "# Training attestations",
    "",
    "_Answers CNA Question 3: is there AI training._",
    "",
    "Per-attorney training attestations (a firm-signed, tamper-evident record " +
      "that attorney X acknowledged policy version Y on date Z) are captured " +
      "by the attestation layer.",
    "",
    PLACEHOLDER_BADGE,
    "",
    "Honest bound for this product: an attestation is a signed record that " +
      "someone ACKNOWLEDGED training, not proof they absorbed it.",
    "",
  ].join("\n");
  return { title: "Training attestations", markdown: body };
}

// ── Section 6: human review of AI actions (CNA Q4) ───────────────────

function renderHumanReview(agg: QuarterAggregation): PackSection {
  const c = agg.by_category;
  const body = [
    "# Human review of AI actions at the control point",
    "",
    "_Answers CNA Question 4: how is AI output reviewed._",
    "",
    "Every high-risk (Tier 1) action requires a human approval before it " +
      "runs, and each approval or denial is recorded in the tamper-evident " +
      "audit log with a timestamp. The counts below separate decisions a HUMAN " +
      "made at the control point from decisions the automated policy tiers made " +
      "without a human, so this section never presents an automated decision as " +
      "human oversight, or the reverse.",
    "",
    "## Decisions a human made",
    "",
    "| Outcome | Count |",
    "|---|---|",
    `| Human-approved at the control point | ${c.human_approved} |`,
    `| Human-denied through the cross-harness inbox | ${c.human_denied} |`,
    "",
    "## Decisions the automated tiers made (no human)",
    "",
    "| Outcome | Count |",
    "|---|---|",
    `| Auto-allowed (low-risk tier) | ${c.allowed} |`,
    `| Auto-allowed via proxy | ${c.allowed_proxy} |`,
    `| Blocked as prompt injection | ${c.injection_blocked} |`,
    `| Unclassified | ${c.unclassified} |`,
    "",
    "## Denials (blended - see note)",
    "",
    "| Outcome | Count |",
    "|---|---|",
    `| Denied (automated policy OR human control point) | ${c.denied} |`,
    "",
    "NOTE on the denial count: Sanctuary writes the SAME audit operation for a " +
      "human control-point denial and for an automated policy / invalid-proof / " +
      "channel-failure denial, so this report cannot split them from the log " +
      "alone. It is therefore shown as a single blended figure and is NOT " +
      "claimed to be purely automated enforcement. The per-entry audit log " +
      "distinguishes them for an auditor who reconciles against it.",
    "",
    "This measures human review of AI ACTIONS at Sanctuary's control point. " +
      "It shows a human was in the loop for gated actions; it does not, on " +
      "its own, establish that the supervising attorney reviewed the work " +
      "product of each matter. The policy and attestation layer carries the " +
      "professional-responsibility half of this question.",
    "",
  ].join("\n");
  return { title: "Human review of AI actions", markdown: body };
}

// ── Section 7: access-log and enforcement summary ────────────────────

function renderAccessLog(
  agg: QuarterAggregation,
  shortfall: ShortfallReport
): PackSection {
  const c = agg.by_category;
  const lines = [
    "# Access-log and enforcement summary",
    "",
    "_Supports CNA Question 4 and an outside-counsel audit-log ask._",
    "",
    "Sanctuary records every gated action and every denial in a hash-chained, " +
      "signed audit log. Denials are first-class rows here and are never " +
      "omitted: an action that cannot hide in audit silence is the core " +
      "honesty property of this product.",
    "",
    "| Decision | Count |",
    "|---|---|",
    `| Auto-allowed | ${c.allowed} |`,
    `| Auto-allowed via proxy | ${c.allowed_proxy} |`,
    `| Human-approved at the control point | ${c.human_approved} |`,
    `| Denied (automated policy or human control point) | ${c.denied} |`,
    `| Human-denied through the cross-harness inbox | ${c.human_denied} |`,
    `| Blocked as prompt injection | ${c.injection_blocked} |`,
    `| Unclassified | ${c.unclassified} |`,
    `| Other recorded operations | ${c.other} |`,
    "",
    `Covered window attested for this quarter: ${shortfall.covered_from} to ${shortfall.covered_to_exclusive} (exclusive). This is the span the report actually backs, which is NOT necessarily the full quarter.`,
    "",
  ];
  if (shortfall.shortfall) {
    lines.push("> COVERAGE NOTICE: " + shortfall.explanation, "");
  }
  return { title: "Access-log and enforcement summary", markdown: lines.join("\n") };
}

// ── Section 8: data boundary and custody statement ───────────────────

function renderCustody(custody: CustodyFacts | undefined): PackSection {
  const noOutbound = custody?.no_outbound_by_default !== false;
  const body = [
    "# Data boundary and custody statement",
    "",
    "_Supports an outside-counsel data-handling ask._",
    "",
    "The firm holds the keys; the vendor cannot read the firm's data. By " +
      "architecture, Sanctuary stores state encrypted at rest under the " +
      "firm's own master key, and no state data leaves the local machine " +
      "except through an explicit, human-approved export.",
    "",
    "| Fact | This install |",
    "|---|---|",
    `| Master-key custody | ${fmtCustodyMode(custody)} |`,
    `| Outbound denied by default | ${noOutbound ? "yes" : "no"} |`,
    "| Data export | requires human (Tier 1) approval |",
    "",
  ].join("\n");
  return { title: "Data boundary and custody", markdown: body };
}

// ── Section 9: incident response (CNA Q5) ────────────────────────────

function renderIncidentResponse(): PackSection {
  const body = [
    "# Incident response",
    "",
    "_Answers CNA Question 5: what is the AI incident response._",
    "",
    "The incident-response runbook, the named human who helps fill in the " +
      "carrier questionnaire, and the quarter's summary of security findings " +
      "raised and resolved are delivered by the incident-response layer.",
    "",
    PLACEHOLDER_BADGE,
    "",
  ].join("\n");
  return { title: "Incident response", markdown: body };
}

// ── Section 10: verification instructions ────────────────────────────

function renderVerification(signerDid: string): PackSection {
  const body = [
    "# Verifying this pack as a third party",
    "",
    "_For an underwriter or a client's auditor who does not trust the vendor._",
    "",
    "Each Markdown file in this pack is individually SHA-256 hashed and " +
      "Ed25519-signed with the firm's primary identity; the signatures and " +
      "hashes are recorded in `00_pack_manifest.json`. To verify a file " +
      "without any Sanctuary software:",
    "",
    "1. Recompute the file's SHA-256 (for example, `sha256sum <file>`) and " +
      "confirm it matches the `sha256` recorded for that file in the manifest.",
    "2. Verify the Ed25519 signature over that SHA-256 digest against the " +
      `signer public key in the manifest (signer: ${signerDid}).`,
    "3. Verify the manifest's own `manifest_signature` over its canonical body.",
    "",
    "IMPORTANT: the rendered PDF is a human-readable copy and is NOT itself " +
      "cryptographically signed (this is deliberate). Integrity lives in the " +
      "signed Markdown files and the manifest, not in the PDF.",
    "",
    "Where the discrete evidence exports are included alongside this pack " +
      "(the signed transparency checkpoint bundle, any public-anchor evidence, " +
      "and the audit-chain export), an auditor can independently confirm the " +
      "recorded enforcement history with the shipped standalone " +
      "`verify-transparency` tool, on a separate machine, using only the " +
      "bundle and an out-of-band copy of the public key.",
    "",
  ].join("\n");
  return { title: "Verifying this pack", markdown: body };
}

// ── Section 11: scope and limits (mandatory) ─────────────────────────

function renderScopeAndLimits(): PackSection {
  const body = [
    "# Scope and limits (what this report does and does not prove)",
    "",
    "This honesty page is mandatory. Read it before relying on the report.",
    "",
    "- **Inventory is not exhaustive.** Only wrapped harnesses, gated egress, " +
      "and (on enforced machines) observed destinations are visible. Browser " +
      "ChatGPT, Copilot inside Office, and phones are not.",
    "- **No wire-level proof.** A checkpoint proves the recorded enforcement " +
      "history, not packets blocked on the wire. Per-machine authenticity " +
      "basis can differ (per-event producer-signed on Linux; " +
      "channel-authenticated on macOS).",
    "- **We do not claim per-rule per-flow auditing.** The shipped claim is: " +
      "enforces a signed operator policy, with a tamper-evident log and " +
      "signed enforcement-activity totals.",
    "- **Freshness.** A stale but genesis-rooted bundle can still pass offline " +
      "verification; only opt-in public anchoring plus a pinned log key gives " +
      "an auditor freshness and fork detection.",
    "- **Self-reported binary hash; no remote attestation.**",
    "- **Covered window (both ends).** Audit retention is size/count-based " +
      "(FIFO), not time-based, so a busy fortress can prune early-quarter " +
      "entries (start-side shortfall); and a report generated before the " +
      "quarter closes can only attest coverage through its generation time " +
      "(end-side / partial-quarter shortfall). This report detects and " +
      "discloses both above and states the real covered-through instant, " +
      "never assuming coverage to the quarter end.",
    "- **Human vs automated decisions are separated.** Human control-point " +
      "approvals/denials are counted apart from automated-tier decisions. The " +
      "denial figure is blended (one shared audit operation) and is not " +
      "claimed to be purely automated enforcement.",
    "- **Human-review counts** reflect the control-point operator gate, not " +
      "a supervising attorney's per-matter review.",
    "- **Attestations prove acknowledgment, not competence.**",
    "- **Not legal advice, no carrier endorsement.**",
    "",
  ].join("\n");
  return { title: "Scope and limits", markdown: body };
}

// ── Appendix B: per-machine detail ───────────────────────────────────

function renderPerMachineAppendix(): PackSection {
  const body = [
    "# Appendix B: per-machine detail",
    "",
    "Per-machine rows (node id, label, enforcement level, last seen, policy " +
      "version, drift state) with an assurance label (enforced / cooperative / " +
      "unmanaged-attested) are delivered by the fleet-wide pack.",
    "",
    PLACEHOLDER_BADGE,
    "",
  ].join("\n");
  return { title: "Appendix B: per-machine detail", markdown: body };
}

// ── Assembly ─────────────────────────────────────────────────────────

/**
 * Render the full ordered section list for the pack. `productName` is the
 * working title on the cover. The returned sections feed both the signed
 * Markdown report and the PDF (one PDF page-group per section).
 */
export function renderSections(params: {
  input: EvidencePackInput;
  window: QuarterWindow;
  generatedAt: string;
  signerDid: string;
  productName: string;
  aggregation: QuarterAggregation;
  shortfall: ShortfallReport;
}): PackSection[] {
  const inv = params.input.inventory ?? {};
  return [
    renderCover(
      params.input,
      params.window,
      params.generatedAt,
      params.signerDid,
      params.productName,
      params.shortfall
    ),
    renderExecutiveSummary(params.aggregation, params.shortfall, inv),
    renderInventory(inv),
    renderGovernancePolicy(),
    renderTrainingAttestations(),
    renderHumanReview(params.aggregation),
    renderAccessLog(params.aggregation, params.shortfall),
    renderCustody(params.input.custody),
    renderIncidentResponse(),
    renderVerification(params.signerDid),
    renderScopeAndLimits(),
    renderPerMachineAppendix(),
  ];
}
