/**
 * Sanctuary MCP Server - Law-firm Evidence Pack: section renderers
 *
 * Copyright 2026 Erik Newton
 * SPDX-License-Identifier: Apache-2.0
 *
 * Renders the human-readable Markdown sections of the quarterly evidence pack,
 * mapped one-for-one to the five questions a malpractice carrier now asks on
 * the CNA AI supplement. Written for the reader it will actually have: an
 * office manager, an underwriter, or a client's outside-counsel-guidelines
 * auditor. Every section leads with a plain-English sentence.
 *
 * Slice 1 (walking skeleton) renders the sections that the shipped audit +
 * inventory surfaces can honestly fill; sections that require a later slice
 * (policy/attestation templates, fleet roster, incident-response runbook)
 * render a clearly-labeled "not yet included in this preview" placeholder
 * rather than fabricating content. A lawyer will read this, so it never
 * overclaims.
 *
 * NOT LEGAL ADVICE. The CNA mapping is a reading of the carrier supplement,
 * not a carrier-endorsed format.
 */

import type {
  CustodyFacts,
  EvidencePackInput,
  InventoryAgentRow,
  InventoryMcpServerRow,
  InventoryObservedDestinationRow,
  InventorySnapshot,
  QuarterAggregation,
  ShortfallReport,
} from "./types.js";
import type { QuarterWindow } from "./types.js";
import { notCollectedInventorySnapshot } from "./inventory.js";
import {
  claimFromCompleteRead,
  foldOutcome,
  type ReadOutcome,
} from "./read-outcome.js";

/** One rendered section: a title (PDF page heading) plus its Markdown body. */
export interface PackSection {
  title: string;
  markdown: string;
}

const PLACEHOLDER_BADGE =
  "_[NOT YET INCLUDED IN THIS PREVIEW - a later build slice fills this " +
  "section; it is intentionally blank rather than fabricated.]_";

/** Static disclaimer carried on the cover and in the manifest. */
export const PACK_DISCLAIMER =
  "This evidence pack is a technical artifact generated by the Sanctuary " +
  "Framework. It is NOT legal advice and does not constitute a legal " +
  "interpretation of any professional-responsibility rule, insurance " +
  "questionnaire, or outside-counsel guideline. The mapping to carrier " +
  "questions is Sanctuary's reading of the supplement, not a carrier " +
  "endorsement. Have the policy and attestation content reviewed by a " +
  "licensed attorney before first use.";

function fmtCustodyMode(custody: CustodyFacts | undefined): string {
  switch (custody?.custody_mode) {
    case "passphrase":
      return "passphrase held by the firm";
    case "keychain":
      return "operating-system keychain on the firm's machine";
    default:
      return "not reported by this install";
  }
}

// ── Section 1: cover ─────────────────────────────────────────────────

function renderCover(
  input: EvidencePackInput,
  window: QuarterWindow,
  generatedAt: string,
  signerDid: string,
  productName: string,
  shortfall: ReadOutcome<ShortfallReport>
): PackSection {
  // The covered SPAN and any shortfall/partial banner are DEFINITIVE coverage
  // claims, so they may only be drawn from a completed audit read. The cover
  // shows BOTH bounds (not just the end) so a cover-only reader is not misled
  // when early entries were pruned in a completed quarter (MED-1).
  const coveredSpan = foldOutcome(shortfall, {
    populated: (s) => `${s.covered_from} to ${s.covered_to_exclusive} (exclusive)`,
    emptyVerified: () => "could not be determined",
    readFailed: () => "could not be determined (the audit log could not be read)",
  });
  const body = [
    `# ${productName}`,
    "",
    `**Firm:** ${input.firm_name}`,
    "",
    `**Reporting quarter:** ${window.label} (${window.start_inclusive} to ${window.end_exclusive}, end exclusive)`,
    "",
    `**Generated:** ${generatedAt}`,
    "",
    `**Coverage (signed span this report backs):** ${coveredSpan}`,
    "",
    `**Signer identity (the firm's own key):** ${signerDid}`,
    "",
  ];
  const banner = foldOutcome(shortfall, {
    populated: (s) => {
      if (s.in_progress_quarter) {
        return [
          "> PARTIAL QUARTER: this report was generated before " +
            window.label +
            " ended. It covers only the portion of the quarter through " +
            s.covered_to_exclusive +
            ", NOT the full quarter. Regenerate after the quarter closes for a " +
            "complete report.",
          "",
        ];
      }
      if (s.zero_of_quarter_covered) {
        return [
          "> COVERAGE NOTICE: NONE of this quarter is covered; no entries from " +
            window.label +
            " survive in the retained log. See the access-log section for " +
            "details.",
          "",
        ];
      }
      if (s.shortfall) {
        return [
          "> COVERAGE NOTICE: the signed span above does NOT reach the quarter " +
            "start; earlier-quarter access history is not in the retained log. " +
            "See the access-log section for details.",
          "",
        ];
      }
      return [];
    },
    emptyVerified: () => [],
    readFailed: (reason) => [
      "> COVERAGE UNAVAILABLE: the audit log could not be read, so the covered " +
        "window could not be computed for this quarter. This report makes NO " +
        "coverage claim. Reason: " +
        reason,
      "",
    ],
  });
  body.push(...banner);
  body.push(
    // HIGH-4: honest evidence-toward framing. Three of the five CNA sections are
    // labeled placeholders in this build, and every file is self-signed with the
    // FIRM's key (not vendor-independent), so the cover must not claim the doc
    // "answers, one for one" all five, nor "without trusting the vendor".
    "This document is organized around the five questions a malpractice " +
      "carrier's AI supplement commonly asks (Sanctuary's reading of the CNA " +
      "supplement, not a carrier-endorsed format). It presents the evidence " +
      "Sanctuary can produce for each; sections marked NOT YET INCLUDED are " +
      "flagged in place (in this build the governance-policy, training, and " +
      "incident-response sections are placeholders). It also gives instructions " +
      "to check the signed files for tampering since the firm signed them and, " +
      "where a transparency bundle is included, to verify the enforcement " +
      "history against a vendor-independent key.",
    "",
    "## Disclaimer",
    "",
    PACK_DISCLAIMER
  );
  return { title: productName, markdown: body.join("\n") };
}

// ── Section 2: executive summary ─────────────────────────────────────

/**
 * The exec-summary "AI tools inventoried" line. The tool count is a DEFINITIVE
 * number, so it is emitted ONLY when both tool sources (wrapped harnesses +
 * configured MCP servers) were read to completion; a `read_failed` on either
 * renders "could not be fully determined" instead of a bare "0", and the "0"
 * wording itself is gated through {@link claimFromCompleteRead} on a Complete
 * witness. This is the MED-1 fix: a failed read can never print as a definitive
 * zero via the type, not merely via adjacent prose.
 */
function toolInventoryLine(inv: InventorySnapshot): string {
  if (
    inv.agents.status === "read_failed" ||
    inv.mcp_servers.status === "read_failed"
  ) {
    return (
      "**AI tools inventoried:** could not be fully determined this period " +
      "(one or more inventory sources could not be read; see the inventory " +
      "section for which and why). This is NOT a count of zero."
    );
  }
  // Both tool sources are Complete here (TS narrows out `read_failed`).
  const agentRows = inv.agents.status === "populated" ? inv.agents.value : [];
  const mcpRows =
    inv.mcp_servers.status === "populated" ? inv.mcp_servers.value : [];
  const count = agentRows.length + mcpRows.length;
  // MED-1 (sample-render): the flat count silently includes a RETIRED harness
  // and a DISABLED server as if they were live tools. Carry the denominator: an
  // agent is active only when its status is explicitly "active", an MCP server
  // only when it is enabled.
  const active =
    agentRows.filter((a) => a.status === "active").length +
    mcpRows.filter((s) => s.enabled === true).length;
  const destNote =
    inv.observed_destinations.status === "read_failed"
      ? " (Note: the observed-egress-destination source could not be read; " +
        "see the inventory section.)"
      : "";
  if (count === 0) {
    return (
      claimFromCompleteRead(
        inv.agents,
        "**AI tools inventoried:** 0 (wrapped harnesses and configured AI tool " +
          "servers this install can see; see the inventory section for the " +
          "coverage basis - this is NOT a claim that the firm uses no AI tools)."
      ) + destNote
    );
  }
  return (
    `**AI tools inventoried:** ${count} recorded, of which ${active} active ` +
    "(this is CONFIGURED inventory - wrapped harnesses and configured AI tool " +
    "servers, including any retired harness or disabled server - NOT a count of " +
    "live tools; see the inventory section)." +
    destNote
  );
}

function renderExecutiveSummary(
  aggregation: ReadOutcome<QuarterAggregation>,
  shortfall: ReadOutcome<ShortfallReport>,
  inv: InventorySnapshot
): PackSection {
  const machines = "1 (this Sanctuary install)";
  const toolLine = toolInventoryLine(inv);

  // The decision-count bullets are DEFINITIVE claims (e.g. "0 denied"), so they
  // may only be drawn from a completed audit read. A read failure prints an
  // honest "could not be computed" bullet instead of a flattering zero.
  const decisionBullets = foldOutcome(aggregation, {
    populated: (agg) => {
      const c = agg.by_category;
      const bullets = [
        `- **Actions reviewed by a human at the control point:** ${c.human_approved + c.human_denied} ` +
          `(${c.human_approved} approved, ${c.human_denied} denied by an operator).`,
        `- **Automated decisions:** ${c.allowed + c.allowed_proxy} allowed, ${c.denied} denied by policy, ` +
          `${c.injection_blocked} blocked as prompt injection, ${c.unclassified} unclassified.`,
        `- **Total recorded audit operations in the quarter:** ${agg.total_in_window} ` +
          `(${agg.total_in_window - c.other} control-point decisions + ${c.other} ` +
          "other recorded operations that are not control-point decisions).",
      ];
      if (c.uncategorized > 0) {
        bullets.push(
          `- **Uncategorized control-point operations:** ${c.uncategorized} ` +
            "(recorded gate operations this report version does not classify; " +
            "surfaced, not folded into a decision total - see section 6)."
        );
      }
      return bullets;
    },
    emptyVerified: () => [
      "- **Control-point decision counts:** could not be computed for this quarter.",
    ],
    readFailed: (reason) => [
      "- **Control-point decision counts:** could NOT be computed for this " +
        "quarter because the audit log could not be read, so no approval, " +
        "denial, or total counts are asserted. Reason: " +
        reason,
    ],
  });

  const lines = [
    "# Executive summary",
    "",
    "In plain terms, for the reporting quarter:",
    "",
    `- **Machines covered by this report:** ${machines}; it does not enumerate other firm machines.`,
    `- ${toolLine}`,
    ...decisionBullets,
    // HIGH-3: never a flattering "none" from an unread source. Incident response
    // is a placeholder in this build; make no claim in either direction.
    "- **Incidents:** not assessed in this build. Incident-response reporting is " +
      "a labeled placeholder (section 9); this report makes no claim, in either " +
      "direction, about incidents this quarter.",
    "",
  ];
  const coverageNotice = foldOutcome(shortfall, {
    populated: (s) => (s.shortfall ? ["> COVERAGE NOTICE: " + s.explanation, ""] : []),
    emptyVerified: () => [],
    readFailed: (reason) => [
      "> COVERAGE NOTICE: the covered window could not be computed (the audit " +
        "log could not be read): " +
        reason,
      "",
    ],
  });
  lines.push(...coverageNotice);
  lines.push(
    "These counts reflect enforcement decisions at Sanctuary's control " +
      "point. They show that a human was in the loop for gated actions; they " +
      "do not, by themselves, prove that a supervising attorney reviewed the " +
      "output of each client matter. The written policy and per-attorney " +
      "attestations carry that half.",
    ""
  );
  return { title: "Executive summary", markdown: lines.join("\n") };
}

// ── Section 3: AI tool inventory (CNA Q1) ────────────────────────────

function renderInventory(inv: InventorySnapshot): PackSection {
  const lines = [
    "# AI tool inventory",
    "",
    "_Answers CNA Question 1: which AI tools are used._",
    "",
    "## Coverage basis (read this first)",
    "",
    "Sanctuary can enumerate only what it wraps, what flows through its " +
      "gates, and (on enforced machines) the destinations its observe engine " +
      "records. An attorney using ChatGPT in a browser tab, or Copilot inside " +
      "Word, is INVISIBLE to this inventory. This section must never be read " +
      "as an exhaustive list of AI use at the firm; the written policy and " +
      "per-attorney attestations cover unmanaged use.",
    "",
  ];

  // Wrapped AI harnesses. The definitive "none recorded" line is emitted ONLY
  // from a Complete witness (empty_verified); a read failure prints the honest
  // incomplete note. This is the typed chokepoint - see read-outcome.ts.
  lines.push("## Wrapped AI harnesses");
  lines.push("");
  lines.push(
    ...foldOutcome(inv.agents, {
      populated: (rows) => agentTable(rows),
      emptyVerified: (witness) => [
        claimFromCompleteRead(
          witness,
          "No wrapped AI harnesses are recorded in the hub agent registry on this fortress."
        ),
      ],
      readFailed: (reason) => [incompleteNote("wrapped-harness", reason)],
    })
  );
  lines.push("");

  // Configured MCP tool servers.
  lines.push("## Configured AI tool servers (MCP)");
  lines.push("");
  lines.push(
    "The upstream MCP tool servers this fortress is configured to gateway. " +
      "State and tool counts reflect configuration; the pack does not open a " +
      "live connection to probe them during generation."
  );
  lines.push("");
  lines.push(
    ...foldOutcome(inv.mcp_servers, {
      populated: (rows) => mcpTable(rows),
      emptyVerified: (witness) => [
        claimFromCompleteRead(
          witness,
          "No MCP tool servers are configured on this fortress."
        ),
      ],
      readFailed: (reason) => [incompleteNote("MCP tool server", reason)],
    })
  );
  lines.push("");

  // Observed egress destinations.
  lines.push("## Observed egress destinations (enforced machines only)");
  lines.push("");
  lines.push(
    ...foldOutcome(inv.observed_destinations, {
      populated: (rows) =>
        destinationTable(rows, inv.observed_destinations_pre_idempotency === true),
      emptyVerified: (witness) => [
        claimFromCompleteRead(
          witness,
          // L1-MED-6: a bare "none recorded" reads as "nothing exfiltrated" on a
          // host that does not observe egress at all (Windows, or un-walled
          // macOS). Egress observation records only on enforced machines, so
          // absence here is NOT evidence that no data left the machine.
          "No egress destinations were recorded. Egress observation records " +
            "only on enforced machines with the observe engine armed; on a " +
            "host without it, nothing is recorded regardless of activity. " +
            "Absence here is NOT evidence that no data left the machine."
        ),
      ],
      readFailed: (reason) => [
        incompleteNote("observed egress destination", reason),
      ],
    })
  );
  lines.push("");
  // Closing reinforcement (printed whether the tables above are empty or full):
  // a POPULATED inventory is still not a complete picture, so a reader who
  // skips the coverage-basis header still sees the bound right after the rows.
  // This must never be dropped (paramount honesty rule). It warns in BOTH
  // directions: under-inclusion (tools Sanctuary cannot see) and over-inclusion
  // (a stale persisted row for a since-removed tool).
  lines.push(
    "What is NOT in this inventory, and what may be stale: any AI tool " +
      "Sanctuary does not wrap or observe is absent (browser-based AI such as " +
      "ChatGPT in a browser tab, AI embedded in other applications, and use on " +
      "phones or unmanaged machines), so a populated list above is the AI use " +
      "Sanctuary can see on this install, NOT a complete census of the firm's " +
      "AI use. Conversely, the rows reflect the LAST PERSISTED configuration " +
      "and may still list a tool the firm has since decommissioned; this is " +
      "not a point-in-time liveness attestation. Reconcile against current " +
      "configuration, and rely on the written policy and per-attorney " +
      "attestations for unmanaged use."
  );
  lines.push("");
  return { title: "AI tool inventory", markdown: lines.join("\n") };
}

/**
 * Honest wording for a source whose store could NOT be read. It must never read
 * as an affirmative "none exist" census claim (slice-2 HIGH-1): a read failure
 * is disclosed as incomplete, with the reason, distinct from a genuine empty.
 * There is no code path from a `read_failed` outcome to a definitive-negative
 * line (that requires a Complete witness via {@link claimFromCompleteRead}), so
 * this note is the ONLY thing a failed inventory read can render.
 */
function incompleteNote(sourceLabel: string, reason: string): string {
  return (
    `The ${sourceLabel} inventory could not be read for this period, so this ` +
    "section is INCOMPLETE. This is NOT a statement that none exist. " +
    PLACEHOLDER_BADGE +
    ` Reason: ${reason}`
  );
}

function agentTable(rows: InventoryAgentRow[]): string[] {
  const out = ["| Agent | Harness | Model | Wrapped | Status |", "|---|---|---|---|---|"];
  for (const a of rows) {
    const model = [a.model_vendor, a.model_id].filter(Boolean).join(" / ") || "-";
    out.push(
      `| ${a.agent_id} | ${a.harness} | ${model} | ${a.wrapped_at ?? "-"} | ${a.status ?? "-"} |`
    );
  }
  return out;
}

function mcpTable(rows: InventoryMcpServerRow[]): string[] {
  const out = ["| Server | Transport | Enabled | State | Tools |", "|---|---|---|---|---|"];
  for (const s of rows) {
    const enabled = s.enabled === undefined ? "-" : s.enabled ? "yes" : "no";
    out.push(
      `| ${s.name} | ${s.transport ?? "-"} | ${enabled} | ${s.connection_state ?? "-"} | ${s.tool_count ?? "-"} |`
    );
  }
  return out;
}

function destinationTable(
  rows: InventoryObservedDestinationRow[],
  seenCountsMayPredateIdempotency = false,
): string[] {
  // HIGH-1 (sample-render): the column was a bare "Exfil risk: yes/no", which a
  // non-technical underwriter can misread as the firm SELF-REPORTING that data
  // was exfiltrated - especially next to an incident section that says "not
  // assessed". It is actually a heuristic CLASSIFICATION of the destination, not
  // a finding that anything left the firm. Relabel to a risk CLASS and define it
  // in an unmissable legend before the table.
  //
  // OPEN-MED-1 (confirmatory review 2026-07-14): "Seen" renders `times_seen`,
  // the observe store's cumulative count - it is NOT quarter-scoped (the
  // observe store is not quarter-indexed; quarter-scoping is a deliberate
  // out-of-scope build-slice decision). Inside a report whose cover names a
  // reporting quarter, a reader would otherwise infer the count is
  // quarter-scoped, so disclose the count's basis in the legend.
  //
  // F2 (round-2 sweep 2026-07-14; basis verified against the ENGINE after the
  // round-3 R3-1 fix): the count's true basis is the CURRENT candidate
  // record, not "since observation began". The observe refresh chokepoint
  // (castle-wall/observe/refresh.ts, the R3-1 fold-watermark engine this
  // stack rebases on) folds each recorded denial into the store EXACTLY
  // once, `observe discard`/promote delete the candidate row, and only a
  // genuinely NEW denial re-mints it -- restarting its count at 1. The
  // legend states those reset semantics; the round-3 sweep proved the
  // PRE-watermark engine did not honor them (it re-folded retained history
  // additively, inflating counts and resurrecting rows), which is why the
  // engine was fixed rather than this wording softened a third time.
  //
  // F1 (round-2 sweep 2026-07-14; basis RE-VERIFIED against the ENGINE after
  // the round-3 R3-1 fix, its two-family-gate hardening, AND #934's
  // provenance-scoped belt + Linux flat-shape fold -- round-4 R4-1): the
  // observe engine folds ONLY denied flows into candidates (adapter.ts gates
  // both the nested and the #934 flat arm on `egress_blocked` and stamps
  // `disposition: "denied"`; castle-wall/observe/fold.ts, enforce-preserving
  // posture D-Q1), so every row here is a destination the wall BLOCKED and
  // allowed egress is structurally absent -- TRUE on macOS AND on the Linux
  // daemon rows #934 newly folds. The refresh chokepoint
  // (castle-wall/observe/refresh.ts) suppresses and prunes a candidate ONLY
  // when it can POSITIVELY verify the current signed policy permits that flow
  // for the attempting agent across every enforcement path (an exact host/IP
  // allow with covering scope and no matching deny -- exactly what the promote
  // workflow writes), so a PROMOTED destination no longer re-enters this table
  // from retained history.
  //
  // #934 PROVENANCE SCOPE (R4-1 re-truing): that auto-suppression belt is now
  // OPERATIVE for Linux-daemon-attributed rows (`refresh.ts:288` no longer
  // exempts them) but INERT for the current macOS build, where every flow is
  // recorded with the default resolver's `agent_template: "unknown"` and
  // `provenance` macos, which `refresh.ts:288` refuses to suppress -- so a
  // macOS destination the policy permits is NOT auto-cleared and stays listed
  // until the operator promotes or discards it (promote deletes the row on
  // every platform, independent of the belt). The legend now discloses this
  // macOS-`"unknown"` case explicitly rather than presenting auto-clearing as
  // universal; it still EXPLICITLY discloses that a row may remain listed when
  // its permission cannot be verified that exactly (pattern/scoped-rule cases)
  // -- a definitive "permitted destinations never appear" absolute would be
  // falsifiable, and the round-1..3 sweeps graded exactly such falsifiable
  // absolutes HIGH. Never re-widen this wording without re-verifying the
  // engine.
  const out = [
    "Legend - Row basis: this table records BLOCKED flow observations only. " +
      "Each row is a destination the wall DENIED; the Seen count is a count " +
      "of those denied attempts. This table never lists allowed egress: " +
      "every row was denied when observed, and as of its most recent " +
      "refresh the observe engine records no candidate, and clears any " +
      "pending candidate, for a flow it can positively verify the current " +
      "signed policy permits for the agent that attempted it (an exact " +
      "host or IP allow rule, as written by the promote workflow). That " +
      "automatic clearing applies only where the engine can attribute the " +
      "flow to an agent whose allow rule it can verify -- Linux " +
      "enforcement-daemon rows today. On the current macOS build every flow " +
      "is recorded with an unresolved \"unknown\" agent attribution that no " +
      "allow rule's scope can be verified to cover, so macOS rows are NOT " +
      "auto-cleared by policy; a macOS destination you have permitted stays " +
      "listed until you clear it by promoting or discarding it (`observe " +
      "promote` / `observe discard`). A row may also remain listed while its " +
      "permission cannot be verified that exactly (for example a " +
      "hostname-pattern rule, or a rule scoped to a different agent whose " +
      "own attempts stay denied); a listed row therefore means denied " +
      "attempts were recorded, never that data was exchanged. Reconcile this " +
      "table against current policy. Allowed egress is not inventoried by " +
      "this table or this version of the pack, so this table is not a census " +
      "of where the machines' traffic actually went.",
    "",
    "Legend - Destination risk class: a heuristic CATEGORY of the destination " +
      "itself (for example, a messaging or paste host that could be misused for " +
      'exfiltration is "elevated"; a routine AI/API endpoint is "standard"). It ' +
      "is NOT a finding that any data left the firm, NOT a confirmed " +
      "exfiltration, and NOT a legal conclusion. See the Incident response " +
      "section for incident status. An 'elevated' row means only that this " +
      "destination is worth a human review.",
    "",
    "Legend - Seen: the number of denied flow observations recorded since " +
      "this destination's current candidate record was created. A destination " +
      "that was discarded or promoted and later observed again restarts its " +
      "count. It is NOT a count scoped to the reporting quarter, and a " +
      "destination listed here may not have been seen within the reporting " +
      "quarter.",
    "",
  ];
  if (seenCountsMayPredateIdempotency) {
    // R4-2 (round-4 sweep 2026-07-15; gate-hardened): the observe store held
    // candidate rows but NO fold watermark -- it has not completed a
    // reconciling refresh. This is a legacy PRE-#931 additive store, OR (the
    // narrow safe-direction case both gate families flagged) a post-#931 store
    // whose recompute-heal crashed between writing rows and advancing the
    // watermark (refresh.ts writes rows then the watermark, non-atomically by
    // design). In EITHER case the pack renders the persisted store faithfully
    // without mutating it, so it discloses the un-reconciled condition rather
    // than presenting the rows as if a reconciling refresh had run.
    //
    // The caveat does NOT attribute a specific cause ("earlier engine
    // version" would be false in the crash-window case -- Codex HIGH #1), and
    // it does NOT claim membership is unaffected: the PRE-#931 additive engine
    // could resurrect promoted/discarded destinations from retained history
    // and did not prune now-allowed destinations, so the LISTED SET (not just
    // the Seen magnitude) may be un-reconciled (Codex HIGH #2). The remedy
    // clause is scoped precisely (gate runs 2+3 HIGH): a reconciling refresh
    // clears a row ONLY under `candidateCurrentlyAllowed` (refresh.ts prune at
    // ~:568-575) -- the SAME exact, provenance-scoped condition the Row-basis
    // legend already discloses, so the caveat defers to it rather than
    // re-stating it (and, like the legend, must NOT over-generalize: a macOS
    // 'unknown' row the policy permits is NEVER auto-cleared, refresh.ts:288;
    // pattern/cidr allows and deny-shadowed rows also do not clear). PROMOTED
    // destinations do clear because promote synthesizes the exact allow rule
    // that predicate matches. A re-surfaced DISCARDED destination is NOT
    // removed: a discard leaves no allow rule, and the recompute-heal's
    // replacement path (refresh.ts ~:534-537) keeps any already-persisted key
    // present in the full-history fold, so an already-resurfaced discard
    // survives; the operator must discard it again.
    // What DOES hold regardless of the watermark is the blocked-only fold basis
    // (adapter.ts gates on egress_blocked; fold.ts folds only denied), so every
    // listed row is still a recorded denied observation -- the caveat preserves
    // that true invariant. Running `castle-wall observe candidates` completes
    // the reconciling refresh (idempotent recompute, and for a crashed heal
    // simply finishes it); regenerate the pack afterward.
    out.push(
      "CAVEAT - this install's observe store has not completed a reconciling " +
        "refresh (no fold watermark is present), so the rows below may not " +
        "reflect a reconciled state. The Seen counts may OVERSTATE the " +
        "per-candidate basis described above, AND the listed set may not match " +
        "what a completed refresh would show: it may still include a " +
        "destination the engine would clear under the current policy on refresh " +
        "(only under the exact, provenance-scoped conditions described in the " +
        "Row-basis legend above -- notably NOT a macOS 'unknown' row, which is " +
        "never auto-cleared), and it may include a destination you previously " +
        "discarded that an earlier fold re-surfaced, which a refresh does NOT " +
        "remove (you would need to discard it again). What still holds is that " +
        "every listed row is a destination where denied attempts were recorded " +
        "(the blocked-only basis does not depend on the refresh). Run `sanctuary " +
        "castle-wall observe candidates` (which completes the reconciling " +
        "refresh), re-discard any re-surfaced destinations, and regenerate this " +
        "pack.",
      "",
    );
  }
  out.push(
    "| Destination | Port | Protocol | Seen | Destination risk class |",
    "|---|---|---|---|---|",
  );
  for (const d of rows) {
    const riskClass = d.exfil_risk ? "elevated (review)" : "standard";
    out.push(
      `| ${d.host} | ${d.port ?? "-"} | ${d.protocol ?? "-"} | ${d.times_seen ?? "-"} | ${riskClass} |`
    );
  }
  return out;
}

// ── Section 4: written governance policy (CNA Q2) ────────────────────

function renderGovernancePolicy(): PackSection {
  const body = [
    "# Written governance policy",
    "",
    "_Maps to CNA Question 2 (written AI governance policy), delivered by the policy/attestation layer; NOT included in this build._",
    "",
    "The signed, versioned AI-use policy and its per-attorney mapping to " +
      "professional-responsibility duties are delivered by the policy and " +
      "attestation layer.",
    "",
    PLACEHOLDER_BADGE,
    "",
    "When that layer is included, this section will also print the " +
      "technical-policy stability proof: an equal enforced-policy fingerprint " +
      "across the quarter's signed transparency checkpoints demonstrates that " +
      "the enforced technical policy did not change mid-quarter. That is a " +
      "rendering of a field the shipped checkpoint chain already signs.",
    "",
  ].join("\n");
  return { title: "Written governance policy", markdown: body };
}

// ── Section 5: training attestations (CNA Q3) ────────────────────────

function renderTrainingAttestations(): PackSection {
  const body = [
    "# Training attestations",
    "",
    "_Maps to CNA Question 3 (AI training), delivered by the policy/attestation layer; NOT included in this build._",
    "",
    "Per-attorney training attestations (a firm-signed, tamper-evident record " +
      "that attorney X acknowledged policy version Y on date Z) are captured " +
      "by the attestation layer.",
    "",
    PLACEHOLDER_BADGE,
    "",
    "Honest bound for this product: an attestation is a signed record that " +
      "someone ACKNOWLEDGED training, not proof they absorbed it.",
    "",
  ].join("\n");
  return { title: "Training attestations", markdown: body };
}

// ── Section 6: human review of AI actions (CNA Q4) ───────────────────

/** Honest language for a decision-count section when the audit read failed. */
function countsUnavailable(reason: string): string[] {
  return [
    "The control-point decision counts could not be computed for this quarter " +
      "because the audit log could not be read, so this section asserts NO " +
      "approval, denial, or automated-decision counts (in particular it does " +
      "NOT claim there were none). " +
      PLACEHOLDER_BADGE +
      ` Reason: ${reason}`,
    "",
  ];
}

function renderHumanReview(
  aggregation: ReadOutcome<QuarterAggregation>
): PackSection {
  const lead = [
    "# Human review of AI actions at the control point",
    "",
    "_Answers CNA Question 4: how is AI output reviewed._",
    "",
    "In Sanctuary's design, actions classified Tier 1 require a human approval " +
      "before they run, and each approval or denial is recorded in the " +
      "tamper-evident audit log with a timestamp. (Whether a given action was " +
      "Tier 1 depends on the operator's policy configuration, which this report " +
      "does not itself attest.) The counts below reflect the approvals and " +
      "denials actually recorded in this install's audit log, separating " +
      "decisions a HUMAN made at the control point from decisions the automated " +
      "policy tiers made without a human, so this section never presents an " +
      "automated decision as human oversight, or the reverse.",
    "",
  ];
  const body = foldOutcome(aggregation, {
    populated: (agg) => {
      const c = agg.by_category;
      const rows = [
        "## Decisions a human made at the control point",
        "",
        "| Outcome | Count |",
        "|---|---|",
        `| Human-approved | ${c.human_approved} |`,
        `| Human-denied | ${c.human_denied} |`,
        "",
        "## Decisions the automated tiers made (no human)",
        "",
        "| Outcome | Count |",
        "|---|---|",
        `| Auto-allowed (low-risk tier) | ${c.allowed} |`,
        `| Auto-allowed via proxy | ${c.allowed_proxy} |`,
        `| Denied by automated policy (no human) | ${c.denied} |`,
        `| Blocked as prompt injection | ${c.injection_blocked} |`,
        `| Unclassified | ${c.unclassified} |`,
        "",
        "NOTE on human vs automated: Sanctuary writes the SAME audit operation " +
          "(`gate_approve:` / `gate_deny:`) for a human control-point decision and " +
          "for an automated one, but each entry records WHO decided (the gate's " +
          "`decided_by` field). This report attributes a decision to the human " +
          "rows only when that field is 'human' (an operator approved or denied, " +
          "via the inbox or the interactive channel); automated policy, " +
          "invalid-proof, channel-failure, and timeout decisions are counted as " +
          "automated. So a human approval or denial is counted exactly once, in " +
          "the human row.",
        "",
      ];
      if (c.uncategorized > 0) {
        rows.push(
          "## Uncategorized control-point operations",
          "",
          `${c.uncategorized} recorded gate operation(s) matched a control-point ` +
            "decision shape that this report version does NOT classify. They are " +
            "surfaced here rather than folded into an allow/deny total or hidden " +
            "in 'other'. Investigate before relying on the decision counts (this " +
            "usually means a newer Sanctuary daemon emitted a decision op this " +
            "pack does not yet map).",
          ""
        );
      }
      rows.push(
        "This measures human review of AI ACTIONS at Sanctuary's control point. " +
          "It shows a human was in the loop for gated actions; it does not, on " +
          "its own, establish that the supervising attorney reviewed the work " +
          "product of each matter. The policy and attestation layer carries the " +
          "professional-responsibility half of this question.",
        ""
      );
      return rows;
    },
    emptyVerified: () => countsUnavailable("the audit read returned no result."),
    readFailed: (reason) => countsUnavailable(reason),
  });
  return {
    title: "Human review of AI actions",
    markdown: [...lead, ...body].join("\n"),
  };
}

// ── Section 7: access-log and enforcement summary ────────────────────

function renderAccessLog(
  aggregation: ReadOutcome<QuarterAggregation>,
  shortfall: ReadOutcome<ShortfallReport>
): PackSection {
  const lead = [
    "# Access-log and enforcement summary",
    "",
    "_Supports CNA Question 4 and an outside-counsel audit-log ask._",
    "",
    "Sanctuary records gated actions and denials in a hash-chained, signed " +
      "audit log, and denials are first-class rows here, not omitted. " +
      "(Per-entry detail is subject to the retention limits described in Scope " +
      "and limits.)",
    "",
  ];
  const table = foldOutcome(aggregation, {
    populated: (agg) => {
      const c = agg.by_category;
      const rows = [
        "| Decision | Count |",
        "|---|---|",
        `| Auto-allowed | ${c.allowed} |`,
        `| Auto-allowed via proxy | ${c.allowed_proxy} |`,
        `| Human-approved at the control point | ${c.human_approved} |`,
        `| Denied by automated policy (no human) | ${c.denied} |`,
        `| Human-denied at the control point | ${c.human_denied} |`,
        `| Blocked as prompt injection | ${c.injection_blocked} |`,
        `| Unclassified | ${c.unclassified} |`,
        `| Uncategorized (surfaced, not folded) | ${c.uncategorized} |`,
        `| Other recorded operations | ${c.other} |`,
        "",
      ];
      return rows;
    },
    emptyVerified: () => countsUnavailable("the audit read returned no result."),
    readFailed: (reason) => countsUnavailable(reason),
  });
  const window = foldOutcome(shortfall, {
    populated: (s) => [
      // R3-2: the covered window is derived from what the retained log SPANS.
      // Without the second clause, a quarter where Sanctuary was simply not
      // running (retained entries on both sides, zero decisions in between)
      // reads as "fully covered, zero denials, everything enforced".
      `Covered window attested for this quarter: ${s.covered_from} to ${s.covered_to_exclusive} (exclusive). This is the span the report actually backs, which is NOT necessarily the full quarter; it reflects what the retained audit log spans and does not by itself prove the enforcement stack was running and recording at every moment within it.`,
      "",
      ...(s.shortfall ? ["> COVERAGE NOTICE: " + s.explanation, ""] : []),
    ],
    emptyVerified: () => [],
    readFailed: (reason) => [
      "Covered window: could NOT be determined for this quarter because the " +
        "audit log could not be read. This report makes no coverage claim. " +
        `Reason: ${reason}`,
      "",
    ],
  });
  return {
    title: "Access-log and enforcement summary",
    markdown: [...lead, ...table, ...window].join("\n"),
  };
}

// ── Section 8: data boundary and custody statement ───────────────────

function renderCustody(custody: ReadOutcome<CustodyFacts>): PackSection {
  const lead = [
    "# Data boundary and custody statement",
    "",
    "_Supports an outside-counsel data-handling ask._",
    "",
    // MED-3 / LOW-1: tie the lead to ARCHITECTURE (conditional on the read),
    // not an asserted per-install fact, so it does not contradict a custody row
    // that reads "not reported by this install".
    "By architecture, Sanctuary is designed so the master key is held by the " +
      "firm and never received by the vendor, state is stored encrypted at rest " +
      "under that key, and state data Sanctuary holds leaves the local machine " +
      "only through an explicit, human-approved export. The per-install specifics " +
      "this pack could read are shown below (a value of 'not reported' or 'not " +
      "determinable' means the pack did not probe it, not that the property is " +
      "absent).",
    "",
  ];
  const table = foldOutcome(custody, {
    populated: (facts) => {
      // HIGH-2: the outbound row is a ReadOutcome, so an un-probed/un-walled
      // install renders "not determinable for this install", NEVER a false "yes".
      const outboundRow = foldOutcome(facts.outbound_denied_by_default, {
        populated: (denied) =>
          denied
            ? "yes, for traffic routed through Sanctuary's gateway (this does " +
              "NOT deny egress from other applications, e.g. a browser or " +
              "Office add-in)"
            : "no",
        emptyVerified: () => "not determinable for this install",
        readFailed: () => "not determinable for this install (not probed)",
      });
      return [
        "| Fact | This install |",
        "|---|---|",
        `| Master-key custody | ${fmtCustodyMode(facts)} |`,
        `| Sanctuary-gateway outbound denied by default | ${outboundRow} |`,
        "",
        "By architecture (a product property, not a per-install read), export of " +
          "Sanctuary state is a Tier-1 operation that requires human approval.",
        "",
      ];
    },
    emptyVerified: () => [
      "Per-install custody facts were not supplied for this pack; the " +
        "architectural statement above still holds.",
      "",
    ],
    readFailed: (reason) => [
      "The per-install custody facts could not be read for this pack, so the " +
        "table below is omitted (the architectural statement above still " +
        "holds). " +
        PLACEHOLDER_BADGE +
        ` Reason: ${reason}`,
      "",
    ],
  });
  return {
    title: "Data boundary and custody",
    markdown: [...lead, ...table].join("\n"),
  };
}

// ── Section 9: incident response (CNA Q5) ────────────────────────────

function renderIncidentResponse(): PackSection {
  const body = [
    "# Incident response",
    "",
    "_Maps to CNA Question 5 (AI incident response), delivered by the incident-response layer; NOT included in this build._",
    "",
    "The incident-response runbook, the named human who helps fill in the " +
      "carrier questionnaire, and the quarter's summary of security findings " +
      "raised and resolved are delivered by the incident-response layer.",
    "",
    PLACEHOLDER_BADGE,
    "",
  ].join("\n");
  return { title: "Incident response", markdown: body };
}

// ── Section 10: verification instructions ────────────────────────────

/** One discrete export's outcome + its output filename, for the appendix. */
export interface DiscreteExportView {
  outcome: ReadOutcome<string>;
  filename: string;
}

/** The three discrete exports threaded into the verification appendix. */
export interface DiscreteExportsView {
  transparency: DiscreteExportView;
  audit_chain: DiscreteExportView;
  anchor: DiscreteExportView;
}

function renderVerification(
  signerDid: string,
  discreteExports: DiscreteExportsView
): PackSection {
  const body = [
    "# Verifying this pack as a third party",
    "",
    "_For an underwriter or a client's auditor who does not trust the vendor._",
    "",
    "## 1. Pack integrity (firm identity)",
    "",
    "Each Markdown and export file in this pack is individually SHA-256 hashed " +
      "and Ed25519-signed with the firm's primary identity; the signatures and " +
      "hashes are recorded in `00_pack_manifest.json`. To verify a file " +
      "without any Sanctuary software:",
    "",
    "1. Recompute the file's SHA-256 (for example, `sha256sum <file>`) and " +
      "confirm it matches the `sha256` recorded for that file in the manifest.",
    "2. Verify the Ed25519 signature over that SHA-256 digest against the " +
      `signer public key in the manifest (signer: ${signerDid}).`,
    "3. (Optional) Verify the manifest's own `manifest_signature`. Reproduce the " +
      "canonical body EXACTLY: take the manifest JSON, DROP the " +
      "`manifest_signature` field, sort ALL object keys recursively in ASCII " +
      "order, serialize with NO whitespace, then Ed25519-verify " +
      "`manifest_signature` over the SHA-256 digest of that canonical string, " +
      "using the same signer public key. (Steps 1 and 2 are the primary, " +
      "tool-free integrity checks; this manifest self-signature is a " +
      "belt-and-suspenders check and depends on reproducing the canonicalization " +
      "above.)",
    "",
    "IMPORTANT: the rendered PDF is a human-readable copy and is NOT itself " +
      "cryptographically signed (this is deliberate). Integrity lives in the " +
      "signed Markdown files and the manifest, not in the PDF. Section 1 " +
      "confirms the files are unaltered since the firm signed them; it does " +
      "NOT, by itself, prove the underlying figures are complete or accurate " +
      "(they rest on the firm's honest use of its own signing key). Independent " +
      "assurance of the enforcement history comes only from the transparency " +
      "bundle in step 2, where included.",
    "",
    "## 2. Checking the discrete exports (vendor-independent, where included)",
    "",
    // MED-1 / LOW-3: gate the framing on whether ANY export is actually present,
    // and state that a tool is required (not "only these files and a key").
    ...(discreteExports.transparency.outcome.status === "populated" ||
    discreteExports.audit_chain.outcome.status === "populated" ||
    discreteExports.anchor.outcome.status === "populated"
      ? [
          "The pack gathered the discrete exports below so you can confirm the " +
            "recorded enforcement history on a separate machine, offline, using " +
            "these files, an out-of-band copy of the relevant public key, AND " +
            "the open-source offline verifier named per export. Note the " +
            "DISTINCT keys: the transparency bundle is signed by the Castle Wall " +
            "signer key, not the firm identity above; do not conflate them. " +
            "Independence here is from the VENDOR, not from the firm.",
        ]
      : [
          "For this period the pack contains NONE of the discrete " +
            "enforcement-history exports below (each reads 'Not included'), so " +
            "there is no vendor-independent enforcement-history verification in " +
            "this pack; integrity is limited to the firm-signed files and " +
            "manifest in section 1.",
        ]),
    "",
    "### Transparency checkpoint bundle",
    "",
    ...foldOutcome(discreteExports.transparency.outcome, {
      populated: () => [
        `Included as \`${discreteExports.transparency.filename}\`. Verify it ` +
          "offline with the shipped standalone tool, pinning the Castle Wall " +
          "public key you obtained out of band:",
        "",
        "```",
        `verify-transparency --input ${discreteExports.transparency.filename} --public-key <castle-wall-public-key>`,
        "```",
        "",
        "A PASS (exit 0) confirms the signed checkpoint chain. A stale but " +
          "genesis-rooted bundle can still pass offline verification; only " +
          "public anchoring (below) plus a pinned log key adds freshness and " +
          "fork detection.",
        "",
      ],
      emptyVerified: () => [
        "Not included: this fortress has emitted no signed transparency " +
          "checkpoints yet. When it has, this pack includes the bundle and the " +
          "one-line verify command above.",
        "",
      ],
      readFailed: (reason) => [
        `Not included: the transparency bundle could not be gathered. ${reason}`,
        "",
      ],
    }),
    "### Audit-chain export",
    "",
    ...foldOutcome(discreteExports.audit_chain.outcome, {
      populated: () => [
        `Included as \`${discreteExports.audit_chain.filename}\` (JSONL: entry ` +
          "records plus checkpoint and rotation anchors). Verify its hash chain " +
          "with the audit-chain verifier that ships in the open-source Sanctuary " +
          "CLI (this requires installing that CLI; it is not a standalone " +
          "binary):",
        "",
        "```",
        `sanctuary audit-chain verify --input ${discreteExports.audit_chain.filename}`,
        "```",
        "",
        "The export carries encrypted payload bytes only (no plaintext content " +
          "is exposed).",
        "",
      ],
      emptyVerified: () => [
        "Not included: the audit-chain export was empty for this fortress.",
        "",
      ],
      readFailed: (reason) => [
        `Not included: the audit-chain export could not be gathered. ${reason}`,
        "",
      ],
    }),
    "### Public-anchor (Rekor) evidence",
    "",
    ...foldOutcome(discreteExports.anchor.outcome, {
      populated: () => [
        `Included as \`${discreteExports.anchor.filename}\`. It lets an auditor ` +
          "confirm the checkpoints were publicly anchored (freshness and fork " +
          "detection). It contains salted commitments handed over deliberately, " +
          "never content.",
        "",
      ],
      emptyVerified: () => [
        "Not included: public transparency anchoring (Sigstore/Rekor) is opt-in " +
          "and is not enabled on this install.",
        "",
      ],
      readFailed: (reason) => [
        `Not included: the anchor evidence could not be gathered. ${reason}`,
        "",
      ],
    }),
  ];

  return { title: "Verifying this pack", markdown: body.join("\n") };
}

// ── Section 11: scope and limits (mandatory) ─────────────────────────

function renderScopeAndLimits(): PackSection {
  const body = [
    "# Scope and limits (what this report does and does not prove)",
    "",
    "This honesty page is mandatory. Read it before relying on the report.",
    "",
    "- **Inventory is not exhaustive.** Only wrapped harnesses, gated egress, " +
      "and (on enforced machines) observed destinations are visible. Browser " +
      "ChatGPT, Copilot inside Office, and phones are not.",
    "- **No wire-level proof.** A checkpoint proves the recorded enforcement " +
      "history, not packets blocked on the wire. Per-machine authenticity " +
      "basis can differ (per-event producer-signed on Linux; " +
      "channel-authenticated on macOS).",
    "- **We do not claim per-rule per-flow auditing.** The shipped claim is: " +
      "enforces a signed operator policy, with a tamper-evident log and " +
      "signed enforcement-activity totals.",
    "- **Freshness.** A stale but genesis-rooted bundle can still pass offline " +
      "verification; only opt-in public anchoring plus a pinned log key gives " +
      "an auditor freshness and fork detection.",
    "- **Self-reported binary hash; no remote attestation.**",
    "- **Covered window (both ends).** Audit retention is size/count-based " +
      "(FIFO), not time-based, so a busy fortress can prune early-quarter " +
      "entries (start-side shortfall); and a report generated before the " +
      "quarter closes can only attest coverage through its generation time " +
      "(end-side / partial-quarter shortfall). This report detects and " +
      "discloses both above and states the real covered-through instant, " +
      "never assuming coverage to the quarter end.",
    "- **A covered window proves retention span, not recording liveness.** " +
      "The covered window states what the retained audit log spans. It does " +
      "not prove the enforcement stack was running and recording at every " +
      "moment inside that span: if Sanctuary was off for part of the window, " +
      "AI use during that time was unmanaged and invisible to this report, " +
      "and zero recorded decisions in a period does not mean zero AI " +
      "activity in it.",
    "- **Human vs automated decisions are separated by the gate's `decided_by` " +
      "field.** Human control-point approvals AND denials (an operator decided, " +
      "via the inbox or the interactive channel) are counted in the human rows; " +
      "automated policy, invalid-proof, channel-failure, and timeout decisions " +
      "are counted as automated. Each decision is counted exactly once.",
    "- **Human-review counts** reflect the control-point operator gate, not " +
      "a supervising attorney's per-matter review.",
    "- **Attestations prove acknowledgment, not competence.**",
    "- **Not legal advice, no carrier endorsement.**",
    "",
  ].join("\n");
  return { title: "Scope and limits", markdown: body };
}

// ── Appendix B: per-machine detail ───────────────────────────────────

function renderPerMachineAppendix(): PackSection {
  const body = [
    "# Appendix B: per-machine detail",
    "",
    "Per-machine rows (node id, label, enforcement level, last seen, policy " +
      "version, drift state) with an assurance label (enforced / cooperative / " +
      "unmanaged-attested) are delivered by the fleet-wide pack.",
    "",
    PLACEHOLDER_BADGE,
    "",
  ].join("\n");
  return { title: "Appendix B: per-machine detail", markdown: body };
}

// ── Assembly ─────────────────────────────────────────────────────────

/**
 * Render the full ordered section list for the pack. `productName` is the
 * working title on the cover. The returned sections feed both the signed
 * Markdown report and the PDF (one PDF page-group per section).
 */
export function renderSections(params: {
  input: EvidencePackInput;
  window: QuarterWindow;
  generatedAt: string;
  signerDid: string;
  productName: string;
  aggregation: ReadOutcome<QuarterAggregation>;
  shortfall: ReadOutcome<ShortfallReport>;
  custody: ReadOutcome<CustodyFacts>;
  inventory?: InventorySnapshot;
  discreteExports: DiscreteExportsView;
}): PackSection[] {
  // R3-5: an inventory nobody collected is a FAILED read per source, never a
  // verified empty -- a definitive "No wrapped AI harnesses are recorded ..."
  // census line may only come from a read that actually completed.
  const inv = params.inventory ?? notCollectedInventorySnapshot();
  return [
    renderCover(
      params.input,
      params.window,
      params.generatedAt,
      params.signerDid,
      params.productName,
      params.shortfall
    ),
    renderExecutiveSummary(params.aggregation, params.shortfall, inv),
    renderInventory(inv),
    renderGovernancePolicy(),
    renderTrainingAttestations(),
    renderHumanReview(params.aggregation),
    renderAccessLog(params.aggregation, params.shortfall),
    renderCustody(params.custody),
    renderIncidentResponse(),
    renderVerification(params.signerDid, params.discreteExports),
    renderScopeAndLimits(),
    renderPerMachineAppendix(),
  ];
}
